### ISSUE TITLE
comments: anti-spam e nofollow

### ISSUE THREAD

**Issue by stefanorosanelli** [bedita/bedita#100]
integrare un sistema anti-spam per i commenti (oltre al captcha) tipo:[[BR]]
 * http://akismet.com/development/ - funziona con chiamate tipo web services
 * qualche libreria 3rd-party semplice antispam 

Inoltre aggiungere l'attributo rel="nofollow" agli URL/anchor presente nel testo dei commenti per evitare che aumentino il loro page-rank (soprattutto se non sono moderati)
Vedi:
http://www.google.com/support/webmasters/bin/answer.py?hl=en&answer=81749

**Comment by stefanorosanelli** [comment]
we could close this, seems obsolete
on BE4 we could concentrate on integration with services like Disqus
are we going to have a comments module in BE4?
@xho @batopa

**Comment by xho** [comment]
I agree with @stefanorosanelli about some sort of integrations with third party tools in BE4. I close the issue.
