### ISSUE TITLE
Invalidate object cache on related Annotation update

### ISSUE THREAD

**Issue by fquffio** [bedita/bedita#1011]
When deleting or updating an Annotation, it might happen that the related object's cache becomes obsolete without being invalidated.

This happens because many models have `Annotations` amongst their `frontend` model bindings, and no specific invalidation logic exists yet.

@batopa @didoda @stefanorosanelli Should we deal with this scenario, or delegate the cache invalidation to the application, when it is actually needed?

**Comment by batopa** [comment]
obsolete
