### ISSUE TITLE
Validate input data in bedita setup shell script

### ISSUE THREAD

**Issue by batopa** [bedita/bedita#1013]
To mitigate potential risks in `bedita setup` script when writing database connection data in `config/app.php` we should validate the user input data.

Using the `Cake\Filesystem\File` class also helps writing file more safely.

See https://github.com/bedita/bedita/pull/1005#pullrequestreview-4083907

**Comment by fquffio** [comment]
This issue should now be obsolete, after #1371.

@stefanorosanelli @batopa Shall we close this?

**Comment by didoda** [comment]
obsolete
