### ISSUE TITLE
[API] Implements /categories endpoint

### ISSUE THREAD

**Issue by batopa** [bedita/bedita#1017]
Implement basic functionality.
### Get all paginated categories

``` http
GET /categories
```
### Get single category

``` http
GET /categories/:id
```
### Add category

``` http
POST /categories

{
    "data": {
         "label": "useless category",
         "object_type": "document"
    }
}
```
### Edit (patch) category

``` http
POST /categories

{
    "data": {
         "id": 1,
         "label": "super useless category"
    }
}
```
### Delete category

``` http
DELETE /categories/1
```

Evalute if implementing PUT request too.

We need also to display the categories id in `GET /objects` response, now just `label` and `name` are shown.

**Comment by fquffio** [comment]
Just a couple of questions that arose when implementing POST: should we allow clients to set an `area_id` for a Category? If yes, which Areas should be available for this choice? Maybe only the Publication associated to the current frontend and `NULL`?

Also: should we prevent clients from reading (and especially deleting) categories associated to publications other than the one set for the frontend?

@batopa @vallo87 @stefanorosanelli

PS: (last question, I swear!) should clients be allowed to write/delete a Category only if its object type is writable? Do we need an additional piece of configuration to permit a more fine-grained customization?

**Comment by batopa** [comment]
Very good questions.

I think categories created from client should be placed in the related frontend `area_id` without specifing it. By default I don't think that the client should can setting the `area_id`. The very hard thing is how to distinguish permanents from volatile categories. I wouldn't want that every user can delete any categories.

About the last question I think that operations on categories of object type not writable shouldn't be allowed.

 But I am pretty confused :confused:  and I would prefer have some other opinions.

**Comment by fquffio** [comment]
Uhm… I'm not sure: what are permanent and volatile category? 😕

**Comment by batopa** [comment]
:smile: you are right, indeed it's not clear at all.

I mean categories created from the backend ("permanent"). I think that those categories shouldn't be deleted from anyone. 
Instead for "volatile" I mean categories created from a generic frontend user.

**Comment by fquffio** [comment]
😱  I'm afraid we have no means to tell the ones from the others. I'd say that if the `/categories` endpoint is enabled in an API frontend, all categories that satisfy the conditions you wrote above become writable. An application that needs such a feature would need to implement its own validation logic to make some categories not-writable by the frontend.

**Comment by batopa** [comment]
I agree, we would start simple, so don't be afraid :smile_cat:

**Comment by vallo87** [comment]
@fquffio as for your questions
1- i agree with bato on the first one
2 - yes i would separate them using the area id
3 - yes i'd bind the writability of a category to the that of its object type

**Comment by fquffio** [comment]
Current (proposed) implementation has:

```
GET /categories
GET /categories/:id
POST /categories
PUT /categories/:id
DELETE /categories/:id
```

All endpoints are limited to categories with `area_id` either set to `NULL` or to the current frontend publication ID. Any write action is furtherly limited to categories with `object_type_id` set to a writable object type.

`POST` method can be used both for creating new categories and editing existing ones (by passing an `id` in the request payload, as it happens for regular objects). In the latter case, `POST` acts like a `PATCH`. `PUT` method, on the other hand, completely replaces category's data, thus required fields are the same as when creating a new category, plus `id`.

@vallo87 Can you perform some early testing and tell me if there's anything missing or wrong with this implementation? Then we could open a PR and write some docs.

**Comment by vallo87** [comment]
sure! i'm on it
