### ISSUE TITLE
Validate embed code for videos

### ISSUE THREAD

**Issue by fquffio** [bedita/bedita#1019]
When saving a multimedia of type video, if embed code is provided, it should be validated. Failing to do so might result in malformed HTML code that breaks the whole page in backend.

XSS filter doesn't really quite apply to this case, as far as I can see, as this field is supposed to contain HTML by design. Right, @batopa ?

**Comment by batopa** [comment]
@fquffio uhm... I'm not sure how that field is treated. I think the idea of @qwerg is that it could contain everything. If the embed content is intended just for HTML we could validate it before save but however a valid HTML could contain malicious scripts.

I would also suggest to escape it before show in html doing something as `{$object.body|escape}`.

**Comment by batopa** [comment]
obsolete
