### ISSUE TITLE
Print view

### ISSUE THREAD

**Issue by fquffio** [bedita/bedita#1023]
In some cases it might come in handy to give users the ability to print BEdita objects. A print view is therefore needed.

I see that an implementation of print view is already present but commented out. It was supposedly introduced in #196 and later abandoned. We should wake up this sleeping princess (in devil's castle) and bring print view back to its old glory.

Print button should probably be discrete enough to not interfere with the established workflow of the many people that use BEdita on a daily basis. Maybe it should be an opt-in. @rzecchini @qwerg

**Comment by batopa** [comment]
obsolete
