### ISSUE TITLE
Bake models for all database tables

### ISSUE THREAD

**Issue by fquffio** [bedita/bedita#1075]
We still have some tables in our database that do not have a specific model class.

This is quite fine as long as we do not use such tables, but has some drawbacks anyway. For instance, we are forced to keep our Migrations in the App's namespace, because if they were in *BEdita/Core* plugin (as they are supposed to be) some shell commands like `bin/cake bake migration_diff ...` would not work as expected.

Therefore we should bake Table classes for all database tables that still miss one on their own.

**Comment by stefanorosanelli** [comment]
Missing Tables have been baked
 * default tests are incomplete, keep them like that?
 * entities tests are missing, should we create them?

During `bake` operation i got `<warning>Bake cannot generate associations for composite primary keys at this time</warning>` for `object_relations` and `relation_types` - something to worry about? :smiley:

@batopa @fquffio
