### ISSUE TITLE
Upgrade to CakePHP 3.4

### ISSUE THREAD

**Issue by batopa** [bedita/bedita#1077]
We need to upgrade to CakePHP 3.4

https://bakery.cakephp.org/2017/02/12/cakephp_340_released.html

https://book.cakephp.org/3.0/en/appendices/3-4-migration-guide.html

**Comment by fquffio** [comment]
As a side effect of upgrading to CakePHP 3.4, the requirement for PHP version rises from 5.5.9 to 5.6.0. We should update that requirement in our `composer.json` as well, and drop Travis CI tests for PHP 5.5.

@batopa @stefanorosanelli Does this look right to you?

**Comment by stefanorosanelli** [comment]
It's ok for me

**Comment by fquffio** [comment]
All the three PRs have been accepted and merged. Closing.
