### ISSUE TITLE
Avoid subsections load from selected sections in backend

### ISSUE THREAD

**Issue by stefanorosanelli** [bedita/bedita#1078]
Define one or more sections ID via config that will not load their subsection in some publication trees operation in backend. In case of many many (like thousands) subsections these operations are too slow

- AJAX call like `/pages/tree/{id}`
- `/pages/tree/{id}/option`
- `/pages/tree/{id}/checkbox`
- in `model/tree.php` method `getAllRoots(...)`

**Comment by batopa** [comment]
Pay attention that not loading sections in object detail can lead to unwanted behaviors when saving the object as removing the object from hidden sections.
