### ISSUE TITLE
Object view in a hidden subsection 

### ISSUE THREAD

**Issue by stefanorosanelli** [bedita/bedita#1080]
After #1078 we have to handle these use cases:

- view of a hidden subsection: don't show position *select*, just display position path in tree, un changeable - saving this section position must remain the same
- view of an object in a hidden subsection: just show its position on this subsection (how?), without showing hidden tree branch - position is unchangeable and must remain the same after save

**Comment by didoda** [comment]
"view of an object in a hidden subsection": object could reside in multiple positions; system should show both changeable and unchangeable positions, so that it's always possible to put/remove object from a changeable position, leaving unchangeable positions set.
