### ISSUE TITLE
Update CI builds

### ISSUE THREAD

**Issue by fquffio** [bedita/bedita#1084]
We should evaluate whether it's a good thing to update our CI builds.

What I would like to do:
 - [x] Introduce [PHPStan](https://github.com/phpstan/phpstan), a relatively new static code analysis tool for PHP ≥ 7.0 that could furtherly help finding bugs soon. This would become a new job in our Travis CI build.
 - ~Use [Stickler CI](https://stickler-ci.com/) for coding style checks. It supports CakePHP coding standards out-of-the-box and a bot adds comments to lines that aren't formatted as expected, making it easier to spot coding style problems. The corresponding job in our Travis CI build could then be removed.~
 - ~Update [Codecov](https://codecov.io) configuration. Codecov moved to a YAML-based configuration several months ago, and we still haven't updated it. Time to catch up?~ 😄

**Comment by stefanorosanelli** [comment]
Ok to introduce **PHPStan** in Travis
We could also give a try with **Stickler CI** if it's more detailed than our coding style travis job.
