### ISSUE TITLE
Review test coverage

### ISSUE THREAD

**Issue by stefanorosanelli** [bedita/bedita#1086]
Some test methods require `@covers` declaration to have real unit tests and avoid misleading coverage information

**Comment by fquffio** [comment]
Apart from being more earnest about coverage (that should have partly been addressed by 	325dabb) we should totally increase coverage for the following classes:
- [x] `BEdita\API\Auth\JwtAuthenticate` — just a couple of cases
- [x] `BEdita\API\Network\CorsBuilder` and `BEdita\API\Middleware\CorsMiddleware` — probably just adding a couple reasonable `@covers` is enough
- [x] `BEdita\Core\Configure\Engine\DatabaseConfig`
- [x] `BEdita\Core\Model\Action\*` — some edge cases are not taken into account
- [x] `BEdita\Core\Model\Entity\ObjectEntity` and `BEdita\Core\Model\Entity\Property` — magic getters and setters are lacking tests
- [ ] `BEdita\Core\TestSuite\ShellTestCase` and `BEdita\Core\TestSuite\Fixture\TestFixture` — these classes are **completely untested**! This should be high priority, but how to test such components? @stefanorosanelli @batopa

**Comment by batopa** [comment]
`BEdita\Core\TestSuite\ShellTestCase` and `BEdita\Core\TestSuite\Fixture\TestFixture` will be treated in a specific issue #1115

**Comment by batopa** [comment]
Closing after PR #1100 was merged
