### ISSUE TITLE
Manage applications, endpoints and endpoint permissions via shell

### ISSUE THREAD

**Issue by fquffio** [bedita/bedita#1096]
We need a way to easily manage Applications, Endpoints and EndpointPermissions entities. While in future we'll want a way to manage them via APIs, an immediate solution that could also be a valuable feature is to provide shell management.

It should be possible to:
- [ ] create a new application (`bin/cake applications create <name> [<description>]`)
- [ ] list existing applications (`bin/cake applications ls [--enabled]`)
- [ ] enable/disable an existing application (`bin/cake applications enable|disable <name|id>`)
- [ ] renew API token for an existing application (`bin/cake applications renew_token <name|id>`)
- [ ] remove an existing application? (`bin/cake applications rm <name|id>`)
- [ ] create a new endpoint (`bin/cake endpoints create <name> [<description>] [--object-type=<name|id>]`)
- [ ] list existing endpoints (`bin/cake endpoints ls [--enabled]`)
- [ ] enable/disable an existing endpoint (`bin/cake endpoints enable|disable <name|id>`)
- [ ] remove an existing endpoint? (`bin/cake endpoints rm <name|id>`)
- [ ] create a new endpoint permission (`bin/cake endpoint_permissions create <read> <write> [--application=<name|id>] [--endpoint=<name|id>] [--role=<name|id>]`)
- [ ] list endpoint permissions (`bin/cake endpoint_permissions ls [--application=<name|id>] [--endpoint=<name|id>] [--role=<name|id>]`)
- [ ] remove an existing endpoint permission? (`bin/cake endpoint_permissions rm [--application=<name|id>] [--endpoint=<name|id>] [--role=<name|id>]`)

I know this quite a bunch of stuff, so it's probably a good idea to split it into multiple sub-tasks… 🤔 Also, we might want to start with a subset of these shell commands, and just add a draft for the remaining with a notice to the end user that the command they're attempting to use is not yet implemented.

**Comment by didoda** [comment]
Shell classes with methods (empty) and docs are ready; methods must be developed. We could create subtasks, one for each shell, to continue development.
