### ISSUE TITLE
Move migrations data to Core plugin

### ISSUE THREAD

**Issue by stefanorosanelli** [bedita/bedita#1099]
After #1075 all `config/Migrations` files should be moved to `plugins/BEdita/Core/config/Migrations`

**Comment by stefanorosanelli** [comment]
@fquffio  after wiki update you can close the issue

**Comment by fquffio** [comment]
[Wiki page](https://github.com/bedita/bedita/wiki/%5BBE4%5D-Using-migrations) updated. I'm closing this issue. Feel free to reopen it if something isn't OK with docs.
