### ISSUE TITLE
Relation parameters

### ISSUE THREAD

**Issue by fquffio** [bedita/bedita#1122]
After #1114 we'll also need a proper handling of relation parameters.

Each relation defined can have `relations.params` column populated with a definition of allowed parameters. The proposed format for such definition is [JSON Schema](http://json-schema.org/).

Then, each row in `object_relations` can have its `object_relations.params` column populated if and only if the JSON in `object_relations.params` validates against the schema defined in the related `relations.params` column.

Open questions:
1. What should happen if a relation definition changes when relations of that kind already exist? Should we re-validate all params? How should we behave in case issues arise?
2. How are relation parameters displayed in JSON API response? [According to the spec](http://jsonapi.org/format/#document-resource-identifier-objects) it looks like we should put all these information in the `meta` object in each relationship definition.
3. What's the correct response in case a relationship params fail to validate? **400 Bad Request** or rather silently ignoring such parameters?

**Comment by fquffio** [comment]
@bedita/core Please share your opinions. 😃

**Comment by stefanorosanelli** [comment]
About the 3 questions:
 2. i would put in `meta` as you suggest
 3. if a relationship param fail to validate, i would avoid error (as Robustness Principle suggests) - some sort of warning/information in a `meta` response could be useful, in general, not just here
 
As for 1. probably we will have to revalidate everything or keep everything and give warnings on single requests as params are no more valid. Difficult to say at the moment, but some strategy is needed. 
Or we can send user threatening messages as he tries to change a definition :smiling_imp:
