### ISSUE TITLE
Properties definitions for object types

### ISSUE THREAD

**Issue by stefanorosanelli** [bedita/bedita#1123]
After #984 object types properties are available via `/properties` but not data are currently displayed.

This is a master issue for subtasks to be implemented in separate issues

- [ ]  `objects.custom_props` field is added: a JSON validated field (JSON-SCHEMA), its keys will be shown in  `attributes` section - `custom_props` will never appear in any POST/GET/PATCH request or response - every `key` has its own JSON-SCHEMA - basic templates are available but it is possibile to create a custom type

- [x] `/object_types` will display a `json_schema` section with JSON-SCHEMA of its properties (should it appear in `meta`?)

- [x] `object_types.hidden` - list of `attributes` to hide, even if present on db those fields are ignored in every operation. This list should appear in `/object_types` and be modifiable via API

- [x] `/object_types/{name|id}/properties` will display a complete list of user defined properties and not *core* properties for a given object type - usigng `/properties` endpoint we should be able to do CRUD operations on user-defined properties for an object type: these properties will appear in `attributes` section of a request/response and are no different than core properties. This should already work as expected, but some modifications could be necessary.

**Comment by fquffio** [comment]
Most of the tasks hereby described have been completed in a slightly different way. I'm closing this issue as it has become obsolete.
