### ISSUE TITLE
Relation cardinality on left/right items

### ISSUE THREAD

**Issue by stefanorosanelli** [bedita/bedita#1124]
Introduce explicit relation cardinality using dedicated `relations` columns:
 * `right_max` and `left_max` to indicate maximum number of objects expected, if `NULL` no limit is set given
 * `right_min` and `left_min` minimum number of objects - are these columns necessary?

On create / udpate / delete operations on object relations those limits MUST be checked.
This will be done after #1114

**Comment by didoda** [comment]
obsolete
