### ISSUE TITLE
beThumb lib has an old implementation that doesn't represent a modern pattern

### ISSUE THREAD

**Issue by vallo87** [bedita/bedita#1131]
beThumb lib read bedita configure mediaRoot in it's constructor and uses it to resample the image in order to create a thumbnail.

this is a problem now. 
public method image should do 2 things:
1 - accept a parameter to force service path for it to correctly operate and generate thumbnail outside bedita mediaRoot
2 - as a backup (and backward compatibility) read the mediaRoot configure when it really needs it (inside method image? or resample? reset?)

first cure is to make it reload the configuration in the reset method

**Comment by batopa** [comment]
obsolete
