### ISSUE TITLE
shell publication - remove publication, view info about publication data

### ISSUE THREAD

**Issue by didoda** [bedita/bedita#1134]
Shell publication provides methods to create publication and contents:
 - `create [-d <depth> [-ns <sublevel-number-of-sections>] [-nd <leafs-number-of-documents>]`
 - `createContents [-t <type>] [-n <number>] [-pid <parentId>] [-tpf <titlePostFix>] [-uri <uriInsideMediaFolder>]`

Useful extra methods could be:
 - `remove -ids <publicationIds> (comma separated id list string)` // delete list of publications
 - `stats [-id <publicationId>]` // basic info on publication + summary of objects inside publication, count by type

**Comment by batopa** [comment]
We have a bug when removing publications. The script correctly cleans the tree but then remove just the publication leaving all the sections orphans.

**Comment by didoda** [comment]
publication remove should also remove contents that are not inside "other" sections/areas, in order to not leave orphans contents. I'd add an option to script to enable 'remove all contents that are not in other publications/sections'
