### ISSUE TITLE
Unique names are not generated properly in CTI

### ISSUE THREAD

**Issue by fquffio** [bedita/bedita#1154]
When a table extends another table via CTI, some behaviors (`UniqueNameBehavior`, for instance) are not triggered properly unless specifically bound to the descendants tables as well.

Currently we have some issues when saving objects with similar titles, as `UNIQUE` constraints on `objects.uname` column prevent latter saves.

**Comment by stefanorosanelli** [comment]
We have the same behavior also with `documents` object type, using only `objects` table: 400 error when using an existing title... 

Another tricky scenario:
 * create a document with empty title - OK
 * create another document with empty title - 400 response
