### ISSUE TITLE
Check schema should ignore tables of other plugins

### ISSUE THREAD

**Issue by stefanorosanelli** [bedita/bedita#1163]
Two problems with our migrations/schema system

 * `bin/cake db_admin check_schema` and `bin/cake bedita setup` give schema errors when using plugins with own tables - those tables must be ignored
 * `bin/cake bake migration_diff -p MyPlugin` or `-p BEdita/Core` should ignore tables owned by other plugins

**Comment by didoda** [comment]
obsolete
