### ISSUE TITLE
Retrieving relationships for trashed entity

### ISSUE THREAD

**Issue by edoardocavazza** [bedita/bedita#1168]
Deleting an entity which is related with other objects should remove (or hide?) its relationships.

**Comment by stefanorosanelli** [comment]
Related objects that are deleted should not be visible.

If relations must be deleted as an object is trashed is not clear... probably best solution is to keep them: as the object is restored, its relations are restored too, probably that's the expected behavior

**Comment by edoardocavazza** [comment]
So we could just hide them in the response.

**Comment by stefanorosanelli** [comment]
Solved in #1169
Closing
