### ISSUE TITLE
Shell test BeditaShellTest: nasty behaviour with sqlite, in following shell test

### ISSUE THREAD

**Issue by didoda** [bedita/bedita#1178]
Using branch `issue/v4/1096-manage-applications-endpoints-and-endpoints-permissions-via-shell`, there's an issue with class `BeditaShellTest`, using sqlite connection (i.e. in `config/app.php`: `['Datasources' => ['test' => ['url' => 'sqlite:///tmp/bedita4.sqlt']]]`).

- Launching phpunit separately on `plugins/BEdita/Core/tests/TestCase/Shell/BeditaShellTest.php` and `plugins/BEdita/Core/tests/TestCase/Shell/EndpointPermissionsShellTest.php` works fine.
- Launching phpunit on `plugins/BEdita/Core/tests/TestCase/Shell/` folder returns error on `EndpointPermissionsShellTest` (first test using fixtures `roles`, `object_types`, `endpoints`, `applications`, `endpoint_permissions`). Failing nature: `SQLSTATE[23000]: Integrity constraint violation: 19 FOREIGN KEY constraint` / during `DELETE FROM roles`.

Something goes wrong in `BeditaShellTest`, when db connection alias is set (`ConnectionManager::alias('test', 'default')`).

Temporarily file `BeditaShellTest` has been renamed to `ZZZBeditaShellTest`, to skip travis errors.

**Comment by didoda** [comment]
Another unexpected behavior: launching all tests with phpunit, at the end database has table `relations`. Expected behavior: empty database (no tables).

**Comment by stefanorosanelli** [comment]
`BeditaShellTest` has been (temporary) moved to `SetupShellTest` to avoid this problem
