### ISSUE TITLE
Object cache concurrency issues in distributed systems

### ISSUE THREAD

**Issue by fquffio** [bedita/bedita#1182]
When BEdita is installed in a distributed system, and Redis is used as a shared cache engine, issues with object cache arise due to concurrency in read/write operations.

As a result, we have some corrupt `_index` keys, that cause some other keys to be "orphan" (not referenced in any `_index`). Such keys are never invalidated, and might cause obsolete contents to be returned.

After an analysis of @didoda we came up with four possible solutions:
1. Introduce some kind of distributed lock when performing _any_ (read+write) operation that involves `_index` cache. Redis itself can be used for this. We should be _very_ careful about starvation, but PHP's `max_execution_time` alone can probably be a solution.
2. Treat `_index` keys as [lists](https://redis.io/topics/data-types#lists) to mitigate concurrency issues. This should solve concurrency when writing, but can still create orphans in a case like this:
   - Server **A** wants to invalidate cache for object 1. He reads `1_index` to decide which keys must be invalidated.
   - Server **B** wants to add a new `1_children_abcd` cache key. It writes its value to `1_index` cache, and writes `1_children_abcd` key with its value.
   - In the meanwhile, server **A** has invalidated all cache keys it found in `1_index`. `1_children_abcd` _was not_ amongst those values at the time Server **A** performed read. Server **A** now deletes `1_index`.
   - `1_children_abcd` is now an "orphaned" key — every following invalidation of cache for object 1 will be unaware of its existence, thus `1_children_abcd` will never be invalidated.
3. Treat `_children` keys (and any other key that is currently being written to `_index`) as an [hash](https://redis.io/topics/data-types#hashes). This should make `_index` keys useless, and should hopefully move any concurrency concern within Redis itself — that means no concurrency problem, ❤️ Redis.
4. Use some sort of home-made set structure with a single `_children` key that encapsulates all other keys in a serialized associative map. This has the tremendous drawback of generating huuuuuuuuuge cache keys, that take a lot of time to download when reading and to upload when writing — this in practice defies the purpose of cache. Also, it doesn't actually solves all problems with concurrency.

**Comment by fquffio** [comment]
I'd go with 3.

2 and 4 are not actually solving the problem — if they are not creating new ones.

1 would be a good option, but surely Redis already uses a similar approach at a low level when using proper data sets, so in this case we would probably be replicating that logic in a less-efficient way.

**Comment by stefanorosanelli** [comment]
Agreed, 3. (Redis hash) seems to be the best solution. 
Concurrency problems are not completely excluded, but the orphaned keys and corrupt `_index` problems sould be solved.

**Comment by didoda** [comment]
Solution 3 does the job, and it seems less complicated than other approaches.

**Comment by fquffio** [comment]
Closing as resolved in #1538.
