### ISSUE TITLE
500 error saving special chars in text fields

### ISSUE THREAD

**Issue by edoardocavazza** [bedita/bedita#1185]
Saving entities with special chars (as emojis) in a text field (eg `body` or `description`) fails with 500 code status and message: `SQLSTATE[HY000]: General error: 1366 Incorrect string value: \u0027\\xF0\\x9F\\x8D\\x8C\u0027 for column \u0027description\u0027 at row 1`

**Comment by stefanorosanelli** [comment]
To summarize: error depends on encoding settings on database connection and on database/table/column itself. 
With the correct `utf8mb4` encoding everything works as expected.

The only problem is: an unexpected encoding in input should not return a 500 error code as response, but (probably) a 400 bad request.
Do we open a new issue for that? @fquffio @didoda

**Comment by fquffio** [comment]
I'd go with this one.

**Comment by didoda** [comment]
Agreed with a new issue for unexpected http 500 response code

**Comment by stefanorosanelli** [comment]
Changed issue title a little bit - we may work on this one to solve the 500 error issue 

Votes 2 : 1 - sorry @didoda  :smiley:

**Comment by didoda** [comment]
With the various commits, no 500 error on saving data neither 400.
Trying various databases (sqlite, postgres, mysql, mem) with phpunit test, only mysql silently fails (some asserts fail, but `save` is performed): it saves data but emojis are removed from text field(s). It's a known issue: as said above, mysql needs `utf8mb4` encoding (db and tables). Bug seems resolved to me.
