### ISSUE TITLE
Link for available objects to relate with another one

### ISSUE THREAD

**Issue by edoardocavazza** [bedita/bedita#1186]
In order to display a list of available objects to connect through a relationship with another one, maybe would be useful an additional entry in the `links` section of a relationship API call which contains the url to retrieve the list.

Examples:
```js
// documents/5/relationships/authors
{
    "data": [...],
    "meta": {...},
    "links": {
        "self": "...",
        "home": "...",
        "available": ".../objects?filter[type][]=profiles&filter[type][]=authors",
     }
}
```
or
```js
// users/1/relationships/roles
{
    "data": [...],
    "meta": {...},
    "links": {
        "self": "...",
        "home": "...",
        "available": ".../roles",
     }
}
```

**Comment by stefanorosanelli** [comment]
We surely need some method to retrieve all possible _relationable_ objects 

Your proposal is interesting, we should probably investigate other possible solutions and then decide
