### ISSUE TITLE
[API] Pagination size configuration

### ISSUE THREAD

**Issue by stefanorosanelli** [bedita/bedita#1195]
As explained here 
http://bedita.readthedocs.io/en/4-develop/endpoints/parameters.html#pagination

we need seom default settings for `default` and `max` page_size
probably an hardcoded `max` of `max` limit is necessary to avoid dangerous configurations

**Comment by stefanorosanelli** [comment]
Config layout proposal:
```php
    'Pagination' => [
        'defaultSize' => 20,
        'maxSize' => 100,
    ],
```

with max possible `maxSize` 500, hardcoded...

**Comment by fquffio** [comment]
CakePHP's [Paginator Component](https://api.cakephp.org/3.4/class-Cake.Controller.Component.PaginatorComponent.html#$_defaultConfig) uses `limit` for default page size and `maxLimit` for maximum requested page size.

**Comment by didoda** [comment]
From `PaginatorComponent` in `vendor/cakephp/cakephp/src/Controller/Component`:
```
protected $_defaultConfig = [
        'page' => 1,
        'limit' => 20,
        'maxLimit' => 100,
        'whitelist' => ['limit', 'sort', 'page', 'direction']
    ];
```
`limit` and `maxLimit` seem fine

**Comment by stefanorosanelli** [comment]
Yes, that's what Cake use but we use `page` and `page_size` in query string and `meta` response. I would use that as reference. 
However, it's a matter of tase :wink:
