### ISSUE TITLE
Signup endpoint for user registration

### ISSUE THREAD

**Issue by stefanorosanelli** [bedita/bedita#1203]
A new `/signup` endpoint is needed to:

* allow users registration/signup
* `POST /signup` will be called anonymously
* `data.attributes` requires `username`, `password` and `email`
* in `meta` key of signup post an `activation_url` or `redirect_url` can be specified, but both could be set via configuration
* `/signup?code={code}` will be responsible for registration confirmation giving also an HTML browser response

**Comment by fquffio** [comment]
The flow should now be complete. @batopa Can we close this issue?

**Comment by batopa** [comment]
Yes, if necessary we'll work on refinements/improvements in specific issues.
