### ISSUE TITLE
CTI: avoid duplicate fixes in Query in inheritanceBeforeFind

### ISSUE THREAD

**Issue by batopa** [bedita/bedita#1206]
After PR #1199 we have removed the check on primary in `Table::inheritanceBeforeFind()` so, for example, when is executed a find on a table with CTI

```php
$user = TableRegistry::get('Users')->find()->first();
```

the fixes on `Query` are executed more times. We could avoid this using a flag in `\ArrayObject $options` as commented in https://github.com/bedita/bedita/pull/1199#issuecomment-297713624

**Comment by fquffio** [comment]
The approach we hoped to work, doesn't work. 🙃 Since things are working, we're moving this to a further milestone.

**Comment by fquffio** [comment]
After #1269 the method mentioned in issue description simply doesn't exist anymore. 🙃  This issue should be considered obsolete.
