### ISSUE TITLE
Reduce the dimension of JWT access token

### ISSUE THREAD

**Issue by batopa** [bedita/bedita#1207]
The JWT generated to grant access to user is overweight. We generate it using all user data but we can reduce its weight using just useful and not sensitive information.

If client needs all user data it can use `GET /auth`.

I think we could store in JWT the user id and roles, something like

```json
{
  "id": 1,
  "roles": ["editor", "basic"]
}
```

or

```json
{
  "id": 1,
  "roles": [
    {
      "id": 14,
      "name": "editor"
    }
    {
      "id": 27,
      "name": "basic"
    }
  ]
}
```
@bedita/core what do you think?

**Comment by stefanorosanelli** [comment]
Agree, I would probably add `username` also but for other data `GET /auth` is the way to go.

**Comment by batopa** [comment]
Maybe we could define a default and make it configurable.
