### ISSUE TITLE
Many warnings are polluting error log

### ISSUE THREAD

**Issue by fquffio** [bedita/bedita#1252]
Right now, `error.log` is a bit polluted by warning messages that are caused by a behaviour that I personally consider rather normal and not harmful.

The scenario is a bit knotty:
- let's suppose there is a **plugin** that adds a table for an object type called "MyObjectType"
- let's also suppose that there is a relation called "MyRelation" between "MyObjectType" and any other object type
- let's suppose that it does exist an object of type "MyObjectType" with ID = 2
- issuing a request `GET /my_object_type/2/my_relation` or `GET /my_object_type/2/relationships/my_relation` will cause the server to return a correct response, but a warning will be written to `BEDITA/logs/error.log` even if everything apparently did go well

Steps to reproduce from the console:
```
$ bin/cake console

>>> // First, we must restore the logger, since `ConsoleShell` drops all loggers before initializing.
>>> \Cake\Log\Log::setConfig('error', ['className' => 'Console', 'stream' => 'php://stdout'])

>>> // Next, we need to initialize `ListRelatedObjectsAction`
>>> $MyObjectType = \Cake\ORM\TableRegistry::get('MyObjectType')
>>> $action = new \BEdita\Core\Model\Action\ListRelatedObjectsAction(['association' => $MyObjectType->MyRelation]);

>>> // Now, we execute the action. This will cause a warning to be written to error log (in this case, stdout).
>>> $action->execute(['primaryKey' => 2, 'filter' => []])->count()
2017-05-24 22:04:14 Warning: Record not found in table "object_types"
```

This is caused by the fact that in `TableLocator` we log a warning every time an attempt is made to load a table whose name doesn't meet some requirements. Before 2526b2f this didn't happen, since the error was being logged only in case it wasn't a `RecordNotFoundException`.

However, I'm not quite sure how to proceed. 🤔  Surely it's a weird thing, but I'm not quite sure that it should be logged. Frankly, I'd _at least_ lower the logging level in case the exception is a `RecordNotFoundException`, but I'd probably prefer to revert to the old behaviour (record not found -> not logged at all).

What do you think?

**Comment by didoda** [comment]
"a table whose name doesn't meet some requirements" and `RecordNotFoundException` don't sound relate with each other, I mean "semantically".
'Record not found' should not be an issue, it should be just an empty set result, shouldn't it?
If it is so, then I agree with reverting to previous behaviour
```
if (!($e instanceof RecordNotFoundException)) {
    $this->log($e, 'warning');
}
```

**Comment by stefanorosanelli** [comment]
Trying to load a non existing object type could be a symptom of a problem that I would normally not hide.

Why in your example a non existing object type is searched? Is it avoidable?

**Comment by fquffio** [comment]
In the scenario described above, the `ListRelatedObjectsAction` builds a custom association named `_InverseAssociation`. This is required to perform match correctly, and the association name is purposely non-standard in order to avoid conflicts.

If this inverse association's source is a real table class in BEdita/Core plugin, the locator returns sooner. If it isn't (either because it belongs to another plugin, or because it is not a real table, e.g.: "News") an attempt is made to load an object type named "_InverseAssociation". This attempt fails, but by then `$option['className']` would have been set correctly, and the locator would eventually return the correct result.

As far as I can tell, this is _not_ avoidable unless we either change the behaviour of table locator, or we refactor it heavily making it likely less efficient — and it better be so.

If an attempt to load a non-existing object type is made, things already go quite wrong, since ObjectsController performs proper checks. Also, a list of generic instances returned by TableLocator (i.e., calls to TableRegistry that did return a generic table object as a real table class could not be found) is available through `array_keys(\Cake\ORM\TableRegistry::locator()->genericInstances())`.

**Comment by stefanorosanelli** [comment]
That's ok but `TableLocator` is invoked not only in `ObjectsController`
What about an allowed failure for `_InverseAssociation` ? 
Other non existing load attempts should be logged or not?
