### ISSUE TITLE
Error on saving artwork

### ISSUE THREAD

**Issue by simone-sanfratello** [bedita/bedita#1272]
Saving an artwork, I get

http://(domain)/artworks/save

```
Notice (8): Undefined index: description [APP/models/behaviors/notify.php, line 163]
Warning (2): Cannot modify header information - headers already sent by (output started at /home/bedita3/iebook/cake/libs/debugger.php:686) [CORE/cake/libs/controller/controller.php, line 742]

```

what I did: 

In an artwork, I add a multimedia document; the document is without description
Then, when I save the artwork, I got the error

contatct me for the data example

**Comment by stefanorosanelli** [comment]
Hi @simone-sanfratello,
it seems there's a missing check on array data upon object change notification.

We'll try to fix it right away.

**Comment by stefanorosanelli** [comment]
Problem is fixed in **BEdita 3** stable branch `3-corylus`
You can pull to test it.
