### ISSUE TITLE
Error response priority

### ISSUE THREAD

**Issue by stefanorosanelli** [bedita/bedita#1286]
We need a predictable error response priority in case of multiple possible errors.

Example requests: 
 1. `GET /documents/xxxxx`
 2. `GET /documentsxxxxx`

With a missing/wrong API KEY and `Security.blockAnonymousApps` set to `true` we get:
 1. **406** (bad content type) on missing or wrong `Accept` header - **403** with right `Accept`
 2. **404** always, with wrong/right `Accept` or with bad/good API KEY 

What's the expected behavior?

Priority proposal:
 1.  **403** on missing/wrong API KEY if API KEY is mandatory
 1. **401** in case of unauthenticated request, when authentication is requested
 1. **406** if there's a content negotiation problem probably **405** and **415** too
 1. **404** if requested resource was not found or other possible errors like **400** or **500**

This will help us in diagnostics, logging & assistance

**Comment by stefanorosanelli** [comment]
see #1012

**Comment by didoda** [comment]
obsolete
