### ISSUE TITLE
Docker compose

### ISSUE THREAD

**Issue by stefanorosanelli** [bedita/bedita#1312]
* [x] docker image for **bedita/manager**
 * [ ] docker compose file

**Comment by fquffio** [comment]
Docker image for `bedita/manager` should be on its way, waiting for PR to be reviewed and approved.

I'm now working on Docker Compose template, but I'm wondering where it should stay… 😕 Should it be placed in `bedita/bedita`, in `bedita/manager`, or in its own repository? For now I'll just make a Gist, but we should probably make a more solid decision.

**UPDATE**: [`docker-compose.yml`](https://gist.github.com/fquffio/09360e9b65781f01ee47cbe78487a5de)

**Comment by stefanorosanelli** [comment]
I'd put docker compose template in `bedita/bedita` simply because it's the main repo
