### ISSUE TITLE
Profiling tools

### ISSUE THREAD

**Issue by stefanorosanelli** [bedita/bedita#1316]
Try out profiling tools like https://tideways.io 
and related GUI https://github.com/perftools/xhgui

Are code changes needed?

Write wiki page with instructions usage

**Comment by didoda** [comment]
Installing and configuring XHGui + Mongo + Tideways, no code changes are needed in BEdita4.
Vhost example (profiling enabled through `php_admin_value auto_prepend_file`):
```
<VirtualHost *:80>
	ServerName be4.com
	DocumentRoot /var/www/be4.com/webroot
	php_admin_value auto_prepend_file "/var/www/xhgui/external/header.php"
	<Directory /var/www/be4.com/webroot>
		Options Indexes FollowSymLinks MultiViews
		AllowOverride All
		Order allow,deny
		Allow from all
		Header set Access-Control-Allow-Origin "*"
		Header set Access-Control-Allow-Methods "GET,POST,PATCH,OPTIONS"
		Header set Access-Control-Allow-Headers "origin, x-requested-with, authorization, content-type"
	</Directory>
</VirtualHost>
```

**Comment by didoda** [comment]
Wiki page: https://github.com/bedita/bedita/wiki/Profiling-with-XHGui-and-Tideways
We can improve it, "trying" the instructions and cutting some extra info...
