### ISSUE TITLE
Core media object types

### ISSUE THREAD

**Issue by stefanorosanelli** [bedita/bedita#1317]
Implement core media object types like images, videos, audio and files.

Is `media` an abstract base type like `objects`?

**Comment by stefanorosanelli** [comment]
Seems to be obsoleted by #908 -> `media` is an abstract type and `images`, `videos` concrete inherited types

Is there something to do here or can we just close? @fquffio @batopa

**Comment by fquffio** [comment]
At the present stage only "images" is present… Maybe we should add the missing ones.

Also, but it's probably not something strictly related to this issue, we should add a validation to which streams can be associated to a media according to its actual type — e.g., `application/zip` should not be allowed for images.

**Comment by stefanorosanelli** [comment]
Indeed, some core media types are missing: we may just implement here very simple versions of `videos`, `audio` and `files`
 
Stream and mime type validation can be done afterwards I guess
