### ISSUE TITLE
Docker image build failure

### ISSUE THREAD

**Issue by stefanorosanelli** [bedita/bedita#1341]
After the introduction of `"league/json-guard"` in #1339 a new php extension (`bcmath`) is required and  local image creation

`docker build -t bedita/bedita:4-cactus .`

fails with error

`Your requirements could not be resolved to an installable set of packages.`

Probably because https://hub.docker.com/r/chialab/php/ is missing `bcmath` extension

**Comment by fquffio** [comment]
See chialab/docker-php#15

We should solve this issue in the base image.

**Comment by fquffio** [comment]
The referenced issue has been closed. Trying to build the image now works, but it is required to download the latest base image available using `docker pull chialab/php:7.1-apache`, then `docker build -t bedita/bedita:4-cactus .`

@stefanorosanelli Can you confirm it is working now for you as well? If so, shall we close this issue?

**Comment by stefanorosanelli** [comment]
yes, it's working now
closing
