### ISSUE TITLE
Properties list of an object type

### ISSUE THREAD

**Issue by stefanorosanelli** [bedita/bedita#1353]
[This is needed in `bedita/graphql` but it will probably useful in #1345 and in modeling API]

Get a list of properties with their types of an object type.
Structure similar to `/model/properties` or even better like:
 ```php
'description' => [
     'type' => 'string',
     'required' => false,
    ....
]
```
This list should be cached somehow.

**Comment by stefanorosanelli** [comment]
Much of the work has been done in #1363 
Currently you may use a cached version of properties with something like:
```php
        $properties = TableRegistry::get('Properties')->find('objectType', [$name])
            ->cache(sprintf('id_%s_props', $id), '_bedita_object_types_')
            ->toArray();
``` 
where `$name` is the object type name and `$id` its id

Another possibility will be the use of virtual property `ObjectType::properties` that will also provide a cached list of properties.

@batopa @fquffio can we close this?

**Comment by batopa** [comment]
Ok, closing
