### ISSUE TITLE
`/model/schema` endpoint - JSON SCHEMA

### ISSUE THREAD

**Issue by stefanorosanelli** [bedita/bedita#1384]
Implement a `read-only` endpoint
```
GET /model/schema/{type}
```
Where `{type}` can be:
- an object type, abstract or concrete
- a core resource like `roles`, `applications`, `async_jobs`....

No POST,PATCH,DELETE or GET lists/index are available

Request/response structure proposal:

```http
GET /model/schema/objects
Accept: application/json
```
```http
Content-Type: application/json
{
    "$id": "https://api.example.org/model/schema/objects#",
    "$schema": "http://json-schema.org/draft-06/schema#",
    "type": "object",
    "properties": {
        "uname": {
            "type": "string"
        },
        ...
    },
    "required": ["uname", ...]
}
```

Where response is not `JSON API` but a `JSON-SCHEMA` v6 representation of the type properties

Can a `"version"` - like a hash built from schema - be displayed in order to compare and sync schemas?

**Comment by fquffio** [comment]
The structure you proposed would make things slightly more difficult for a client that needs to validate a JSON against the schema. I would rather serve a plain JSON Schema, without the overhead of a JSON API response structure. Thus:

```http
GET /model/schema/objects
Accept: application/json

Content-Type: application/json

{
    "$id": "https://api.example.org/model/schema/objects#",
    "$schema": "http://json-schema.org/draft-06/schema#",
    "type": "object",
    "properties": {
        "uname": {
            "type": "string"
        },
        ...
    },
    "required": ["uname", ...]
}
```

Also, I'd suggest to use Draft 6 for JSON Schema specifications, and it would be easier to start with object types only — i.e. implement core resources in a second step.

**Comment by fquffio** [comment]
Doing so, a client would be able to validate a JSON against the schema by simply passing `https://api.example.org/model/schema/objects` to the validator.

Another question: how should we differentiate between properties in `attributes` and in `meta`? Should `meta` properties be omitted? And `id`, `type` and `links`? I'd like to hear an opinion from the team that is working on the client SDK as well.

**Comment by stefanorosanelli** [comment]
Ok, main description updated

**Comment by stefanorosanelli** [comment]
- we need both `attributes` and `meta` I think, but some info to identify a property as `attribute` or `meta` is necessary
- `id` and `type` may be omitted
- don't know about `links` in general but some info on object relations could (or should) be provided

**Comment by stefanorosanelli** [comment]
agreed: we should hear opinions from @bedita/managers
