### ISSUE TITLE
Error saving user with duplicated `email`

### ISSUE THREAD

**Issue by stefanorosanelli** [bedita/bedita#1422]
Creating or modifying `users` with a duplicated `email` result in a `500` `Save failed` error instead of a `400`

Example request `POST {apiUrl}/users` with body:
```json
{
    "data": {
        "type": "users",
        "attributes": {
			"username":"gustavo",
			"email":"{existing-email}"
		}
        }
}
```
Error comes from `Cake\ORM\Table::_processSave()` where
```php
        if ($options['checkRules'] && !$this->checkRules($entity, $mode, $options)) {
            return false;
        }
```

returns false in CTI as `Profiles` is the current table,
Same request on `/profiles` will return
```json
{
    "error": {
        "status": "400",
        "title": "Invalid data",
        "detail": "[email._isUnique]: This value is already in use "
    }
}
```

**Comment by batopa** [comment]
I have identified the issue. 

It is a general issue in CTI. When saving parent entity we have some errors we should pass the errors to the last descendant entity but we don't.
