### ISSUE TITLE
GET `files` fails with 405

### ISSUE THREAD

**Issue by edoardocavazza** [bedita/bedita#1430]
### Expected behavior

BEdita should provide a list of objects with `object_type: files` through the endpoint `{host}/files`.

### Actual behavior

The `OPTIONS` network request fails with status 405.

### Steps to reproduce the behavior

1. Authenticate
2. Fetch the resource `{host}/files`

**Comment by batopa** [comment]
I think there is a conflict with webroot/files folder. Could you check if renaming It solves the issue?
