### ISSUE TITLE
Folder API write operations

### ISSUE THREAD

**Issue by stefanorosanelli** [bedita/bedita#1431]
After  #1402 and #1408 some API operations are still missing:

 * place an object inside a folder, or more folders (?)
 * remove an object from a folder
 * move an object from a folder to another

**Comment by batopa** [comment]
In addition to writing operations also

```http
GET /folders/:id/parent
```
doesn't work responding with `404`

```json
{
    "error": {
        "status": "404",
        "title": "Relationship \"parent\" does not exist"
    }
}
```

Moreover

```http
GET /folders/:id/parents
```
should return `404 Not found` but it returns `200` with an array of one parent.
