### ISSUE TITLE
JSON Schema params validation

### ISSUE THREAD

**Issue by stefanorosanelli** [bedita/bedita#1507]
Similar to #1336 - add validation to relation properties

**Comment by batopa** [comment]
It seems already implemented... to verify

**Comment by batopa** [comment]
The validation happens for example using `\BEdita\API\Model\Action\UpdateAssociatedAction` creating entity at row 120

```php
$targetEntities[$id]->_joinData = $association->junction()->newEntity($meta);

$errors = $targetEntities[$id]->_joinData->getErrors();
if (!empty($errors)) {
    throw new BadRequestException([
        'title' => __d('bedita', 'Invalid data'),
        'detail' => $errors,
    ]);
}
```

**Comment by fquffio** [comment]
In commit ~~a66b44a~~ 0801f71 I have added an integration test to ensure `POST` and `PATCH` fail when invalid relation params are given. The test passes without any change to the sources.

Can you provide the schema used for the validation? Maybe the schema you're using is too permissive.

**Comment by batopa** [comment]
I meant that validation on params already worked ;)
Closing the issue.
