### ISSUE TITLE
API POST - Relations: skip "isObjectReachable" with specified relations

### ISSUE THREAD

**Issue by didoda** [bedita/bedita#1510]
### Use case

```
POST /objects/<id>
{
  "id": <id>,
  "title": "my object",
  "object_type": "document",
  "relations": {
    "my_relation": [
      {
        "related_id": <related_id>
      }
    ]
  }
}
```

### Expected behavior
Save object with related data, no matter if related object is not reachable, for some relations.
(Tip: define a whitelist of relations in config, then use it to skip check in `bedita/bedita-app/controllers/components/ApiValidatorComponent:checkRelations / isObjectReachable`)

### Actual behavior
Post fails with `400 Invalid Relation: <related_id> is unreachable`

**Comment by batopa** [comment]
For the whitelist I suggest to place it in [configuration](https://docs.bedita.net/en/v3.8.0/configuration.html), for example in `api.validation.reachableRelations` or similar.

Maybe to have an attribute in `ApiValidator::$reachableRelations` populated with the conf if present seems a good idea to me.

**Comment by didoda** [comment]
issue is already resolved
