### ISSUE TITLE
“View” modal window in versions’ history doesn’t scroll

### ISSUE THREAD

**Issue by GitGianluc** [bedita/bedita#1517]
When opening a “view” window under the versions’ history tab of a document, the modal doesn’t scroll. If the text length exceeds the “natural” height of the window, user is not able to check/uncheck the box(es) requested to restore the desired version of the document.

### Environment information

* bEdita version: 3.8.0
* browser: Mozilla Firefox Quantum 61.0.1

**Comment by batopa** [comment]
obsolete
