### ISSUE TITLE
Updating child position still has some issue

### ISSUE THREAD

**Issue by vallo87** [bedita/bedita#1531]
### Expected behavior

changing all children's position at once should work

### Actual behavior

the change it's not applied to all child (maybe none) but no error is thrown

### Steps to reproduce the behavior

1. go into a folder view
2. add some children to it if none is attached
3. try to change all children's position at once

### Environment information

be4-web@issue/155-move-children-object
bedita4@master

**Comment by vallo87** [comment]
I provide an example here:
the call to {{be4Url}}/folders/53/relationships/children
with the body: 
```
{
    "data": [
        {
            "id":"5",
            "type":"documents",
            "meta": {
                "relation": {
                    "position": "1"
                }
            }
        },
        {
            "id":"2",
            "type":"documents",
            "meta": {
                "relation": {
                    "position": "2"
                }
            }
        }
    ]
}
```

should put the doc named test in first position, but it doesn't do anything.

**Comment by vallo87** [comment]
api method need to reorder body with this priority 
positions:
null   (could be a new related object)
null    
1   
2    
3   
-3    
-1

**Comment by batopa** [comment]
After some headache I realized that the correct order is
```
null
3
2
1
-1
-3
```
