### ISSUE TITLE
need to save relation priority without params

### ISSUE THREAD

**Issue by vallo87** [bedita/bedita#1532]
When i save/update a relation priority i get a validation error on the property params of relation->meta, it cannot be either empty or null and it needs to be present.

this behavior prevent to save only the updated priority of the relation. 

endpoint: {{be4Url}}/documents/2/relationships/modern_voter
body: 
```
{
  "data": {
    "id":"48",
    "type":"profiles",
    "meta":{
       "relation":{
         "priority":1
       }
     }
  }
}

```

**Comment by fquffio** [comment]
This hasn't been resolved yet!
