### ISSUE TITLE
[API] filter query string doesn't accept 1 or 2 letters 

### ISSUE THREAD

**Issue by vallo87** [bedita/bedita#1542]
when filter q=[word] has a word of 1 or 2 characters the api call ends up in failure

Error:
```
    "error": {
        "status": "400",
        "title": "Not Found",
        "detail": "query filter requires a non-empty query string"
    }
```

**Comment by fquffio** [comment]
The behavior can be configured to accept words up to a minimum length (by default, 3 characters). For custom models, this can be changed.

However, the error message should be improved… and why is it `Not Found`? 🤔
