### ISSUE TITLE
Default `status` for new objects

### ISSUE THREAD

**Issue by stefanorosanelli** [bedita/bedita#1552]
Currently all new objects are created with status `draft` if no status is set.
On some object types different defaults should be available.

We could extend this feature to other object properties.

Should this be defined via configuration or as default model properties in object types?
Should this feature be application dependent?

**Comment by didoda** [comment]
Will we really need custom defaults by object type (anytime soon)? maybe `YAGNI`.
I suggest that we start with a basic solution in configuration (`config/app.php`), i.e.:
```
'Object' => [
    'defaults' => [
        'status' => 'on',
    ],
],
```
Then we could think about a "default model properties in object types" solution, when it will be required (in a separate, future, issue).

@batopa , @fquffio , what do you think about it?

**Comment by stefanorosanelli** [comment]
In BE3 we had only a `defaultStatus` configuration for every object type.
If we want to use a configuration for that I'd use something like:

```php
'DefaultValues' => [
   'images' => [
      'status' => 'on',
   ],
]
```

Probably listing only concrete types for simplicity.
Don't know if we should create a link to applications.
