### ISSUE TITLE
[question] thumb of image with no media

### ISSUE THREAD

**Issue by vallo87** [bedita/bedita#1565]
What should we do if an image has no media, related to its thumb creation and media/thumb endpoint?

right now media/thumb of a medialess image doesn't show it on the response (for example with the generic image missing picture)

**Comment by fquffio** [comment]
I'd avoid returning a generic missing image placeholder: it's a solution that comes in handy for simple cases, but makes it difficult to detect whether the thumbnail is "real" or just a placeholder in more advanced scenarios, unless an additional flag is present in the response.

It may be better to just leave the responsibility to the SDK/consumer to provide a default value in case no thumbnail is present.

That being said, maybe we can return the `uri` property with `null`.

**Comment by vallo87** [comment]
I actually agree with this view, but for image that have media that are missing it now gives an image missing url, so there's a discrepancy between the 2 cases...
