### ISSUE TITLE
[Question] How to extend BEdita functionalities with custom codes?

### ISSUE THREAD

**Issue by ProFire** [bedita/bedita#1573]
This is probably a noob question. Please don't flame me. I really tried following the CakePHP documentation. I couldn't find an answer in BEdita documentation. I also don't know where else I can ask this question.

I just want to extend BEdita functionality with my own codes without modifying the BEdita plugin.

### Expected behavior

Create a new Controller named ImageOptimiseController.php and add the route as follows:

```
<?php //src/Controller/ImageOptimiseController.php
namespace App\Controller;

use Cake\Controller\Controller;

class ImageOptimiseController extends Controller 
{
    public function renders() {
        return $this->response;
    }
}
```

```
// config/routes.php
Router::scope('/', function ($routes) {

    $routes->connect(
        "/ImageOptimise/*",
        ["controller" => "ImageOptimise"]
    );

//More Routes
}
```

I expect that I can browse to http://localhost/PROJECTPATH/ImageOptimise/ and output view file not found or something like that.

### Actual behavior

I got this error instead:
Controller class ImageOptimise could not be found.

### Environment information

* Bedita: 4.0.0RC

**Comment by didoda** [comment]
hi @ProFire , I already replyed you in https://groups.google.com/forum/#!msg/bedita/4tA7boPRgIg/00U2AcghAwAJ

I realise that you are using BEdita v.4, so my first reply was not useful for your purpose.

You should be more specific on what exactly you are trying to develop, providing some more code to investigate the problem (specify also which php version you are using).

Maybe you want to develop your own plugin, in `plugins` directory.
In that case, in `config/app.php`:

```
'Plugins' => [
        'MyPlugin/ImageOptimise' => ['autoload' => true, 'bootstrap' => true, 'routes' => true],
],
```

And in `plugins/ImageOptimise` you put your stuff (controller and route, as cakephp app) with the proper namespace (`MyPlugin/ImageOptimize`, i.e.)

Some documentation on plugins configuration: https://docs.bedita.net/en/latest/configuration.html#plugins

**Comment by ProFire** [comment]
I'm using PHP 7.2.11.

I'm trying to route all jpg request to CakePHP so that I can resize->optimise->cache->serve image on the fly. Normally, in CakePHP, I would just route them as I would with the code above. (It's incomplete anyway)

Now that I'm in BEdita environment, the behaviour seems different. I'm not sure if I'm doing it correctly.

In my htaccess file, I've successfully routed all jpg extensions to CakePHP.
```
    RewriteCond %{REQUEST_URI} ^/(.*?)\.jpg$
    RewriteRule ^(.*)$ ../api.php/$0 [L]
```
I've renamed index.php to api.php in webroot, by the way.

P.S. Sorry about the double post. I thought the google group was inactive after I posted, so I posted here.

**Comment by didoda** [comment]
I guess that your routing system couldn't sort out the namespace.
I would try something like the following, in `config/routes.php`:

```
<?php
use Cake\Routing\RouteBuilder;
use Cake\Routing\Router;
Router::plugin(
    'MyPlugin/ImageOptimise',
    [
        'path' => '/',
    ],
    function (RouteBuilder $routes) {
        $routes->connect(
            '/ImageOptimise',
            ['controller' => 'ImageOptimise', 'action' => 'index']
        );
    }
);
```
For details about `Router::plugin`, look at cakephp doc (https://book.cakephp.org/3.0/en/development/routing.html#plugin-routing)

Note: in this example the namespace that you should put in the controller would be `MyPlugin\ImageOptimize\Controller`

**Comment by didoda** [comment]
Another suggestion: take a look on the graphql plugin for bedita, to have tips on plugin developing for bedita (https://github.com/bedita/graphql)

**Comment by fquffio** [comment]
Hi @ProFire ! Thanks for your interest in this project.

I'm afraid that your controller lives in the wrong namespace. As you can see from [`package.json`](https://github.com/bedita/bedita/blob/4-cactus/composer.json#L38) the `src/` folder is the PSR-4 root for namespace `BEdita\App`. Therefore, the Fully-Qualified Class Name (FQCN) for your controller should probably be `BEdita\App\Controller\ImageOptimiseController`.

However, even though your approach is perfectly fine, most of the times we use a plugin-based approach. You might consider creating your `ImageOptimise` plugin and use that instead. 😄

**Comment by ProFire** [comment]
> 
> 
> Hi @ProFire ! Thanks for your interest in this project.
> 
> I'm afraid that your controller lives in the wrong namespace. As you can see from [`package.json`](https://github.com/bedita/bedita/blob/4-cactus/composer.json#L38) the `src/` folder is the PSR-4 root for namespace `BEdita\App`. Therefore, the Fully-Qualified Class Name (FQCN) for your controller should probably be `BEdita\App\Controller\ImageOptimiseController`.
> 
> However, even though your approach is perfectly fine, most of the times we use a plugin-based approach. You might consider creating your `ImageOptimise` plugin and use that instead. 😄

That totally worked. I didn't realised the FQCN can be affected in composer.json. I have just learnt something new.

Probably another noob question. Now that I know there are 2 ways to do this, should I stick with the original src folder or do it in the plugins folder? What are the pros and cons?

**Comment by batopa** [comment]
It depends. The major pros of doing a plugin is the possibility to reuse it in other BEdita instances and/or in generic CakePHP apps.

So if you feel that the code you wrote is easily reusable in other projects go with plugin.

Another advantage is to maintain the BEdita app code cleaned and easily upgradable without having to diff common files as `config/routes.php`, `config/bootstrap.php`.

Anyway you can also proceed with your initial approach and move it in a plugin later if you need it.

**Comment by fquffio** [comment]
@ProFire Just a few words more on the namespace: the PSR-4 root is set in `composer.json` and this is a standard for all modern PHP projects.

Furthermore, CakePHP wants you to set the [`config/app.php`](https://github.com/bedita/bedita/blob/4-cactus/config/app.default.php#L40) as it needs to know that for some operations. So, if you ever want to change that, you should update the namespace in a number of places. 😞

**Comment by ProFire** [comment]
Thanks for sharing this information. I've learnt and will try out the 2 different ways, while identifying which way suits my project most.
