### ISSUE TITLE
[API] Relation with empty params can't be saved

### ISSUE THREAD

**Issue by vallo87** [bedita/bedita#1582]
From an object view if I try to save the object after I added a related object (any relation)
i get the following error message:
```
Error
[400] Invalid data

{
    "status": "400",
    "title": "Invalid data",
    "detail": "[params._required]: This field is required",
    "code": 400
}
```

it seams that the required field ghost has made his return :)

**Comment by stefanorosanelli** [comment]
Problem was solved in #1572 (issue #1532) but now it happens again when `params` are not set but are defined in a relation...
