### ISSUE TITLE
Objects.publisher field is set to empty string when an object is saved from bedita-app

### ISSUE THREAD

**Issue by mikelina** [bedita/bedita#1621]
After #1025 in publisher field we should have NULL value, defaultPublisher or string value inserted by user in frontend.

When an object is created by API and updated from bedita-app or when from bedita-app is cleared the value of field, in database is saved empty string and not null value.

When we order object by publisher to give priority on editorial content, objects with publisher = "" and publisher = null is ordered separately.

**Comment by batopa** [comment]
closed by #1622
