### ISSUE TITLE
Parent tree cache invalidation on model save [first time "destination" is set]

### ISSUE THREAD

**Issue by didoda** [bedita/bedita#1676]
### Expected behavior

Saving an object from module view invalidates properly parents caches

### Actual behavior

Saving an object from module view sometimes doesn't invalidate properly parents caches on first save, an extra save is needed to achieve the task.

### Steps to reproduce the behavior

1. Edit a document (not in the tree) [from `http://<bedita-local-vhost>/documents/view/<document-id-or-nickname>`), set a destination and save it  [first time "destination" is set]
2. Verify its parent cache: not invalidated (not expected)
3. Save the same document again, without changing data [from `http://<bedita-local-vhost>/documents/view/<document-id-or-nickname>`]
4. Verify its parent cache: invalidate (expected)

=> 2 saves to invalidate parents cache properly

**Comment by batopa** [comment]
obsolete
