### ISSUE TITLE
meta.path on GET /folders/:id

### ISSUE THREAD

**Issue by didoda** [bedita/bedita#1732]
### Expected behavior

meta.path contains the path for folder

### Actual behavior

meta.path contains a superlong string

### Steps to reproduce the behavior

https://comunebo-api.bedita.net/folders/724476

**Comment by stefanorosanelli** [comment]
This is caused by some kind of corruption on `trees` table

After `bin/cake tree recover` `meta.path` seems now correct.

**Comment by didoda** [comment]
hard to tell which kind of corruption took place. let's close the issue, for now. if corruption happens again, we reopen it
