### ISSUE TITLE
ui: media files inline in richtext editor (wordpress)

### ISSUE THREAD

**Issue by stefanorosanelli** [bedita/bedita#190]
una cosa che c'e' su wordpress (e altrove): nel richtext editor posso selezionare immagini dai media presenti nell'archivio e metterle *inline* nel testo che sto scrivendo

**Comment by edoardocavazza** [comment]
@stefanorosanelli @qwerg 

Can we close this issue and open a new one for new features?

**Comment by stefanorosanelli** [comment]
agreed, please close this issue and open new

**Comment by edoardocavazza** [comment]
New issue here #649
