### ISSUE TITLE
Upgrade BEdita 5 dependencies

### ISSUE THREAD

**Issue by stefanorosanelli** [bedita/bedita#1905]
Candidates:

* `symfony/yaml` 5.4.3 - https://github.com/symfony/yaml/tree/v5.4.3
* `league/flysystem` 2.4.5 - https://github.com/thephpleague/flysystem/tree/2.4.5 
* `league/glide` 2.2.2 - https://github.com/thephpleague/glide/tree/2.2.2 
* `firebase/php-jwt` 6.1.2 - https://github.com/firebase/php-jwt/tree/v6.1.2

Maybe it is time to drop `fzaninotto/faker`, see https://marmelab.com/blog/2020/10/21/sunsetting-faker.html

**Comment by batopa** [comment]
We need to pay attention with `firebase/php-jwt`.

From the CakePHP Authentication plugin:

> You need to add the lib [firebase/php-jwt](https://github.com/firebase/php-jwt) ^5.5 to your app to use the JwtAuthenticator (v6.0 is not currently supported).
