### ISSUE TITLE
software update system

### ISSUE THREAD

**Issue by stefanorosanelli** [bedita/bedita#217]
progettare un sistema di software update automatico, diviso in queste parti:
- notifica nuova versione presente _compatibile_ -- aggiungere DIV in dashboard
- script di aggiornamento (scarica versione, scompatta, aggiorna dati-script..) -- da lanciare via shell o da interfaccia admin
- meccanismo di rollback in caso di errori o problemi riscontrati dall'utente

Lo stesso meccanismo, o uno simile, lo potremmo usare per deploy dei frontend.

**Comment by fquffio** [comment]
Should have been solved in #913. Still valid?

**Comment by stefanorosanelli** [comment]
Database part solved with migrations in #913 
On deploy/update strategies in general a lot has changed in last years. We have to rethink on how to do it.

Closing as obsolete
