### ISSUE TITLE
ui: quick edit in object list

### ISSUE THREAD

**Issue by stefanorosanelli** [bedita/bedita#244]
quick edit (like wordpress): activate some operations on lists via ajax:
- change title, status
- change categories, tags
- ...

**Comment by edoardocavazza** [comment]
Right now, the click on a row of the object list triggers the opening of the object view page. How should the quick edit activate? @qwerg @stefanorosanelli

**Comment by stefanorosanelli** [comment]
moved to BE4 - will see how to implement this in the new UI

**Comment by stefanorosanelli** [comment]
No more relevant here
Could be done in bedita/web - we'll see
