### ISSUE TITLE
Tab for alias

### ISSUE THREAD

**Issue by batopa** [bedita/bedita#306]
* **View:** Add a tab (element) to handle aliases. The tab has to have a text form for the alias and a select for the language (it can be null). Add and remove buttons in every row to add or remove an alias row. Build the form name items as:

```html
data[Alias][0][nickname_alias]
data[Alias][0][lang]

data[Alias][0][nickname_alias]
data[Alias][0][lang]
```

 * **Model:** ```Alias::beforeSave()``` has to transform string in friendly url name as a nickname. A check on nicknames and other aliases is required.

Remember that if beforeSave method return true the save method proceeds while return false stop the save

**Comment by stefanorosanelli** [comment]
In BE4 we don't know if we'll still be using **aliases**
closing for now
