### ISSUE TITLE
Adding options in BEdita XML import

### ISSUE THREAD

**Issue by qwerg** [bedita/bedita#415]
For a specific vendor importer, we created a series of options on how to manage nicknames conflicts during the import process. It would be useful to promote this feature to BEdita core importer, and expose it in the UI as radio buttons (area/section module).

Options on nickname conflict:

"override" => "remove already present object (default?)",
"new" => "create a new object with new nickname",
"ignore" => "ignore the object, don't import it",
"update" => "merge relations and update object data",
"merge" => "merge relations only (and don't import the object itself)"

**Comment by stefanorosanelli** [comment]
moved to #640
