### ISSUE TITLE
Create a system to build BEDITA javascript object

### ISSUE THREAD

**Issue by batopa** [bedita/bedita#435]
We need to have some properties exposed to javascript.
We already have a BEDITA javascript object with some vars built in ```views/elements/json_meta_config.tpl``` but it would be better have some simple way  to add dynamically var to that object in business logic.

Finally there is to evaluate if meta tag built in ```views/elements/json_meta_config.tpl``` are necessary.

**Comment by stefanorosanelli** [comment]
This will depend on UI/Javascript design in BE4
@batopa @edoardocavazza may we close it as obsolete?

**Comment by batopa** [comment]
Yep, close it
Il 15/dic/2015 06:31 PM, "Stefano Rosanelli" notifications@github.com ha
scritto:
