### ISSUE TITLE
Comments module: error saving comment 

### ISSUE THREAD

**Issue by qwerg** [bedita/bedita#468]
It's really necessary having mandatory email and url in backend?

```
Error saving comment; [email] => email not valid; [url] => URL not valid
```

**Comment by stefanorosanelli** [comment]
No, it may not be necessary, we could set the user's email
But normally on frontends yuo may expect to have these fields not empty
Is it still necessary?

**Comment by stefanorosanelli** [comment]
Obsolete
Also: we don't like comments :smiling_imp:
