### ISSUE TITLE
View galleries attached media when a gallery is an attach itself

### ISSUE THREAD

**Issue by qwerg** [bedita/bedita#474]
In frontend view we need to display not only the attach-gallery data, but the attach-gallery-attach-media data too. For example to display files. Example:
document > attach > media > file
document > attach > gallery > attach > media > file(s)

**Comment by stefanorosanelli** [comment]
@batopa @qwerg can we close it?

**Comment by stefanorosanelli** [comment]
done with secondaries relations in frontends
