### ISSUE TITLE
Tag filter in objects list view

### ISSUE THREAD

**Issue by qwerg** [bedita/bedita#480]
In #432 we missed to add the tag filter in the filter tab options (lists and modal)
At the moment the only way to view objects by tag is in the tag module.

**Comment by qwerg** [comment]
Add a tag select in showObjects modal filters. @batopa can you give a look (and maybe merge in 3-corylus?)

**Comment by batopa** [comment]
Maybe in the future we could load tags in ajax, I think in case of many tags to load.
Anyway the issue it's ok for me.
Closing
