### ISSUE TITLE
publications: search sections/publications ?

### ISSUE THREAD

**Issue by stefanorosanelli** [bedita/bedita#505]
It is not possibile to search for publications or sections in publications module

You can only serch for contents inside a specific section/publication.

see also #504

**Comment by qwerg** [comment]
Yes, but there's not an index page in publications.
We can 
a) create an index and add a search results page in this module, or 
b) extend the actual basic micro search in home page, creating a more advanced cross-modules full search page and results. A search in publications will redirect to this page.

**Comment by stefanorosanelli** [comment]
Prefer solution *a)*
We could use same patterns of oher modules for object lists and apply same filter
In this case _index_ could not be the default entry page in module

**Comment by qwerg** [comment]
Agree with (a). 
Even so I think an advanced cross object search (b) it's also necessary.

**Comment by stefanorosanelli** [comment]
seems ok now - closing
