### ISSUE TITLE
Media formula enhancement

### ISSUE THREAD

**Issue by qwerg** [bedita/bedita#514]
We need to create a new BEdita object, named "formula"(see #347 )
with specific fields:
- MathML
- SVG
- LaTeX

the user should have the ability to convert mathml to LaTeX and vice versa.
And if possibile also mathml to SVG.
See also
https://github.com/mathjax/MathJax-node

**Comment by fquffio** [comment]
Hence "Formulas" is about to become a standalone BE module, I'd mark this issue as "Obsolete" and close it. @qwerg, do you agree?

**Comment by qwerg** [comment]
yes, but add a reference to the new module repo an issues.
