### ISSUE TITLE
BEdita and Javascript application

### ISSUE THREAD

**Issue by edoardocavazza** [bedita/bedita#537]
We need to implement a better flow for developing javascript applications (web, cordova, etc...) with BEdita as backend and data provider. This is a list of proposals that I have thought:

Todo:

- [ ] establish the structure of the JSON object that BEdita returns
- [x] use ajax layout for all ajax calls (also for errors)

Deprecated:

- <del>promote the method "jsonResponse" that we have used in some projects to the AppController</del>

- <del>use the jsonResponse method for all "json" or "jsonp" calls</del>

Other things with minor priority:
- [ ] javascript application boilerplate
- [ ] oauth authentication for BEdita

Feel free to add comments, more purposes and deletions.
@batopa @stefanorosanelli @qwerg @xho @didoda

**Comment by fquffio** [comment]
Commit 58b33f0 has a reference to this issue, but it should have referenced #573 instead. I'm sorry.

**Comment by stefanorosanelli** [comment]
@edoardocavazza can we close it? seems obsoleted by new API
