### ISSUE TITLE
Installing BEdita with already populated DB prompts to overwrite user with ID=1

### ISSUE THREAD

**Issue by fquffio** [bedita/bedita#540]
When installing BEdita using a pre-populated database, after entering DB connection settings, the user will be prompted to create an admin user (even if it already exists).

If the user enters an already-existing username, he will get an error message, but if he enters an available username, the setup script will overwrite the user with ID=1 (created during a previous installation).

**Comment by batopa** [comment]
Now if system user was already present the installer refers to a generic user _bedita_ also if the username is different:

> a system user _bedita_ with password _bedita_ has already been set up.

We could just write the real system user username. No password information.

**Comment by fquffio** [comment]
@batopa Now the message shows correctly the first User's username. Informations about its password are still shown in case the password is still `bedita`, because otherwise we would never show what is the password of the newly created administrator in a clean installation. I think it might also serve as a basic security warning.

**Comment by batopa** [comment]
@fquffio ok now it's ok. I agree about password. Closing
