### ISSUE TITLE
Filter "count_relations" groups all rows in result

### ISSUE THREAD

**Issue by fquffio** [bedita/bedita#541]
Using `count_relations` as module filter groups all rows in result, due to `SUM(num_of_relations_XXYYZZ)` in `SELECT` query, when rows have already been grouped by `id` by a subquery, causing also `LIMIT` to return 0 rows if a positive offset is specified.

TODO:
- [x] fix query (/bedita-app/models/behaviors/build_filter.php:736).

**Comment by fquffio** [comment]
The same issue happens with "count_annotation" filter.

**Comment by batopa** [comment]
It seems that you have only commit on master branch. Could you cherry-pick it on 3-corylus?

**Comment by batopa** [comment]
@fquffio sorry my mistake. I have looked at commit detail on github and it shows that commit on branch master. *The patch is also rightly landed in 3-corylus*.
Closing
