### ISSUE TITLE
Implement Frontend RESTful API version 1

### ISSUE THREAD

**Issue by batopa** [bedita/bedita#558]
Following format defined in https://github.com/bedita/bedita-genie build the first version of frontend API REST.

- [x] Define a basic set of API endpoints
- [x] Implement backend base controller that extends FrontendController
- [x] ```ApiController``` in frontend apps and routing rules
- [ ] ~~Unit tests~~ todo in other issue
- [x] Authentication system

**Comment by edoardocavazza** [comment]
Introduced a first implementation of the API auth system using session tokens.
Maybe we should take a look at http://jwt.io/ for JSON web tokens

**Comment by edoardocavazza** [comment]
Set up the frontend:
https://github.com/bedita/bedita/wiki/Setup-a-frontend-for-REST-API-response

**Comment by batopa** [comment]
Defined as super basic endpoints
- /auth
- /objects
- /poster
- /me

Moreover every BEdita objects can be reached with its pluralized object type name
- /documents
- /events
- /galleries
- etc...

For now doc [here](https://github.com/bedita/bedita/wiki/REST-API-endpoints-%28Frontend-App%29)
