### ISSUE TITLE
default JSON import/export logic

### ISSUE THREAD

**Issue by stefanorosanelli** [bedita/bedita#561]
Implement first version of basic BEdit objects import/export
See spec in #176 and https://github.com/bedita/bedita/wiki/Default-serialized-format-for-BEdita-objects

Todo: create Model classes and shell script

**Comment by stefanorosanelli** [comment]
Did some export/import tests:

 * there's a naming issue - class name should be **BeFormat** if file name is **be_format.php** (otherwise cake may try to load a new **BEFormat** class not from be_format.php

 * customproperties import: validation error if a value is = 0 - using php _empty_ function it may result not set -- use _isset_ instead

 * categories: in validation we expect a 'name' attribute in categories array, but there isn't

 * general on validation errors: it would be really useful to have all errors listed not just stop after the first

**Comment by stefanorosanelli** [comment]
Naming proposal:
 * model - instead of BEFormat - **DataTransfer** (**data_transfer.php**)
 * shell - **DataShell** instead of **FormatShell**

@batopa and @didoda ??

**Comment by didoda** [comment]
New naming is fine, for me. I still haven't released epub3 import/export model and shell script, I have been working on lately. Proposals for naming? I used EPUB3Format and EPUB3Shell. Maybe I could name them EPUB3Transfer (epub3_transfer.php) and EPUB3Shell

**Comment by didoda** [comment]
```
$ ./cake.sh data help

---------------------------------------------------------------
format script shell usage:

./cake.sh data import -f <filename> [-m <sourceMediaRoot>] [-v]
./cake.sh data export [-id <objectId>] [-f <filename>] [-m <destMediaRoot>] [-t <returnType> JSON|FILE|ARRAY] [-v]
```

**Comment by stefanorosanelli** [comment]
basic functionality works - closing
there are minor problems/enhancements to be handled in new issues
