### ISSUE TITLE
Add validation rule on userid field

### ISSUE THREAD

**Issue by batopa** [bedita/bedita#567]
We need a validation rule on userid field. The validation should be any string composed by chars permitted by email specification (not necessary a valid email)

https://en.wikipedia.org/wiki/Email_address#Local_part

**Comment by fquffio** [comment]
Added two validation rules on `userid` field (`Users` model):
- a minimum length of two characters is now required
- username cannot contain any special character. In other words, only printable characters are allowed (no control characters), except `<>'"\|&`
