### ISSUE TITLE
dashboard: don't display last notes and comments related to objects hidden to user 

### ISSUE THREAD

**Issue by stefanorosanelli** [bedita/bedita#568]
notes and comments of objects handled by modules that are not available to user should not be visible in dashboard - part of #343

**Comment by fquffio** [comment]
@stefanorosanelli Did a bit of testing on 3-corylus branch. It looks like this works already this way. :confused:

Admin view:
![admin](https://cloud.githubusercontent.com/assets/7108146/7022158/307c811c-dd29-11e4-87af-d9308a4426ea.png)

User view (unauthorized to access Addressbook module):
![user](https://cloud.githubusercontent.com/assets/7108146/7022163/38a1bae2-dd29-11e4-958c-11581d31aa7c.png)

What am I doing wrong? :sweat:

**Comment by stefanorosanelli** [comment]
You are right - solution was committed in #303 
Closing
