### ISSUE TITLE
Redesign exceptions and errors handling

### ISSUE THREAD

**Issue by batopa** [bedita/bedita#570]
In order to make more flexible the handling of exceptions and error we need to better design the way BEdita handles exceptions and errors.

It is also useful for #558 when errors on json requests have to responde as json.

**Comment by batopa** [comment]
### Added new http exceptions

In `bedita-app/bedita_exceptions.php` I have mapped common http error status codes with exceptions as `BeditaBadRequestException`, `BeditaNotFoundException`, etc..

### Introduced new Exception handler

While previously there was a `try {} catch() {}` block in `index.php` now in `bedita-app/config/bootstrap.php` we take advantage of `set_exception_handler()` PHP function.
For shell scripts the exception handler is defined in `BeditaBaseShell::__construct()` instead.

### Setup exceptions handler

By default `bedita-app/libs/errors/be_exception_handler.php` is used but it possible to write a custom handler and setup it from configuration

```php
Configure::write('Exception', array(
  'handler' => array(
      'class' => 'MyExceptionHandler',
      'method' => 'myHandleExceptions'
  )
));
```
The custom class should be placed in `bedita-app/libs/errors` or `app/libs/errors` in frontend app.
The custom method has to accept an `Exception` as argument and has to be defined as `public static`.

The default exception handler instantiates an `AppError` that take care of prepare errors data for the client and try to render a view.

### The ResponseHandlerComponent

This component automatically takes care of render the right type of view if a **json** or **xml** are requested. It says to controller to use `JsonView` or `XmlView`.
Those views check if a *special key* named `_serialize` is in `viewVars` and in case serialize all `viewVars` found in `_serialize` to present the payload to client.

For example a json request to an action containing

```php
$this->set('section', $this->Section->find('all'));
$this->set('otherData', array(...));
$this->set('_serialize', array('section', 'otherData'));
```

will output the `json_encode()` of `View::viewVars['section']` and `View::viewVars['otherData']`.

Follow this schema the `AppError::setError()` method setup the `App::error` property to be serialized and send the right header to client based on http error code thrown

```php
$this->controller->ResponseHandler->sendStatus($this->error['status']);
$this->controller->set(array(
	'error' => $this->error,
	'_serialize' => array('error')
));
```

**Comment by stefanorosanelli** [comment]
@batopa can you transform your previous comment/description in an article in docs.bedita.com? 
Then we can close this issue

**Comment by batopa** [comment]
Write the documentation on staging site. We'll promote to official docs when the new BEdita version is released
