### ISSUE TITLE
Automatically create Card when creating a new User

### ISSUE THREAD

**Issue by fquffio** [bedita/bedita#573]
When creating a new User, a new Card should automatically be created and associated to that user.

**Comment by fquffio** [comment]
@batopa & @stefanorosanelli, just a couple of questions 4 u:
- what is it supposed to happen if one attempts to create a User with an email address AND/OR full name that is present in an already-existing Card? Should that Card be linked to the new User instead of creating a new one? And what if those very same values are present in more than one Card?
- should Card creation be triggered only on new User creation, or on existing User update as well, as long as that User has no linked Card(s??) yet?

**Comment by batopa** [comment]
1. I think that if one or more Card with the same email address exist, the user should choose what to do through a modal window (new card, use existing card).

2. updating user without card should be create new one or propose to link existing card with same email.

@stefanorosanelli?

**Comment by stefanorosanelli** [comment]
Agree with @batopa, from backend user may choose an existing with same email and/or same real name. 
Also on user update we could verify Card presence and create it if missing.

**Comment by fquffio** [comment]
Now, when creating a new User, or updating an existing one which has no Card associated, on form submission you are prompted to either choose an existing non-associated Card (match performed against email address or full name*) or create a new one.

* Hence full name search performs substring matches, the Card `First Name` would be returned in the following cases: `First Name`, `Name First`, `Mr. Name First`, `First S. Name`, `First Second Name Sr.`, ...

### In frontends ###
This update is fully retrocompatible, and by default behavior it creates a new Card for everyone. This means that on the "average" BEdita frontend, any new User created will also trigger a new Card creation.
**BUT**, hence we have no checks on posted fields consistency, if a field `data[User][_cardToAssoc]` it is somehow passed to the User model containing the ID of an existing Card, that Card will be associated to the (new or updated) User. **Therefore** frontends *should* manually clear up that field in order to avoid potential threats.
We could easily get around this by adding an additional switch in Config, which enables to turn on or off this feature (on = possibility to associate existing Card, off = always new Card creation), and set it to off by default in `frontend.ini.php`. @batopa @stefanorosanelli, I'll be waiting for instructions.

**Comment by batopa** [comment]
After 58b33f0 in frontends when a user is created a card is always created too. ```data[User][_cardToAssoc]``` is irrelevant.

**Comment by fquffio** [comment]
@batopa Yes, it has been introduced intentionally as a security measure. If `data[User][_cardToAssoc]` was taken into account while creating a User from frontend app, a malicious client could have passed that argument with a valid Card ID to link its account to that Card, even if that wasn't supposed to be possible.

**Comment by batopa** [comment]
@fquffio yes I know, it was a comment to also link the commit on this issue :smile: 

A couple of things then we can close it:

* when you create a card always save the objects.title as 'name surname' or 'username' if no users.real_name is fill. Indeed in addressbook list cards we show objects.title.
* if card missing of 'name', 'surname' and 'email' fields, an empty row appears listing similar cards. We could add objects.title and show it if missing 'name' and 'surname'. If it's also empty objects.title *[no title]* should be displayed

**Comment by batopa** [comment]
ok, closing

**Comment by batopa** [comment]
@fquffio I moved `AddressbookController::similarCards()` to `PagesController::similarCards()` to avoid issues when Addressbook module is disabled. In this way the user is always associated to a Card and enabling Addressbook module you find out all cards created.
