### ISSUE TITLE
Permission system refactor?

### ISSUE THREAD

**Issue by fquffio** [bedita/bedita#574]
In order to give a better consistency and a simpler way to decide whether a User has enough permissions to read/write an object, we might consider a refactor of the permission system. I've been asked by @qwerg to write my proposal, but indeed I have two. :smirk:

At this moment, we can set "read" access to an object for a group A, and group B "read + preview 4 others" access to the very same object. The permissions table would look like this.
```
mysql> SELECT permissions.object_id, permissions.flag, groups.name AS group_name FROM permissions INNER JOIN groups ON groups.id = permissions.ugid;
+-----------+------+------------+
| object_id | flag | group_name |
+-----------+------+------------+
|         1 |    2 | A          |
|         1 |    3 | B          |
+-----------+------+------------+
2 rows in set (0,00 sec)
```
What is it supposed to happen? Is the preview available to other users, or is it not? Also: if I belong to a third group C, I **always** need to read permissions set for other groups as well in order to decide whether the object should be visible or not.

The following two proposals aim to make this decision unambiguous and requiring a lighter load on the DB. Sorry for this wall-post in advance, but @batopa and @stefanorosanelli have already got used to things like this.

# First proposal: make "preview" permission a BEObject property #
While leaving the `permissions` table unchanged, we could add a boolean value to the `objects` table in a column called `preview`. By doing this, the "preview" permission would be global on that Object, allowing us to decide if a group with no custom permissions set should be allowed to see that object's previrew or not, without having to loop through other groups' permissions.

#### PROs ####
- lighter query (actually, it requires two distinct queries, but BEObject fetching already happens, so fetching `permission` column shouldn't be a problem).
- simpler to implement, as it requires to update the DB structure, while leaving unchanged DB data.
- as far as I can remember, this proposal was @qwerg's favorite — and well, he is my boss. :sweat_smile:

#### CONs ####
- change in the DB structure.
- very little flexibility.
- "semantically not valid", as the preview permission (which is a permission, indeed) is treated as an object property, and saved outside the `permissions` table, where it is supposed to stay.

# Second proposal: bitwise permissions system #
By doing a little change in `permissions` table structure (`ugid` column should be NULL-able), and a bit more complicated data conversion in that same table (two, well-built queries are enough, though), we could gain a finer control on permissions.
The `ugid = NULL` value would be reserved to a pseudo-group "Everyone", and then for each group the `flag` value would be set to an integer value following these rules:
- first two bits are used to decide whether read access is available or not (`$flag & 3 == 0b00` means "no", `$flags & 3 == 0b01` means "never" – stops inheritance and blocks other groups' permissions –, `0b10` means "preview access", `0b11` means "full-read access"). Therefore to decide, if we don't care for full-read access but we need to check only preview access, we could simply perform `$flag >> 1 & 1`.
- third and fourth bits grant write access in a similar way as before (`$flag >> 2 & 3 == 0b00` stands for "no", `0b01` is "never", `0b11` means "yes", `0b10` is just a bug).

A simple pseudo-code to check permissions in this case would be:
```php
// Default values.
define('PERM_NO', 0);  // 0b00
define('PERM_NEVER', 1);  // 0b01
define('PERM_PARTIAL', 2);  // 0b10
define('PERM_FULL', 3);  // 0b11

function doIHaveReadPermission(array $allThePermissionsIHaveInherited) {
    $perm = 0;
    foreach ($allThePermissionsIHaveInherited as $p) {
        # $p = $p >> 2;  // Comment/uncomment this line to switch between read/write permissions, respectively.
        if ($p & PERM_FULL == PERM_NEVER) {
            return PERM_NO;
        }
        $perm = $perm | ($p & PERM_FULL);
    }
    return $perm;
}

$permission = doIHaveReadPermission([0, 1, 2, 3, 4, 5, 6, 7]);
switch ($perm) {
    case PERM_NO:  // 0b00 = 0
        print 'nope';
    case PERM_PARTIAL:  // 0b10 = 2
        print 'preview';
    case PERM_FULL:  // 0b11 = 3
        print 'yay';
    default:  // Other values never happen.
        print 'H4CK3D!!1!';
        pr($this->data); exit;
}
```

Instead, to set permissions:
```php
$write = PERM_NEVER;  // Write: inhibit.
$read = PERM_PARTIAL;  // Read: only preview access.
$valueToBeSaved = ($write << 2) | $read;  // "Compressed" value to be saved.
doSetPermissions($groupId, $objectId, $valueToBeSaved);  // Or perform "conversion" within this function instead.
```

#### PROs ####
- lightest query and PHP algorithm.
- despite of all, it should be quite simple to implement.
- great flexibility.
- very little change in DB structure.
- "semantically valid", as all permissions are set within `permissions` table, and read from there.

#### CONs ####
- one-time DB data conversion.
- `permissions` table would be less human-readable.
- one more pseudo-group, that would be used just in this context.

**Comment by fquffio** [comment]
The second proposal might have also the benefit of making things easier when it is needed to give access permission to a publication to two or more different groups, but restricting access to some resources (like videos, for example) to just one of them. It would be enough to set `read == PERM_FULL` permissions for all those groups to the publication, and `read == PERM_NEVER` for some of them to some specific resources in that publication.
@manuelzane ?

**Comment by qwerg** [comment]
Go for it

Il giovedì 12 febbraio 2015, Paolo Cuffiani <notifications@github.com> ha
scritto:

> The second proposal might have also the benefit of making things easier
> when it is needed to give access permission to a publication to two or more
> different groups, but restricting access to some resources (like videos,
> for example) to just one of them. It would be enough to set read ==
> PERM_FULL permissions for all those groups to the publication, and read
> == PERM_NEVER for some of them to some specific resources in that
> publication.
> @manuelzane <https://github.com/manuelzane> ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bedita/bedita/issues/574#issuecomment-74040303>.
>


-- 
_______________
Andrea Alberti

**Comment by fquffio** [comment]
@batopa @stefanorosanelli @qwerg @edoardocavazza I'd move this issue to the next major release milestone.

**Comment by batopa** [comment]
:+1:
