### ISSUE TITLE
web app capable meta data

### ISSUE THREAD

**Issue by edoardocavazza** [bedita/bedita#576]
The main mobile browsers have implemented (or they are going to) a lot of feature for web apps development.

For example:
- Chrome on Android: now, you can add a web site to the home screen. Through an app manifest, you can specify the size of the app (fullscreen | with address bar | medium), the app icons, the start page and you can use application cache, localStorage, FileSystem and all Chrome features.

- Safari on iOS: you can add your sites to the home, using custom icons and splashscreens. It supports application cache and localStorage.

- IE 11 on Windows 8: you can "pin" the site in your home, using custom "tiles" (tiny | square | wide | large) and a custom feed for notifications (!!). It supports application cache and localStorage.

What about to add a section in the BEdita areas module in order to handle all this metadata/links?

@stefanorosanelli @batopa @didoda @qwerg @xho

**Comment by edoardocavazza** [comment]
We have a first implementation. Add your web app metadata using the `beFront` helper as follows `{$beFront->metaWebApp($publication.title, ["default" => "apple-touch-icon.png"], '#000')}`

**Comment by stefanorosanelli** [comment]
Added to ```bedita/bootstrap``` with check that BE version is >= 3.5.2
You can see it in http://test.bedita.com/bootstrap
