### ISSUE TITLE
basic EPUB 3 import / export capabilities

### ISSUE THREAD

**Issue by stefanorosanelli** [bedita/bedita#577]
Implement basic EPUB 3 import / export using #561 JSON importer / exporter
Goals: 
 * export section or publication ti epub3
 * import ebpu3 into BEdita objects structure

**Comment by didoda** [comment]
I experienced a problem with "max_execution_time", in some query. Strange that I get this problem today, even though there were no new updates in 15 days. I raised max_execution_time to 300 and I can export publications locally. TODO: understand what is slower than before and why.

I released some mini fix (to avoid warnings) and a patch to delete export temporary folder in case of exceptions before or during file export.

**Comment by stefanorosanelli** [comment]
epub development has now been moved to a dedicated addon
@didoda may we close this?

**Comment by didoda** [comment]
Comments are obsolete: epub dev has moved on.
We better close this issue.
