### ISSUE TITLE
Memory exhausted when creating new Section in large BE installations

### ISSUE THREAD

**Issue by fquffio** [bedita/bedita#578]
When attempting to create a new Section on a large BEdita installation with many publications and subsections, there is an issue that causes PHP to reach its memory limit. Therefore, page loading fails and an error is returned:
```
Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 854 bytes) in /var/www/bedita/cake/libs/model/datasources/dbo_source.php on line 2101
```
(By the way, 134217728 bytes = 128 MB, which seems a bit too much to load just the tree structure...)

**Comment by fquffio** [comment]
The memory leak seems to be within `BEAppModel::findObjects()`, as called within `Tree::getAll()`. There seem to be a lot of useless fields fetched from the DB. Unfortunately, there's no way to choose which DB fields one wants to be fetched (there would be an easy way to choose which fields to _exclude_, yet I find this to be quite counterintuitive).

**Comment by stefanorosanelli** [comment]
Patch seems ok, but I'm not sure if we want always and as default to ignore all those fields.
We could have backward compatibility issues whit some frontends.
Better solution would be having an array of ignored fields in __$filter__ to use in every call of findObjects / getAll.
@batopa ?

**Comment by fquffio** [comment]
@stefanorosanelli You're right. I'll find another way! :wink:

**Comment by batopa** [comment]
For me it's ok.
Leave open the pull request to handle ```$filter['ignoreFields']``` that can be an useful option.
