### ISSUE TITLE
beEmbedMedia->object video does not use URLonly when passed

### ISSUE THREAD

**Issue by edoardocavazza** [bedita/bedita#579]
When you use beEmbedMedia->object on a media object of type "video", and you pass the URLonly == true param, this param is being ignored.

**Comment by batopa** [comment]
```URLonly``` param wasn't handled only for ```presentation = full```. With 80ac5b7 we lost all ```URLonly``` features for presentation=link and presentation=thumb.

It should be

```
if ($params["presentation"] == "thumb") {
...
 } elseif ($params["presentation"] == "link" || $URLonly) {

}  elseif ($params["presentation"] == "full") {

}
```

in this way we would handle all cases correctly
