### ISSUE TITLE
section priority in JSON export/import

### ISSUE THREAD

**Issue by stefanorosanelli** [bedita/bedita#583]
Contents position on sections (priority) is missing from spec, and also not persistent doing export/import of data.
We should add to the spec priority info in objects "parents" attribute
https://github.com/bedita/bedita/wiki/Default-serialized-format-for-BEdita-objects

Something like:
```
"objects": {

    10: {
        "id": 10,
        "objectType": "document",
        ....
        "parents" : [ { "id":  2, "priority": 3} ],
        ....
    },
```

@batopa ?

**Comment by didoda** [comment]
I changed "parents" content, as described above by @stefanorosanelli. Pay attention: old json structure (without id/priority) is not accepted anymore by data_transfer->import

**Comment by didoda** [comment]
"doc" updated: https://github.com/bedita/bedita/wiki/Default-serialized-format-for-BEdita-objects

**Comment by stefanorosanelli** [comment]
Seems ok now for contents priorities.
But section priorities are missing - how do we handle them?
Inside "tree" array? 
Should we also update the "doc"?

**Comment by didoda** [comment]
I guess we should put "priority" inside "tree" structure. 
"validate" function already orders sections, according to parent ids. priority would simplify this process.

**Comment by stefanorosanelli** [comment]
Ok, let's put in "tree" as optional attribute

**Comment by didoda** [comment]
"doc" updated: https://github.com/bedita/bedita/wiki/Default-serialized-format-for-BEdita-objects

**Comment by stefanorosanelli** [comment]
Section priorities export is ok
Section priorities import seems ok as ordering but priority numbers are not preserved
Try to import this simple publication: section "Contact" (id 8) has priority 3 instead of 8 in the imported publication

```json
{
    "config": [
    ],
    "tree": {
        "roots": [
            "1"
        ],
        "sections": [
            {
                "id": "2",
                "parent": "1",
                "priority": "1"
            },
            {
                "id": "7",
                "parent": "1",
                "priority": "2"
            },
            {
                "id": "8",
                "parent": "1",
                "priority": "8"
            }
        ]
    },
    "objects": {
        "1": {
            "id": "1",
            "public_name": "Example",
            "public_url": "http:\/\/www.example.com",
            "staging_url": "http:\/\/www.example.com",
            "email": "info@example.com",
            "status": "on",
            "title": "Example",
            "nickname": "example",
            "description": "example.com made with BEdita",
            "priority_order": "asc",
            "objectType": "area"
        },
        "2": {
            "id": "2",
            "syndicate": "off",
            "priority_order": "asc",
            "status": "on",
            "title": "Channelweb",
            "nickname": "who",
            "description": "who are we?",
            "objectType": "section"
        },
        "7": {
            "id": "7",
            "syndicate": "on",
            "priority_order": "desc",
            "status": "on",
            "title": "News",
            "nickname": "news",
            "objectType": "section"
        },
        "8": {
            "id": "8",
            "syndicate": "off",
            "priority_order": "asc",
            "status": "on",
            "title": "Contact",
            "nickname": "contact",
            "objectType": "section"
        }
    },
    "relations": {
    }
}
```
