### ISSUE TITLE
JSON export enhancement - "types" and "all" options

### ISSUE THREAD

**Issue by stefanorosanelli** [bedita/bedita#584]
Shell data export should work this way:
 * using "id" option we get a section with all discendents or a publication or a single object (implemented)
 * using "types" option we get only selected types, all objects without tree positioning if "id" option is missing
 * using "all" option we get everything, every publication and every object, also "orphaned" objects not on a section

Examples:

 * export all documents and events from an instance, without tree position
```
./cake.sh data export -types document,event
```

 * export every object, also all publications
```
./cake.sh data export -all
```

 * export a section/publication structure, but only documents and images - use id and types option
```
./cake.sh data export -id 123 -types document,image
```

One of the 3 options must be present, we could assume "all" as default if no option is passed.

**Comment by didoda** [comment]
Examples 1 and 3, ok.
Example 2... the system export all the publications with tree. If we want another behaviour (all objects, without tree), some refactor is necessary.

**Comment by stefanorosanelli** [comment]
Examples 1 and 3 work, but:
 * some relations are missing - i did an export with -types _document_ and got 10 _link_ objects but just one **link** relation
 * should we get also related objects or just objects fo requested type? extracting documents I would expect just documents, however... don't know what the exptected behavior may be

With **-all** option I would expect to get every object, on publication tree or not - so every publication and every orphan object.

**Comment by stefanorosanelli** [comment]
Using **-types** option we may want to export:
 1. those types and only related objects of those types
 1. those types and also related objects of some types
 1. those types and all related objects

Current scenario is 3. Don't know if it's a good default, but we can keep it.

We then need two more options:
 1. **--exclude-other-types** to exclude other related types, if **-types** is used, otherwise option is ignored
 1. **--related-types** to add also some related types
 
@didoda what do you think?

**Comment by stefanorosanelli** [comment]
We could also move **-all** option implementation to a new issue

**Comment by didoda** [comment]
2 more options **--exclude-other-types** and **--related-types** are fine.

**Comment by stefanorosanelli** [comment]
Tested **-all** options:
- all objects are actually exported
- custom properties are missing (definitions and values)
- some fields are missing, like _body_ of events/documents, _DateItems_, _GeoTag_ of events and others...

Did a simple comparison with an export of a single publication on same instance.

**Comment by stefanorosanelli** [comment]
Also _relations_ are missing with **-all** option

**Comment by stefanorosanelli** [comment]
Tested **--exclude-other-types** option:
- only selected types are exported
- custom properties definitions and relations are exported
-  some fields are missing, like body of events/documents, DateItems, GeoTag of events and others... (like in **--all**)

**Comment by stefanorosanelli** [comment]
Tested again:
- missing fields or DateItems/GeoTag problem is solved
- **-all** seems now ok
- **-types** and **--exclude-other-types** is now OK - but all custom properties definitions are exported (also of other types)
- **-types** option (without **--exclude-other-types**) now has the same behavior of **-all** (!!!) without tree data - all objects are exported regardless of selected types...

**Comment by didoda** [comment]
With #689 'status' option for export.
Usage:

```
./cake.sh data export -f test.json -status on,draft
```

**Comment by stefanorosanelli** [comment]
seems ok, closing
