### ISSUE TITLE
Handle homePage tpl

### ISSUE THREAD

**Issue by edoardocavazza** [bedita/bedita#587]
If a ```home_page``` template exists in ```views/pages```, maybe should be preferred to the ```section``` one when the ```homePage``` method is called.

What do you think about it?

@batopa @fquffio @stefanorosanelli @qwerg @xho

**Comment by batopa** [comment]
Absolutely!

**Comment by batopa** [comment]
@edoardocavazza may you autoassign the issue or assign to @fquffio please? :smile:

**Comment by fquffio** [comment]
I tested this on Bootstrap and Boilerplate frontends. It should be ok. @edoardocavazza @rzecchini : could you please test this on a real frontend? :smirk:

**Comment by edoardocavazza** [comment]
seems ok, closing
