### ISSUE TITLE
Non-administrators backend users are able remove "fixed" property

### ISSUE THREAD

**Issue by fquffio** [bedita/bedita#590]
By simply manipulating POSTed data, even non-administrators backend users can remove "fixed" property, hence being able to edit every object in the modules they have access to.

It is possible that this bug is to be extended to frontend users as well.

**Comment by fquffio** [comment]
(It has to be noted that this bug was not introduced after #588, but was present even before.)

**Comment by stefanorosanelli** [comment]
By non-administrator you mean users not belonging to "administrator" group ?
I don't think that's a requirement: any user with read/write access to a module/object may add or remove *fixed* property. 
@batopa ?

If by "non admin" you mean non backend (frontend only) users that's actually something to avoid.

**Comment by fquffio** [comment]
@stefanorosanelli In templates, the "fixed" checkbox is kept hidden to users that don't belong to "administrator" group, even if they have read/write permission for that module. Yet, those users were able to edit the "fixed" flag by sending a custom POST request (actually, any user was able to do that, regardless of groups and other permissions).

There was either a bug in controller, or a mistake in templates. :wink:

**Comment by stefanorosanelli** [comment]
Ok, so, if we had this on template don't change it now. 
I do think that's not necessary (being "administrator"), but we may want to think about it and change it in a different issue.

**Comment by stefanorosanelli** [comment]
Tested, ok!
