### ISSUE TITLE
Inconsistency in controller method and view recognition

### ISSUE THREAD

**Issue by edoardocavazza** [bedita/bedita#601]
PHP class methods are **case insensitive**, so each method can be call by url using lowercase, UPPERCASE, or camelCase. Because of in our guidelines, we define class methods in camelCase and we refer views with underscores, there is an inconsistency problem.

Examples:

controller method: `mickeyLovesMinnie`
template file: `mickey_loves_minnie.tpl`

| url | works |
| --- | --- |
| .../mickeyLovesMinnie | yep |
| .../MICKEYLOVESMINNIE | nope (error 500) |
| .../mickeylovesminnie | nope (error 500) |
| .../mickey_loves_minnie** | yep |

*\* before looking for controller method, the passed action is converted in camelCase mode, where possible

**Comment by stefanorosanelli** [comment]
URLs are not case insensitive - the path part of an URL is in general case sensitive, so URLs with incorrect case shoud return a 404 or a 301 redirect to the right one

keep in mind in BE4

**Comment by stefanorosanelli** [comment]
Actually: Error 500 like those in the description should never happen - if it's a problem we could open an issue for that in BE3

**Comment by batopa** [comment]
obsolete
