### ISSUE TITLE
Relations modal window:  select all

### ISSUE THREAD

**Issue by qwerg** [bedita/bedita#605]
In the modal window I want to select and associate *all* search results items.

![scrnsh](https://cloud.githubusercontent.com/assets/2248878/6413436/b8c71770-be8f-11e4-80d5-bef64ff2ecc5.jpg)

**Comment by fquffio** [comment]
@qwerg Done. It seems to be working. Could you please test a bit and close if everything is ok? :smile:

**Comment by qwerg** [comment]
Ok. The label "select all" is missing, but the behaviour is so obvious, that it's probably useless.
