### ISSUE TITLE
Links custom properties not handled

### ISSUE THREAD

**Issue by fquffio** [bedita/bedita#607]
In backend context, it is possible to create new custom properties for `Link` model, but once they have bee created, it is not possible to set them (missing fields in `form.tpl`), or read them in frontend without creating a custom model binding. @batopa @stefanorosanelli is this intentional?

**Comment by batopa** [comment]
No intention here, you can add it to form and to model bindings.

Il giorno dom 1 mar 2015 04:36 Paolo Cuffiani <notifications@github.com> ha
scritto:

**Comment by fquffio** [comment]
Ok, thanks. Done and working, Travis CI passing. Don't think this needs further testing (in that case, my apologies).

I venture to close this issue... :fearful:
