### ISSUE TITLE
Remove Content-Style-Type meta when document type is HTML 5

### ISSUE THREAD

**Issue by fquffio** [bedita/bedita#608]
According to [W3C](http://www.w3.org/html/wg/wiki/HTML5_Authoring_Conformance_Study#Conformance_Errors_with_Unclear_Value), `<meta http-equiv="Content-Style-Type" />` is no longer a valid meta tag, as can be stated by checking a HTML 5 document against the validator.

Could we add an optional `$docType` parameter to `BeFrontHelper::metaAll()` to serve meta tags according to the provided document type?

**Comment by stefanorosanelli** [comment]
Yes, we could also introduce a $config parameter (in config/frontend.ini.php) to set frontend's doc type

**Comment by fquffio** [comment]
Done. Possible values for `BeFrontHelper::metaAll()` parameter OR `$config['docType']` (if present) should be the same as for [`HtmlHelper::docType()`](http://api.cakephp.org/1.3/class-HtmlHelper.html#_docType).

@stefanorosanelli Is this ok?

**Comment by stefanorosanelli** [comment]
It's ok
Only not sure about the best default - actually 'html5' should be default nowadays
Anyway we could keep it for minimum backward compatibility
Closing
