### ISSUE TITLE
Model 'Card' is not associated with model 'GeoTag'

### ISSUE THREAD

**Issue by fquffio** [bedita/bedita#609]
Under some circumstances (especially after authenticating, as it's a moment when user's Card is always loaded and stored in Session) we get a warning:
```
Warning (512): Model "Card" is not associated with model "GeoTag" [CORE/cake/libs/model/behaviors/containable.php, line 353]
```

This is due to the fact that GeoTag model appears in Card's `$modelBindings`, whilst Card is not actually associated to that model.

We should either associate Card to GeoTag, or remove GeoTag from Card's model bindings. @batopa @stefanorosanelli ?

By the way, in backend Card creation form, fields to specify a GeoTag for a Card are displayed, but nothing seem to happen on save. So I guess that Card should be associated with GeoTag, indeed (yet, isn't it a duplication of Card's address fields?).

**Comment by stefanorosanelli** [comment]
Did some testing and it seems ok now:
- GeoTag model is associated to Card
- in backend GeoTag tab is present and save works as expected

Probably solved in other commits
@fquffio can we close it?

**Comment by fquffio** [comment]
@stefanorosanelli I can't remember the last time I had this issue, that I usually experienced right after authenticating. I guess we could close it and reopen it should we ever run into this again.
