### ISSUE TITLE
Delete/turn off sections from the tree

### ISSUE THREAD

**Issue by rzecchini** [bedita/bedita#613]
If I delete a section from the section-list using the "x" sign it goes into a "limbo": it is still accessible via  url+id but it is technically hidden to the user.
We probably need a place where to see all this deleted stuff (a sort of trash bin?).

![schermata 2015-03-04 alle 11 10 31](https://cloud.githubusercontent.com/assets/2392233/6482024/98b7cd9a-c262-11e4-9741-a1ecac3b8f15.jpg)

**Comment by edoardocavazza** [comment]
A section without a parent has no reason to exist, in my opinion. Why should we keep it in DB? Maybe we could replace the "X" button (unlink) with "remove" button (delete), and remove the section at all. @qwerg @batopa 

@rzecchini can you please move your enhancement proposal in a separated issue? Thanks.

**Comment by qwerg** [comment]
Yes we should keep it if is not explicitly deleted with the delete button+confirm. A short X command its to easy to perform. So we can simply change his status to off, or use a sort of trash can (we have an issue about this #?)

**Comment by fquffio** [comment]
@qwerg Yes, #102.

**Comment by rzecchini** [comment]
enhanc. proposal moved

**Comment by qwerg** [comment]
resolved in #504
