### ISSUE TITLE
Checkbox behavior inside contents list

### ISSUE THREAD

**Issue by rzecchini** [bedita/bedita#614]
1. When checking the checkbox-input this event is registered as a change and it asks to save.
2. When checking the checkbox-input it should open the tools panel.

![schermata 2015-03-04 alle 11 16 07](https://cloud.githubusercontent.com/assets/2392233/6482112/33fbcd06-c263-11e4-98b2-cf5092f6eca7.jpg)

**Comment by edoardocavazza** [comment]
@fquffio can you test and close it?

**Comment by edoardocavazza** [comment]
Changed 2nd point in:
- When checking the checkbox-input it should open the <del>tools</del> <ins>bulk actions</ins> panel.

**Comment by fquffio** [comment]
Seems ok. Closing.
