### ISSUE TITLE
Manage the section status within the sections list

### ISSUE THREAD

**Issue by rzecchini** [bedita/bedita#617]
Enhancement: be able to directly manage the section status (eg. select the section via checkbox and change the status parameter—on, off, draft).

![schermata 2015-03-04 alle 11 10 31](https://cloud.githubusercontent.com/assets/2392233/6501358/85681f5a-c317-11e4-90c0-6a600a1f801a.jpg)

**Comment by stefanorosanelli** [comment]
solved in #504
