### ISSUE TITLE
First user created become system user and it has to be not removable

### ISSUE THREAD

**Issue by batopa** [bedita/bedita#618]
The first user created in BEdita become also the system user and it has to be not removable. For backward compatibility we use the user with id *1*.

Todo:

- [x] add a method `BeSystem::systemUserId()` (or similar) that return 1
- [x] replace `BEObject::defaultUserId` with `BeSystem::systemUserId()`. I think It only used in `BEObject::_getIDCurrentUser()`
- [x] remove the ability to delete that system user
- [x] add to BEdita initial setup some info about that the user created will be used as system user and it will be not removable

**Comment by stefanorosanelli** [comment]
We could also introduce default value for **objects.user_created** and **objects.user_modified** fields
```sql
ALTER TABLE `objects` CHANGE `user_created` `user_created` INT( 10 ) UNSIGNED NULL DEFAULT '1'
ALTER TABLE `objects` CHANGE `user_modified` `user_modified` INT( 10 ) UNSIGNED NULL 
DEFAULT '1'
```

**Comment by fquffio** [comment]
@stefanorosanelli At the moment, in `BEObject::_getIDCurrentUser()` the system user ID is used only if class `CakeSession` doesn't exist (I suppose that it means that sessions have been disabled completely by conf). In case sessions are enabled, but an object is created by a non-logged user, `null` is returned instead, which by the way is a value not accepted by corresponding SQL table fields. :confused:

Should that method return the system user ID by default, instead?

**Comment by stefanorosanelli** [comment]
Let's say that `BEObject::_getIDCurrentUser()` should not use `CakeSession` - current user id should be set directly from controller or caller in general (maybe as a BEAppObjectModel attribute?)

In this case however, if we don't find current user we could:
 1. return system ID
 1. return null - system ID will be set by SQL default (if we introduce it)

Both are acceptable
