### ISSUE TITLE
addressbook: country select box is not working

### ISSUE THREAD

**Issue by stefanorosanelli** [bedita/bedita#620]
In addressbook card view __country__ select box doesn't display current card's country

**Comment by xho** [comment]
A common list of countries with ISO code was added as an array in new configuration file:
`countries.iso.php`.

**Comment by stefanorosanelli** [comment]
Found a little problem: if you don't select a country saving a card it will get the first on the list (currently Afghanistan) as default  country is saved on db
We should be able to leave this field NULL as default
