### ISSUE TITLE
Data JSON export - use model binding

### ISSUE THREAD

**Issue by stefanorosanelli** [bedita/bedita#625]
Enhance #592 with a more general solution: use one of the model bindings, without trying to define all possible bindings

**Comment by stefanorosanelli** [comment]
Some data are missing, example exporting an Event with Calendar and GeoTag we get something like:
```json
    "objects": {
        "2587": {
            "id": "2587",
            "status": "on",
            "created": "2015-03-13 14:58:00",
            "modified": "2015-03-13 15:30:39",
            "title": "test event",
            "nickname": "test-event",
            "lang": "ita",
            "comments": "off",
            "objectType": "event"
        }
    },
```
where Calendar and GeoTag data are missing...

**Comment by fquffio** [comment]
Export now uses "default" model binding (if present) as specified in `TheModel::$modelBindings` array, or one of the two model bindings provided by default in `DataTransfer` model (either stream binding, or object binding) as a fallback.

Now, for example, exporting an Event will result in obtaining its `DateItem` data.
```json
{
    "objects": {
        "429": {
            "id": "429",
            "DateItem": [
                {
                    "id": "207",
                    "object_id": "429",
                    "start_date": "2015-03-20 14:00:00",
                    "end_date": "2015-03-20 18:00:00",
                    "params": null
                }
            ],
            "status": "on",
            "created": "2015-03-19 11:36:38",
            "modified": "2015-03-19 11:54:15",
            "title": "Test event",
            "nickname": "test-event",
            "description": "Just another test event",
            "lang": "eng",
            "comments": "off",
            "objectType": "event"
        }
    }
}
```
GeoTag data is still missing, because it is still in "to do" in `DataTransfer::rearrangeObjectFields()`, as probably we must still decide a default export format for it. @stefanorosanelli, @didoda: given that probably it could be enough to leave the `GeoTag` key untouched in the resulting array, should I take care of this within this issue, or open another one instead?

**Comment by stefanorosanelli** [comment]
Yes, also `GeoTag` should be present, it was not included in my example but we surely need it.
This issue is fine

Maybe `DateItem.id` field is not useful and could be dropped in export? Is there a risk to override an existing id?
Is `DateItem` correctly imported this way?

**Comment by fquffio** [comment]
@stefanorosanelli `DateItem.id` has been removed, as well as `DateItem.object_id`, hence both of these fields are handled automatically while saving the new object in import, and their presence in exported JSON might have caused overwriting of an existing DateItem or associating the DateItem to another object, respectively (apart from giving no useful information at all). `GeoTag` is now being handled the same way.

Import seem to work fine after those changes for both `DateItem`s and `GeoTag`s. `Annotation`s and `LangText`s are still in "TODO" in `DataTransfer::rearrangeObjectFields()`. I could take care of 'em. @didoda ?

**Comment by didoda** [comment]
@fquffio :+1:

**Comment by fquffio** [comment]
@stefanorosanelli @didoda Added `LangText` handling. Translations are now exported this way:
```json
"7": {
    "id": "7",
    "status": "on",
    "objectType": "event",
    "created": "2015-03-20 11:42:58",
    "modified": "2015-03-24 10:10:28",
    "title": "Test event",
    "nickname": "test-event-1",
    "lang": "eng",
    "lang_texts": {
        "fra": {
            "status": "on",
            "title": "Événement de test",
            "created_on": "1427185974",
            "modified_on": "1427185974",
            "created_by": "bedita",
            "modified_by": "bedita"
        },
        "ita": {
            "status": "on",
            "title": "Evento di prova",
            "created_on": "1427185974",
            "modified_on": "1427185974",
            "created_by": "bedita",
            "modified_by": "bedita"
        }
    }
}
```

This export format is also handled during import, making translations persistent across import/exports. Is this format ok? Could you please help me test this?

**Comment by didoda** [comment]
I would get rid of "created_by" and "modified_by".
What happens when there's more than one field translated (i.e. title, description)?
Every translation is collapsed inside single "lang" obj? it would be fine

**Comment by stefanorosanelli** [comment]
Agree with @didoda, as format I would use:
```json
{
     .....
    "title": "Test event",
    "lang": "eng",
    "lang_texts": {
        "fra": {
            "status": "on",
            "created_on": "2015-03-20 11:42:58",
            "modified_on": "2015-03-20 11:42:58",
            "title": "Événement de test",
            "description": "....."
        }
    }
}
```
Are multiple fields (title, description, body,....) already handled this way?

**Comment by fquffio** [comment]
After getting rid of `created_by` and `modified_by`, the output result is as follows:
```json
"5": {
    "id": "5",
    "body": "<p>Some other text.<\/p>\r\n",
    "status": "on",
    "created": "2015-04-02 09:18:31",
    "modified": "2015-04-02 09:18:31",
    "title": "Test document",
    "nickname": "test-document",
    "description": "<p>Words words words<\/p>\r\n",
    "lang": "eng",
    "comments": "off",
    "objectType": "document",
    "lang_texts": {
        "ita": {
            "status": "on",
            "title": "Documento di prova",
            "description": "<p>Parole parole parole<\/p>\r\n",
            "body": "<p>Ancora un po' di testo.<\/p>\r\n",
            "created_on": "1427959147",
            "modified_on": "1427959147"
        }
    },
    "parents": [
        {
            "id": 4,
            "priority": "1"
        }
    ]
}
```

Al the translated fields are outputted within the `lang_texts.<langcode>` object.

**Comment by stefanorosanelli** [comment]
Ok, I would use SQL datetime like `"2015-04-02 09:18:31"` instead of timestamp for readability on `modified_on/created_on`

**Comment by stefanorosanelli** [comment]
Export of `DateItem`, `GeoTag` and `LangText` seems ok
Why `lang_texts` instead of `LangText` ? (`LangText` would be more  consistent)

**Comment by stefanorosanelli** [comment]
Testing a single event import I get an error... @didoda @fquffio do I have to open a new issue?
Trying to import this json
```json
{
    "config": {
    },
    "tree": [
    ],
    "objects": {
        "3534": {
            "id": "3534",
            "body": "<p>The<strong>body<\/strong><\/p>\r\n",
            "status": "on",
            "created": "2015-02-05 09:52:00",
            "modified": "2015-04-07 16:18:37",
            "title": "The Event",
            "nickname": "the-event",
            "lang": "eng",
            "comments": "off",
            "GeoTag": [
                {
                    "latitude": "44.494820",
                    "longitude": "11.339692",
                    "address": "Via Rismondo 2, Bologna",
                    "gmaps_lookat": {
                        "zoom": "18",
                        "mapType": "k",
                        "latitude": "44.4948179",
                        "longitude": " 11.339692000000014",
                        "range": 5961.9159740835
                    }
                }
            ],
            "customProperties": [
            ],
            "DateItem": [
                {
                    "start_date": "2015-03-24 00:00:00",
                    "end_date": "2015-03-27 00:00:00",
                    "params": "a:1:{s:4:\"days\";a:3:{i:0;s:1:\"1\";i:1;s:1:\"2\";i:2;s:1:\"3\";}}",
                    "days": [
                        "1",
                        "2",
                        "3"
                    ]
                }
            ],
            "objectType": "event",
            "lang_texts": {
                "ita": {
                    "status": "on",
                    "title": "L'evento",
                    "body": "<p>bla bla bla<\/p>\r\n",
                    "created_on": "2015-04-07 18:20:42",
                    "modified_on": "2015-04-07 18:20:53"
                }
            },
            "categories": [
                {
                    "name": "booh",
                    "label": "booh"
                }
            ]
        }
    },
    "relations": [

    ]
}
```
I get this error:
```
ERROR: missing tree in source json data
```
but tree is not needed here (parents array is empty)

**Comment by didoda** [comment]
@stefanorosanelli, tree is not needed, right. it's a bug to fix. new issue? maybe not necessary... we could fix and release in here.
Case to handle (it's not an error):
 => empty tree, objects without 'parents'

**Comment by stefanorosanelli** [comment]
Seems ok now
@fquffio one last thing before closing, as in my previous comment: may we use `LangText` instead of `lang_texts`?

**Comment by fquffio** [comment]
@stefanorosanelli Sorry, I missed your comments. Done.

**Comment by stefanorosanelli** [comment]
@fquffio everything ok
but after import I don't see translations on new object 
Try to import json example in https://github.com/bedita/bedita/issues/625#issuecomment-90640226 changing  `lang_texts` to `LangText`.

**Comment by stefanorosanelli** [comment]
some minor side effects from the use of model bindings in #662
