### ISSUE TITLE
data export: don't add custom properties config if a type is not exported

### ISSUE THREAD

**Issue by stefanorosanelli** [bedita/bedita#626]
Using _-types_ option in data export, like
```
./cake.sh data export -types document,short_news
```
in resulting _config.customproperties_ array only custom properties of selected types should be present

**Comment by stefanorosanelli** [comment]
There are two exceptions to handle: 
 1. if we are exporting a publication also **config.customproperties**  for type _section_ and _area_ must **always** be present
 1. if we are exporting a section also **config.customproperties**  for type _section_ must **always** be present (in this case we don't expect to have publications)

**Comment by stefanorosanelli** [comment]
Test failed.
Exporting with ```-types short_news -relations attach``` i get these results:
```
Num of objects: 104
Types: short_news(99) image(5) 
Relations: attach(6) 
```
but exported json file contains customproperties of type *area*

**Comment by didoda** [comment]
@stefanorosanelli  short_news or images were inside area? in that case, export is correct
I'll check myself with another example

**Comment by stefanorosanelli** [comment]
short_news were inside areas/sections but areas/sections were not exported
fixed now
