### ISSUE TITLE
ui: handle import/export filter dynamic options

### ISSUE THREAD

**Issue by stefanorosanelli** [bedita/bedita#640]
* in import/export filter model classes define options to use, using: option name, option values for a fixed list or a description for input parameter (like custom properties?)
 * those options are registered in config, like names and mime types
 * in UI when we select a filter we show those options: a combo/select if there's a fixed list, an input text otherwise

a more general solution to #415

**Comment by didoda** [comment]
Data structure sample... an idea:
```
$options = array(
	'myOption1sample' => array(
		'name' => 'myOption1',
		'label' => 'My Option 1'
		'dataType' => 'number' // number|date|text|options
	),
	'myOption2sample' => array(
		'name' => 'myOption2',
		'label' => 'My Option 2'
		'dataType' => 'options', // number|date|text|options
		'values' => 'document,image,video',
		'attributes' => array(
			'multipleChoice' => true
		)
	)
)
```

**Comment by qwerg** [comment]
I suggest to use a separate view like the actual demo page
/admin/importData
for the export / import options and choices.

**Comment by stefanorosanelli** [comment]
yes, new import page is in progress in #641 
we could create an element .tpl for the view and then use it in this page or elsewhere

export is not handled in #641 but options mechanism is the same for import / export

**Comment by xho** [comment]
I agree with Dante as regards the options array, but i suggest a couple of things.

* each option should also contain the following informations:
   * is the option mandatory? (required to proceed with import)
   * is there a default value?
* also there should be an option that tells if data imported are placed in a branch of the publications' tree (and it should also be defined as mandatory or not).

**Comment by stefanorosanelli** [comment]
Also (in another issue?) introduce `$typeLabel` as more descriptive filter label in backend UI.
`$typeName` should not contain spaces and be _shell_ friendly as it's also used via command line

**Comment by didoda** [comment]
Data structure sample updated:
```
$options = array(
	'myOption1sample' => array(
		'name' => 'myOption1',
		'label' => 'My Option 1'
		'dataType' => 'number', // number|date|text|options
                'mandatory' => true,
                'defaultValue' => 1000
	),
	'myOption2sample' => array(
		'name' => 'myOption2',
		'label' => 'My Option 2'
		'dataType' => 'options', // number|date|text|options
		'values' => 'document,image,video',
		'attributes' => array(
			'multipleChoice' => true
		)
	),
        'myOptionPublishInfo' => array(
		'name' => 'myOptionPublishInfo',
		'label' => 'My Option Publish Info'
		'dataType' => 'options', // number|date|text|options
		'chooseTreePosition' => 'true', // in UI there will be the tree of publications to choose destination for data
		'attributes' => array(
			'multipleChoice' => true
		)
	)
)
```

**Comment by stefanorosanelli** [comment]
OK
`chooseTreePosition` or `treePosition` (default false) should be a property of the import class filter, not the option

**Comment by didoda** [comment]
A real case from #641: 
```
public $label = 'CSV/vCard import filter';
    public $options = array(
	    'overwritePolicy' => array(
	        'label' => 'If a card with same email exists',
	        'dataType' => 'options', // number|date|text|options
		'values' => array(
			'overwrite' => 'overwrite the card',
			'new' => 'create a new card',
			'skip' => 'skip'
		),
		'defaultValue' => 'skip', // can be 'overwrite', 'new', 'skip'
		'mandatory' => true,
	    	'multipleChoice' => false
	),
    	'validateEmail' => array(
    	    'label' => 'If email is not valid',
		'dataType' => 'options', // number|date|text|options
		'values' => array(
			'import' => 'import',
    			'skip' => 'skip'
    		),
		'defaultValue' => 'skip', // can be 'import', 'skip'
		'mandatory' => true,
		'multipleChoice' => false
    	)
);
```

**Comment by didoda** [comment]
TODO: 'destination/tree' option. Idea: if option contains 'id' then UI shows publication(s) tree with checkboxes or radio (multipleChoise false|true), to choose destination for import data

**Comment by stefanorosanelli** [comment]
Agree with @didoda we could:

a) introduce a _special import option_ __id__ 
If present we should show publications tree UI to select destination (maybe also numeric id as option)
_multipleChoice_ probably makes no sense in this context (destination id should be unique), but it could be mandatory

b) we could use a __special dataType__ _tree_ to select tree positions and show publications tree UI

**Comment by didoda** [comment]
How could 'special import option id' be?
```
public $options = array(
    'id' => array(
        'label' => 'Publish data to',
        'dataType' => 'tree',
        //'defaultValue' => '1', // default position (area or section id) for data import
        'mandatory' => true,
        'multipleChoice' => false // if true, then multiple positions allowed
    )
);
```

**Comment by stefanorosanelli** [comment]
Using __tree__ dataType we don't need a special option __id__ , we could use any name
seems a better solution, proposed structure is fine, proceed with this

**Comment by stefanorosanelli** [comment]
Tested dataTypes:
 * tree OK
 * text OK
 * options OK
 * number OK (but same as text??)
 * date KO

Proposal: just start with main option types tree / text/ options / (maybe number) that will cover known cases just fine - will add different types later if necessary (like date/boolean/...)

**Comment by didoda** [comment]
Released template fixes. Every case is managed (included date and boolean).
You can test with the following $options array:

```
public $options = array(
        'test1' => array(
            'label' => 'Test 1 boolean',
            'dataType' => 'boolean'
        ),
        'test2' => array(
            'label' => 'Test 2 text',
            'dataType' => 'text'
        ),
        'test3' => array(
            'label' => 'Test 3 date',
            'dataType' => 'date'
        ),
        'test4' => array(
            'label' => 'Test 4 number',
            'dataType' => 'number'
        ),
        'test5' => array(
            'label' => 'Test 5 tree',
            'dataType' => 'tree'
        ),
        'test6' => array(
            'label' => 'Test 6 options',
            'dataType' => 'options',
            'values' => array(
                '1' => 'one',
                '2' => 'two',
                '3' => 'three'
            ),
            'defaultValue' => '1', // can be '1', '2', '3'
            'mandatory' => true,
            'multipleChoice' => false
        ),
    );
```

**Comment by stefanorosanelli** [comment]
Ok, well done
Is there a difference between _text_ and _number_ ?
Closing anyway

**Comment by didoda** [comment]
@stefanorosanelli text input field size is 40, number input field is 12 (it makes sense... usually text strings can be longer than numbers). there's no "maxlength" for both input fields. text input has "textinput" class, number field has "numberinput" class. I used the same naming convention used in dates... (class dateinput... [ < type >input ]).
