### ISSUE TITLE
new data import page on backend

### ISSUE THREAD

**Issue by stefanorosanelli** [bedita/bedita#641]
New data import page (may be part of a future module)
 * use `HomeController`, link on the left near `Home`/`Profile` links
 * use available import filters, like in `Publications / Tools / Import`
 * show preview if (available)
 * show results summary and other info, link to new data (if available)

**Comment by stefanorosanelli** [comment]
Seems ok. 
I would prefer results input options and results on the same page, so we shouldn't click and return to import page for a new import

Preview feature could be moved to a new issue

**Comment by qwerg** [comment]
* Why the "save" button on left column?
* Agree with @stefanorosanelli, same page for results and options. Options set for the last import should be preserved/checked.

**Comment by stefanorosanelli** [comment]
"Save" button removed

**Comment by didoda** [comment]
commit "526c898" to merge to "issue/641-new-data-import-page" branch?

**Comment by didoda** [comment]
merged with 3-corylus. maybe we could drop remote branch issue/641-new-data-import-page

**Comment by stefanorosanelli** [comment]
Can we drop __Publication / Tools / Import__ button?

**Comment by qwerg** [comment]
No,  would be better to transform the button to a link, pointing to the new import page, with current section selected.

**Comment by stefanorosanelli** [comment]
Problem is: on import page all options are dynamic, selection of a section for import depends on filter, so we have to select filter first....

**Comment by qwerg** [comment]
The same problem (dynamic options) is present for the EXPORT page, and I think:
- import and export command need to stay on the same position and have the same trigger
- user should be able to start directly in the new stand alone page, with tree select and other filters AND
- user should be able to start from the desired position in publications/tree (common behaviour)

why we need to select a filter first?
In /home/import/
we can preselect a tree position with get parameters....

**Comment by stefanorosanelli** [comment]
Because we don't know which parameters a filter has
 **CSV / vCard** import filter does not have a _tree_ parameter, usually you don't import cards on a section, same could happen with other filters...

**Comment by qwerg** [comment]
In that case the tree ID get parameter will be ignored...

**Comment by stefanorosanelli** [comment]
Closing
Activity on import page moved to #736
Export UI design in #663
