### ISSUE TITLE
Maximize button for rich text editor in Newsletter module

### ISSUE THREAD

**Issue by xho** [bedita/bedita#642]
Maximize button has been removed when we switched to CKeditor, because of a bug in this plugin that overwrites all parent styles when maximizing. At least in Newsletter it should be available, since editing fixed width HTML larger than the textarea is difficult.

**Comment by xho** [comment]
I made a fix that works in newsletter module, but I had to disable the ESC key binding (if pressed while maximized it changes the css of tabs and everything disappears).
Fixing this, I also reviewed a bit the main BEditaUI.js.

We should consider upgrading CKEditor, maybe the bug is solved.
(and also finally remove traces of TinyMCE which we definitely not support anymore).

**Comment by edoardocavazza** [comment]
#411 we already have an issue for that.

**Comment by xho** [comment]
Ok, I made this as a temporary solution just for Newsletter module, since there you usually edit fixed width html content. An update of CKeditor may solve this and other minor issues.
