### ISSUE TITLE
Add media attach relation from CKEditor

### ISSUE THREAD

**Issue by edoardocavazza** [bedita/bedita#649]
Add a new button to CKEditor for media relation inserting, using the BEmodal.

**Comment by stefanorosanelli** [comment]
@edoardocavazza are we going to merge this in BE3 or wait till BE4 ?

**Comment by edoardocavazza** [comment]
In BE3, if possible :S

**Comment by stefanorosanelli** [comment]
ok, we'll keep it here

**Comment by batopa** [comment]
obsolete
