### ISSUE TITLE
data JSON export/import from backend via filter

### ISSUE THREAD

**Issue by stefanorosanelli** [bedita/bedita#652]
Create filter classes to import/export JSON using surrent logic
Don't export media files

Add option to import media files from base URL or path on local filesystem

**Comment by didoda** [comment]
TODO: UI for export options (#640, #641, or new issue?)

**Comment by stefanorosanelli** [comment]
#641 deals only with import
#640 is quite general, but has overlaps with #641 and we could probably close it (will chek and do it)
As for export we have many possible entry points:
 1. export in list filter, like currently in addressbook CVS/vcard export, we could add a generic export button
 1. export a single object
 1. export a section/publication, currently available

We could work (and fix) current export modal in publications module (in #640) and add it later as bulk filter (list filter) - single object surely less important

**Comment by didoda** [comment]
@qwerg @xho, do you think we could have another solution, instead of export in "modal"? maybe we could have an "export block" in every single object view (containing options, like in import page). We already have "export" button in section/publication, with modal... is it ok, or we could drop that button and use an "export block"? I guess we need a new issue :)

**Comment by stefanorosanelli** [comment]
Import filter test failed, two problems:
 *  *sourceMediaUri* option is not handled in `DataTransfer` model, instead *sourceMediaUrl* is
 *  in import.log we have this error 

```sourceMediaRoot folder "TMP/media-import" not found```

probably caused by

```$this->import['sourceMediaRoot'] = 'TMP' . DS . 'media-import'```

that should be
```$this->import['sourceMediaRoot'] = TMP . 'media-import'```

**Comment by stefanorosanelli** [comment]
as for previous comment by @didoda I agree, will open a new issue for that and discuss it with the team
