### ISSUE TITLE
Set JPEG quality in BeEmbedMedia

### ISSUE THREAD

**Issue by fquffio** [bedita/bedita#659]
When using BeEmbedMediaHelper it could be helpful if we were able to set the JPEG quality for the thumbnail to be generated using an additional parameter `quality`.

**Comment by fquffio** [comment]
Added `interlace` param as well.

**Comment by batopa** [comment]
@edoardocavazza, @qwerg please could you test and close it?

**Comment by batopa** [comment]
Fix some issues using imagemagick. It seems all ok!
