### ISSUE TITLE
ui: data export from backend

### ISSUE THREAD

**Issue by stefanorosanelli** [bedita/bedita#663]
As proposed by @didoda in #652 
(see https://github.com/bedita/bedita/issues/652#issuecomment-91483752)
we could:
 * drop current **Export** button from *Publication / Tools*
 * add new **Export** block in _Publications_ containing element .tpl similar to the new import page #641 (with dynamic options etc...)
 * we could use same **Export** block for single object views (not so important, but useful to have maybe)
 * a really similar **Export** block could be placed at the bottom of the object list view for bulk export using current filter - like _Export # cards_ in **Addressbook**

@qwerg @batopa any thoughts?

**Comment by qwerg** [comment]
Agree. 
Can we close #504 (and maybe #641) and merge related branches, before working on a new section detail page?

**Comment by stefanorosanelli** [comment]
Yes, #504 can be closed (we need just a trivial label change, we can do it afterwards)
as for #641 I would change it to single page view before closgin/merging

**Comment by stefanorosanelli** [comment]
Another solution (proposed by @qwerg)
https://github.com/bedita/bedita/issues/641#issuecomment-111044077

To summarize the proposal:
1. new export page (similar to current import page)
2. from publications module (or other module) we can have a link to this page with current section/area id (as GET or POST param) to use with filters as _ready to go_ tree parameter

We have to choose between this and/or the issue description
What's best?
@qwerg @xho @batopa

**Comment by stefanorosanelli** [comment]
in #771 will be implement first two points of original issue description
- drop current **Export** button from _Publication / Tools_
- add new **Export** block in _Publications_ containing element .tpl similar to the new import page #641 (with dynamic options etc...)

Other points may be implemented in the future, but not now.
Closing
