### ISSUE TITLE
Which objectTypes should we use in customRelations manager?

### ISSUE THREAD

**Issue by qwerg** [bedita/bedita#668]
Managing custom relations, we can select source and target objects only from _objectTypes['related']_ array. So, areas and sections, comments etc are missing. Consider to expose _all_ kind of objects.

**Comment by stefanorosanelli** [comment]
I would keep same structure but add missing `$objectTypesGroups` attribute `'related'` in model definition to those object types like section, area, comment....

**Comment by stefanorosanelli** [comment]
areas and section are present now - closing
