### ISSUE TITLE
data transfer: refactor

### ISSUE THREAD

**Issue by didoda** [bedita/bedita#669]
When #667 is closed, some refactoring is needed on `DataTransfer` class.
Refactoring tips:
- variables and arrays (multilevel arrays to single level arrays)
- reusing code (find common parts, create private functions, etc.)
- code conventions (naming, spaces, etc.)
- enhance logs? other?

**Comment by stefanorosanelli** [comment]
Couple of suggestions
- using **verbose** mode (`-v` option) add a log line for each media file copied with source and destination paths
- in log files a numeration like ''2.2.1.1" or "2.3.1" was useful during development but seems unnecessary now

**Comment by didoda** [comment]
refactor done in local branch  issue/669-data-transfer-refactor.
when #667 is done, I'll perform a local merge and then some test... then commit+push

**Comment by didoda** [comment]
I'm still keeping local branch issue/669-data-transfer-refactor (merged 3-corylus to it, just now).
Any news about #667?

**Comment by stefanorosanelli** [comment]
unfortunately not, moved after 3.6 release

**Comment by stefanorosanelli** [comment]
I've moved #667 to BE4, we could:
- close issue as it is
- or do some simple/trivial tests on your branch - if ok merge it and close

@didoda ?

**Comment by didoda** [comment]
my local branch is too old: in 3-corylus we had bugs fixes recently.
I think the merge would be a mess.
we better close the issue and refactor when we work with data transfer
