### ISSUE TITLE
Managing dateItems before 1000 AD

### ISSUE THREAD

**Issue by qwerg** [bedita/bedita#670]
In some projects we need to handle dateitems for events and people (card) in remote past.
Current date_items Bedita table is using mysql _datetime_ data type, so we can't manage dates before 1000 AC unless _sqlmode_allow_invalid_dates_ is enabled.
http://dev.mysql.com/doc/refman/5.6/en/sql-mode.html#sqlmode_allow_invalid_dates
Even so, dates BC aren't possible.
So how can we:
- handle dates BC in events and cards (and maybe in other models)
- store a generic 'YEAR' value (2015-00-00??) without months and days
  ?

**Comment by fquffio** [comment]
We could store dates in a `BIGINT` format, like YYYYMMDDHHMMSS (year-month-day-hour-minute-second).
Doing so:
- ordering and comparisons are kept
- BC dates could be treated as negative integers without any issue
- Any "uncertain" date could be stored using some "special" value, which is an invalid date, but follows some convention we can decide
- dates up to 900+M years before and after Christ would be supported.

This would need some caring in building and reading dates, but it should be quite easy to do.
We could also improve performances using a format like the one above transported to binary numbers, instead of using base 10, but this would make dates much less human-readable.

**Comment by batopa** [comment]
To avoid conversion of many data in production databases it's for me preferable to maintain the current format transforming the data type from DATETIME to VARCHAR i.e. 'YYYY-MM-DD HH:MM:SS' and use another field for BC/AC date or the '-' ahead of date.

Using string like that ordering and comparison functions like '<', '>', MAX(), MIN() continue to work properly (also with '-' ahead). I don't know about performance. 

In some rare situations we could save text values (second half of the XII century) losing obviously ordering feature.

**Comment by fquffio** [comment]
@batopa Actually, using the lexicographic order for dates formatted like MySQL datetime seems to carry some problems with dates out of the range 1000-9999 AC:

```
mysql> SELECT * FROM test;
+----+----------------------+
| id | dates                |
+----+----------------------+
|  1 | 2015-08-17 20:30:30  |
|  2 | 20000-10-10 00:00:00 |
|  3 | 0-01-02 03:04:05     |
|  4 | -100-01-02 10:10:10  |
|  5 | -101-10-20 23:23:23  |
|  6 | 300-10-01 17:08:32   |
+----+----------------------+
6 rows in set (0,00 sec)

mysql> SELECT * FROM test ORDER BY dates;
+----+----------------------+
| id | dates                |
+----+----------------------+
|  4 | -100-01-02 10:10:10  |
|  5 | -101-10-20 23:23:23  |
|  3 | 0-01-02 03:04:05     |
|  2 | 20000-10-10 00:00:00 |
|  1 | 2015-08-17 20:30:30  |
|  6 | 300-10-01 17:08:32   |
+----+----------------------+
6 rows in set (0,00 sec)

mysql> SELECT * FROM test ORDER BY dates DESC;
+----+----------------------+
| id | dates                |
+----+----------------------+
|  6 | 300-10-01 17:08:32   |
|  1 | 2015-08-17 20:30:30  |
|  2 | 20000-10-10 00:00:00 |
|  3 | 0-01-02 03:04:05     |
|  5 | -101-10-20 23:23:23  |
|  4 | -100-01-02 10:10:10  |
+----+----------------------+
6 rows in set (0,00 sec)
```

**Comment by batopa** [comment]
You are right. I tested with simple data with year with four chars. Unluckily there isn't a natural sort function in mysql.

I have found this workaround that seems work

``` sql
SELECT * FROM `date_items` ORDER BY  `date_items`.`start_date`+0 ASC
```

but it should be well tested and... not so pretty

**Comment by fquffio** [comment]
@batopa Sorry for being the party pooper, but your workaround seems to work fine for years, but then the problem remains for finer grain ordering. :disappointed: 

```
mysql> SELECT * FROM test ORDER BY dates + 0;
+----+----------------------+
| id | dates                |
+----+----------------------+
|  5 | -101-10-20 23:23:23  |
|  4 | -100-01-02 10:10:10  |
|  3 | 0-01-02 03:04:05     |
| 10 | 300-01-01 17:08:32   |
|  9 | 300-12-01 17:08:33   |
|  8 | 300-12-01 17:08:31   |
|  7 | 300-12-01 17:08:32   |
|  6 | 300-10-01 17:08:32   |
|  1 | 2015-08-17 20:30:30  |
|  2 | 20000-10-10 00:00:00 |
+----+----------------------+
10 rows in set, 10 warnings (0,00 sec)
```

Using a mock two-fields ordering seems to solve this issue, but looks even worse. :grin: 

```
mysql> SELECT * FROM test ORDER BY dates + 0, dates;
+----+----------------------+
| id | dates                |
+----+----------------------+
|  5 | -101-10-20 23:23:23  |
|  4 | -100-01-02 10:10:10  |
|  3 | 0-01-02 03:04:05     |
| 10 | 300-01-01 17:08:32   |
|  6 | 300-10-01 17:08:32   |
|  8 | 300-12-01 17:08:31   |
|  7 | 300-12-01 17:08:32   |
|  9 | 300-12-01 17:08:33   |
|  1 | 2015-08-17 20:30:30  |
|  2 | 20000-10-10 00:00:00 |
+----+----------------------+
10 rows in set, 10 warnings (0,00 sec)
```

**Comment by fquffio** [comment]
According to PHP documentation of function [`strtotime()`](http://php.net/manual/en/function.strtotime.php):

> For 64-bit versions of PHP, the valid range of a timestamp is effectively infinite, as 64 bits can represent approximately 293 billion years in either direction.

Thus, we can perform column conversion to `BIGINT` in database, then take care of converting dates to or from the appropriate format when writing, reading and querying within the `DateItem` model, in such a way that other parts of the application will never be aware of this difference. BEdita should then be able to handle both table schemas in a transparent way: columns of type `DATETIME` as well as columns of type `BIGINT` with timestamp values.

**Comment by stefanorosanelli** [comment]
seems perfect, proceed!

**Comment by batopa** [comment]
Done some tests:
1. save date items with classic schema (datetime) works as expected
2. update schema and data through SQL conversion works as expected
3. save positive date items with new schema (bigint) works as expected
4. trying to save negative date items. From events module inserting negative year as `-01-02-200` or `01-02--200` save date items with `NULL` value. The right way to save negative date is edit data before save setting ISO-8601 date format.

**Comment by fquffio** [comment]
@batopa Issue 4) should by now have been fixed. Still, the UI cannot handle this properly, as the JS calendar prevents the user from inserting a date in the format `-MM-DD-YYYY`, `DD/MM/-YYYY` or whatever, but if the user "forces" the input value, the saved value should now be as expected.

**Comment by batopa** [comment]
@fquffio test is ok :+1:
