### ISSUE TITLE
Categories' bulk actions

### ISSUE THREAD

**Issue by fquffio** [bedita/bedita#671]
It might be useful to have bulk actions in categories' page, such as bulk delete (that obsoletes atomic deletion) and fast categories merging.
Me might also consider implementing a different way to edit existing categories (either using AJAX or a bulk-save operation) and a lightweight JS filter.

**Comment by qwerg** [comment]
I noticed a 500 error for 'Missing View' on plugins (tickets or questionnaires) after bulk saving or merging.
In core modules it's all ok.

**Comment by fquffio** [comment]
@qwerg Hence many plugin modules overwrite the `forward()` function, for such modules we should add key/item pair:

``` php
"bulkCategories" => array(
    "OK" => "/the_plugin/categories",
    "ERROR" => "/the_plugin/categories"
),
```

to `$REDIRECT` array in `ThePluginController::forward()`. This is due to the fact that the bulk actions use a different controller action than the previous atomic delete, thus needing a custom redirection. For core modules, this has already been done, but for plugin modules I'd rather wait 'till bulk categories actions are a core feature. Should I commit such changes to plugin modules already?

**Comment by batopa** [comment]
Remember that we have to maintain backward compatibility. If changes does not impact plugins installed in old (<= 3.5.1) BEdita we can do it.

**Comment by fquffio** [comment]
@batopa Backward compatibility is fully kept: it's an additional routing rule, that does not affect other ones.

**Comment by batopa** [comment]
@fquffio ok then I agree with you. Updating plugins should be done when the new feature will be merged in main branch

**Comment by batopa** [comment]
I think the merge option is ambiguous.  We should specify what category is maintained or at least write next to the 'merge' button what will happen

**Comment by fquffio** [comment]
@batopa I have improved a bit the information messages. Should be clearer now, please let me know. :smile:

**Comment by batopa** [comment]
Pull request #672 merged

**Comment by fquffio** [comment]
Temporarily reopening as I must update plugin modules as well, to fix misbehavior as of @qwerg comment.

**Comment by fquffio** [comment]
All plugin modules should be ok now. Closing.
