### ISSUE TITLE
API: blacklist property to forbid use of some methods

### ISSUE THREAD

**Issue by stefanorosanelli** [bedita/bedita#679]
Introduce a **blacklist** property to list default methods that cannot be called from on the api controller instance

**Comment by batopa** [comment]
To blacklist endpoints add to frontend `ApiController`

``` php
protected $blacklistEndPoints = array();
```

and fill the array with the endpoints to blacklist.

**Comment by batopa** [comment]
Documented here https://github.com/bedita/bedita/wiki/REST-API:-customize-endpoints#blacklist-endpoints
Closing
