### ISSUE TITLE
API: Access token remotion

### ISSUE THREAD

**Issue by edoardocavazza** [bedita/bedita#682]
The `deleteAuth` method in `api_base_controller.php` requires 2 arguments (`$userId` and `$refreshToken`), but:
- why we need to pass the user id to the method? Could we just use the result of `$this->BeAuthJwt->identify()` ? Why the control `if (!$user || $user['id'] != $userId)` is needed?
- could we extract the refresh token just using the $userId?

**Comment by batopa** [comment]
@edoardocavazza you are right... It is a check remained from my testing code :smile: I'm going to remove `$userId` as first paramter. So you will need to pass only refresh token and access token in header of course. It is enough to identify user and revoke refresh token
