### ISSUE TITLE
API: create an online test instance

### ISSUE THREAD

**Issue by edoardocavazza** [bedita/bedita#683]
enable api controller on [BEdita test instance boilerplate frontend](http://test.bedita.com/boilerplate) with `basePath = '/api/v1'`

**Comment by edoardocavazza** [comment]
I have not the permissions to update the frontends using git. @stefanorosanelli May you update the boilerplate frontend in bedita test? Thanks.

**Comment by stefanorosanelli** [comment]
Fixed. Try again...
