### ISSUE TITLE
API: setup default pagination limit

### ISSUE THREAD

**Issue by batopa** [bedita/bedita#685]
At the moment by default no pagination is set so calling for example `/objects/:id/children` on a section with many children can produce slow and big response.

We should define a default pagination limit. I think 20/30 objects for page is reasonable.This default should be overridable in frontend ApiController or in configuration.

**Comment by batopa** [comment]
We also need to define a max limit and return a 'Bad Request' 400 in case of request with limit over that

**Comment by stefanorosanelli** [comment]
I would set 20 as default size and 100 as max (like in backend object lists)
In controller you have to be able to change both

**Comment by batopa** [comment]
In `ApiController` you can override the default

``` php
protected $paginationOptions = array(
    'page' => 1,
    'pageSize' => 20,
    'maxPageSize' => 100
);
```

**Comment by batopa** [comment]
Added [documentation](https://github.com/bedita/bedita/wiki/REST-API:-pagination)
