### ISSUE TITLE
[import/export] problems exporting a section with `off` status

### ISSUE THREAD

**Issue by edoardocavazza** [bedita/bedita#689]
Exporting a publication which contains a section with `off` status generates some inconsistencies:
- children objects of the section have the correct `parent` relation
- the section object is in the `objects` array
- the section reference **is not** in the `tree`->`sections` array

**Comment by didoda** [comment]
@edoardocavazza, issue resolved, with #690 closed?

**Comment by didoda** [comment]
What's the expected behaviour? It should be consistent.
It's fine that "the section object is in the objects array", as long as it has "status" = "off".
Should we expect that tree->sections contain the section? I'd say yes, but we need to underline that section is off (adding a new attribute 'status' to section details in 'tree').

```
    "tree": {
        "roots": [
            1
        ],
        "sections": [
            {
                "id": "2",
                "parent": "1",
                "priority_order": "asc",
                "syndicate": "off",
                "priority": "1",
                "status": "off"
            }
        ]
    }
```

**Comment by didoda** [comment]
tree->sections can contain now 'draft' and 'off' sections.
I would add a filter/option in export, to allow to export objects by status(es).
For instance:

```
./cake.sh data export -f test.json -all -status on,draft
```

**Comment by didoda** [comment]
Added 'status' option to shell function `data`.
Usage example:

```
./cake.sh data export -f test.json -all -status on,draft
```

Default behaviour: export all statuses objects ('on','off','draft')

**Comment by stefanorosanelli** [comment]
Problem seems solved now - current behaviour:
- default: we get everything (also sections "off")
- if we choose statuses we get consistent results; using **--status on,draft** an "on" document in an "off" section will not be exported

Before closing: do we need status attribute in _tree.sections_ output? we already have status in corresponding object detail

**Comment by didoda** [comment]
Not sure everything still works, if we drop tree.sections[i].status.
We could try and see what happens in a scenario export + re-import

**Comment by stefanorosanelli** [comment]
_tree.sections.status_ removed from export
closing
