### ISSUE TITLE
FrontendController::getPath causes 404 when an object is ubiquitous with a section `off`

### ISSUE THREAD

**Issue by edoardocavazza** [bedita/bedita#690]
If an object `X` is ubiquitous with sections `A` and `B`, and section `B` is `off` and child of `A`, trying to load section `A` returns a `BeditaNotFoundException`, because when `FrontendController::loadSectionObjects` set the canonical path of `X`, the method `FrontendController::getPath` tries to load `B`. The object `X` has two values in the `parent` field (one for `A` and one for `B`), instead it should have only `A` (it should exclude `off` sections and `draft`s if `$conf['draft'] == false`)

**Comment by edoardocavazza** [comment]
This is also the cause of #689

**Comment by stefanorosanelli** [comment]
Looks really like #281 - that should be fixed...
@batopa ??

**Comment by batopa** [comment]
It seems the same... I'll try to reproduce again follow the steps specified from @edoardocavazza

**Comment by batopa** [comment]
The issue was in `FrontendController::getPath()` as said by @edoardocavazza 
Trying to get the first row on trees the status of parent wasn't checked. I added a join to filter away parents in wrong status

``` php
'joins' => array(
    array(
        'table' => 'objects',
        'alias' => 'ParentObject',
        'type' => 'INNER',
        'conditions' => array(
            'ParentObject.id = Tree.parent_id',
            'ParentObject.status' => $this->getStatus()
        )
    )
)
```

Now it should be fine.

**Comment by edoardocavazza** [comment]
seems ok now. closing...
