### ISSUE TITLE
API: base url should show the available endpoints

### ISSUE THREAD

**Issue by batopa** [bedita/bedita#691]
Now calling API base url the response

``` json
{"message": "hello world"}
```

is shown.

The default should be a page with the list of available endpoints

``` json
{
    "auth": "https://api.url/v1/auth",
    "objects": "https://api.url/v1/objects",
   ...
}
```

This default should be overridable in frontend `ApiController`

**Comment by stefanorosanelli** [comment]
introduced `baseUrlResponse()` method, to override for customization in frontend (if necessary)
