### ISSUE TITLE
Invalidate CSS and JS reference browser caches after update in frontends

### ISSUE THREAD

**Issue by edoardocavazza** [bedita/bedita#692]
We should be able to add an unique code to our css and js references in order to invalidate browser caches.
## First proposal: use git!

**Production sample**
1. complete a milestone
2. create a git tag for the current status
3. all `{$behtml->css('abc')}` and `{$behtml->script('def')}` should report the git tag as GET param

**Staging sample**
1. complete a task
2. commit and push your changes
3. all `{$behtml->css('abc')}` and `{$behtml->script('def')}` should report the commit hash as GET param
## Second proposal: use conf

**Sample**
1. make some changes
2. update your app version conf
3. all `{$behtml->css('abc', $appConfKey)}` and `{$behtml->script('def', $appConfKey)}` should report the version number as GET param

What do you think about?
@fquffio @batopa @stefanorosanelli @qwerg

**Comment by fquffio** [comment]
In regard to the first proposal, we might use `git describe` when debug is on, and `git describe --abbrev=0` when it is turned off.

We might also consider using each resource's last modification time (with [`filemtime()`](http://php.net/filemtime)) which is probably faster than querying git.

**Comment by stefanorosanelli** [comment]
@edoardocavazza @fquffio still necessary? move to BE4?

**Comment by fquffio** [comment]
Already solved in #1039.
