### ISSUE TITLE
Additional caching in controller actions

### ISSUE THREAD

**Issue by fquffio** [bedita/bedita#694]
We could try to replicate [this feature](http://api.cakephp.org/3.0/class-Cake.Cache.Cache.html#_remember) from CakePHP 3 in BEdita controllers as well.

We might consider adding a function `remember` to our `AppController` to make it easier to cache data that is difficult or complex to obtain and that is unlikely to change very often.
We could then write something like this, without the `loadSectionsTree` being evaluated on every page view:

``` php
$frontendAreaId = Configure::read('frontendAreaId');
$additionalConf = array('duration' => '+10 minutes');
$fullTree = $this->remember('full_tree', function() use ($frontendAreaId) {
    // CAREFUL! `$this` can be used within anonymous functions as of PHP 5.4.0.
    // With 5.3.0 <= PHP < 5.4.0 a small workaround is needed.
    return $this->loadSectionsTree($frontendAreaId, true, array(), 999);
}, 'my_conf_key', $additionalConf);
```

This cache wouldn't be so "specific" as the currently available objects cache, and would still allow a little data elaboration, that would be impossible with an html cache.

To help invalidate cached values, we might make use of the callbacks system implemented in #470. For instance, we could attach a listener to save events that clears cache based on the entity being saved. This might be implemented using currently available system, but this would require creating a different behavior for each object type, or we could rather try to extend the available functionalities to Components as well as Behaviors, and then triggering a custom event on `AppController::saveObject()`, that would then be caught and processed by a proper custom component.

@edoardocavazza @qwerg @batopa @stefanorosanelli Ideas? Critics? Things that surely ain't gonna work in what I wrote down? :smile:

**Comment by batopa** [comment]
The idea is good for me. Maybe I would put `remember` function in another class (libs?) to easily reuse in other parts of apps (shells, models, ...).

I have to think about cache deleting, it seems a bit complicated. How to know what caches are to invalidate? For example, you could have a 'partial_tree' cache that contains only some object types and saving an 'event' object you should know if that cache is to invalidate.

**Comment by fquffio** [comment]
@batopa That's why custom callbacks on backend operations come in handy: we don't have to think of a general way to invalidate cache hence the callback itself could take care of cleaning specific cache entries (or cleaning anything at all) basing on the entity being saved. Of course, the easy way would be invalidating the whole cache on every operation, but it would be highly inefficient. And of course, the more complicated is to retrieve the data to be cached, the more complicated is to decide whether that cache item is to be cleared or not on each entity saving, but honestly I can't see an easy way out of this problem.

**Comment by batopa** [comment]
@fquffio if I understand you mean that for every frontend we could setup some custom callbacks to invalidate cache.

But in a frontend I could do 

``` php
$data = $this->remember('my-custom-cache', ....);
```

where I save some data of many object types that I don't know, they could be documents, events, but I don't have any information on which objects are cached.

So how can I know that saving a document I should invalidate that cache. That document could be there or not and I can only know it reading the cache.

Am I missing the point? :smile:

**Comment by fquffio** [comment]
@batopa That's more or less what I meant: we might need an improvement to the callback system to allow attaching a callback to every object type at once, but then it's up to you to know how cache is built in your specific case within the closure passed to `remember()`. If cached items happen to be too much "random", you'll probably want either to clear whole cache on every object save, or to use a different caching system, or use no cache at all. :smile:

For example, if I want to read all Objects placed within a Section or its descendants, i would write something like this:

``` php
$sectionId = 123;
$events = $this->remember('objects-in-section-' . $sectionId, function() use ($sectionId) {
    return $this->loadSectionsTree($sectionId, true);
});
```

Then, on every saved object, if that object is or was placed within the section 123, I would invalidate the cache with key `objects-in-section-123`. Hence `remember()` is a very "abstract" method, I'm afraid we can hardly expect to make cache invalidation much less abstract. :neutral_face:
