### ISSUE TITLE
API: handling pagination

### ISSUE THREAD

**Issue by batopa** [bedita/bedita#702]
API lacks pagination handling. We already explose pagination data as

``` json
"paging": {
    "page": 1,
    "total_pages": 2,
    "total": 15,
    "limit": 10
}
```

We should handle page to load, for example page 2 should be callable with `/objects/1/children?page=2` and limit with `/objects/1/children?limit=30`. Moreover in #685 we should define a max limit.

**Comment by stefanorosanelli** [comment]
Ok, I would use:
- "page_size" instead of "limit"
- add "page_count" as a size of current page

**Comment by batopa** [comment]
Added "page_count" and renamed "limit" to "page_size".

Calling endpoints with `page` and/or `page_size` as query  url params fills `ApiBaseController::paginationOptions` with the right value. That array is used as `$option` calling `FrontendController::loadSectionObjects()` paginating the results.

`page_size` is mapped in `dim` that is used by `FrontendController::loadSectionObjects()`.

**Comment by stefanorosanelli** [comment]
Seems ok - create documentation

**Comment by batopa** [comment]
Documented [here](https://github.com/bedita/bedita/wiki/REST-API:-pagination)
