### ISSUE TITLE
API: fix /objects/:id/children and add /object/:id/contents and /objects/:id/sections

### ISSUE THREAD

**Issue by batopa** [bedita/bedita#704]
Now requesting children of an object (section or publication) with `/objects/:id/children`  the response return only the childContents.

We need:
- [x] `/objects/:id/children` has to return all children (sections and contents) mixed
- [x] `/objects/:id/contents` has to return only children contents
- [x] `/objects/:id/sections` has to return only children sections

**Comment by batopa** [comment]
I have added more flexibility to second param in `/objects` endpoint (example `/objects/1/children`). 

That second param (`children`) is validate against `ApiBaseController::allowedObjectsFilter` defined as

``` php
protected $allowedObjectsFilter = array(
        'children',
        'contents',
        'sections',
        'descendants',
        'siblings',
        //'ancestors',
        //'parents'
    );
```

So you can easily limit or add new filter types. 

For example in `ApiController` you can override:

``` php
protected $allowedObjectsFilter = array(
        'children',
        'custom_filter'
    );
```

to make only valid `/objects/1/children` and `/objects/1/custom_filter`.
Then you have to add the method (build as 'load' plus the camelize version of 'custom_filter')

``` php
protected function loadCustomFilter($id) {
    // code here
}
```

to output the response of new filter type.

**Comment by stefanorosanelli** [comment]
seems ok, moved to Doc before closing
