### ISSUE TITLE
beEmbedMedia cannot make thumbs of big images

### ISSUE THREAD

**Issue by rzecchini** [bedita/bedita#707]
beEmbedMedia should not try to make thumbs of huge images otherwise the server crashes

**Comment by fquffio** [comment]
Even if large images are the ones on which we are supposed to perform resizing, in some extreme cases this might lead PHP to overreach its memory limit. In such cases we might delegate the developer not to deliver such big files to the user unless they explicitly asked to.

Added new optional configuration key:

``` php
/**
 * File size limit (in bytes). If an image exceeds this limit, thumbnail won't be generated,
 * and the script won't even try to open the file, cowardly avoiding memory issues.
 * If set to `null`, no file size limit will be enforced.
 *
 * @var int|null
 */
$config['imgFilesizeLimit'] = 1024 * 1024 * 16;  // Default value: 16 MB
```

**Comment by batopa** [comment]
I think that the file size limit should be only used if imagemagick is disabled and PHP GD library is used to create thumbnails. 

If imagemagick is enabled the conversion is delegated to shell launching `convert` through `exec()` function.

**Comment by fquffio** [comment]
I believed that the memory leak occurred with `getimagesize`, which occurs in any case, but I was wrong. I'll fix that ASAP.

**Comment by stefanorosanelli** [comment]
backend user should be alerted (warning message) if image is too big to generate thumbnails - after first upload and on every view

**Comment by stefanorosanelli** [comment]
Log added in `be_thumb` and user warn message added in multimedia view on too big images
Closing
