### ISSUE TITLE
new addons structure

### ISSUE THREAD

**Issue by stefanorosanelli** [bedita/bedita#717]
We need to change current **addons** structure and layout in order to use separate modules and git repos.

Addons should stay in **modules** folder like other BE plugins, but they don't have a backend interface.
We should be able to:
- enable / disable those addons modules in backend admin and via shell
- update (git pull) through shell deploy script and admin ui

How do we distinguish _addons_ modules from _standard_ modules ?
Through _config / bedita_module_setup.php_ ??

**Comment by stefanorosanelli** [comment]
@batopa any suggestions are appreciated

**Comment by fquffio** [comment]
Maybe plugins are just like modules, except they don't have a controller, hence no available backend interface.

**Comment by stefanorosanelli** [comment]
Current situation: putting and addon module in modules folder has this effect:
- shell scripts are working and may be called
- models and behaviors are not enabled

**Comment by stefanorosanelli** [comment]
Introduced a new module type **addon**
We will have 3 module types: **core**, **plugin**, **addon**
**addon** modules will not have a backend UI

Presence of _config/bedita_module_setup.php_ is mandatory - for addons modules we have to declare

```
    'type' => 'addon', 
```

default value is  **plugin**

@batopa @fquffio can you test on _issue/717-addons-modules_ branch?

**Comment by stefanorosanelli** [comment]
Admin Menu change proposal:
- remove **Addons** entry (or change to _deprecated_? how?)
- rename **Plugin Modules** to **Extension Modules** - plugins and addons
- remove **Update addons**  (or change to _deprecated_?)

**Comment by fquffio** [comment]
I'll perform some tests soon. :wink:

I can't see any benefit in deprecating a backend controller method instead of directly removing it, especially if it's something so "core" as the Admin module. It's not something that might introduce issues unless one has hacked the core, as far as I can tell. :confused:

**Comment by stefanorosanelli** [comment]
Removed **Addons** and **Update addons** entries in admin module.
**Plugin Modules** entry unchanged (i think it's fine to leave it)

Future enhancements:
- view pluging details: models, behaviors, scripts... introduced by plugin, configuration info...
- visually distinguish _addons_ and _plugins_
