### ISSUE TITLE
Related objects' title and description emptied if not provided

### ISSUE THREAD

**Issue by fquffio** [bedita/bedita#722]
At the present state, when saving an object's related objects we are able to update their title and description.
With some relation types, we might want to give the user the chance to edit just one of them. When doing so, the other one happens to be emptied because the "default value" for a missing value is an empty string. In brief, if we don't provide a field to edit or persist the description, the description will be lost.

@stefanorosanelli @batopa Is this intentional?

**Comment by batopa** [comment]
I think it should be that if title/description is not set do nothing while if they are set use their values.

**Comment by didoda** [comment]
Test ok (tested with a questionnaire + questions)
