### ISSUE TITLE
Callback system improvements

### ISSUE THREAD

**Issue by fquffio** [bedita/bedita#723]
We need a way to simply attach a callback behavior to multiple object types without replicating it over and over.

In a bit simpler scenario, we might want to attach a callback behavior to _all_ object types, present and future, core or plugin. Using the naming convention introduced in #470 i would expect `BEObjectSthCallbackBehavior` to do the job, but this doesn't work so far.

@stefanorosanelli @batopa we could introduce this as a further artificial measure, couldn't we?

**Comment by batopa** [comment]
Yes, it is a common scenario. It would be nice if `BEObjectSthCallbackBehavior` could define inside of it on which objects to work. For example I might need a behavior that works on `Video`, `Image` but not on `Audio`. Default all objects.

**Comment by batopa** [comment]
Yes, it is a common scenario. It would be nice if `BEObjectSthCallbackBehavior` could define inside of it on which objects to work. For example I might need a behavior that works on `Video`, `Image` but not on `Audio`. Default all objects.

**Comment by fquffio** [comment]
@batopa Fine, i like that, but this would come with some additional overhead as I must actually instantiate the class and go checking for one of its properties. In that case, couldn't we just delegate to the developer to make the behavior void in case the object type isn't in the list? There would be still overhead, but it would make easier to handle both whitelisting (just `Video` and `Image`) and blacklisting (everything but `Document`).

I'm talking of something like this:

``` php
class BEObjectJustVisualBehavior {
    public function beforeSave($model) {
        if (!in_array($model->name, array('Video', 'Image'))) {
            return true;
        }
        // do the magic.
        return false;
    }
}
```

**Comment by batopa** [comment]
@fquffio :+1:  for me it's ok!
