### ISSUE TITLE
frontends: introduce paths.php to define/override app paths

### ISSUE THREAD

**Issue by stefanorosanelli** [bedita/bedita#725]
instead of using **webroot/index.php** (from .sample file) to define _CAKE_CORE_INCLUDE_PATH_ and _BEDITA_CORE_PATH_ introduce a new **paths.php** file to set those constants and also other useful constants like CSS_URL and JS_URL

**Comment by edoardocavazza** [comment]
I migrated all boilerplate frontends!

Here the migration guide:
https://github.com/bedita/bedita/wiki/Migrate-a-frontend-to-new-structure-with-paths.php

**Comment by stefanorosanelli** [comment]
seems ok, only problem: if **config/paths.php** is missing we have to look at apache log files to find out - user gets a blank page and bedita log files are empty...

**Comment by stefanorosanelli** [comment]
modified shell script:

```
./cake.sh bedita checkApp
```

if in a frontend app we have  **config/paths.php.sample** but **config/paths.php** is missing we create a copy
