### ISSUE TITLE
BEdita error page not showing on missing module

### ISSUE THREAD

**Issue by fquffio** [bedita/bedita#727]
If a required BEdita module or addon is not found (for instance when importing an existing database to a new instance), the instruction `BeLib::getObject('BeConfigure')->initConfig()` at the beginning of `app_controller.php` fails, resulting in class `AppController` being unavailable even to show an error page. It results in a blank page and an Apache error log:

```
[Tue Jul 14 12:18:43.187502 2015] [:error] [pid 1512] [client 192.168.56.1:51492] PHP Fatal error: Class 'AppController' not found in /var/www/bedita/cake/libs/error.php on line 32
```

As suggested by @batopa, we might delay the call to `BEConfigure::initConfig()` until `AppController` is actually instantiated to avoid the issue, as the class itself would be available anyway. @stefanorosanelli ?

**Comment by fquffio** [comment]
Ok, I'll take this silence as a "go, no problem with that". :smile:

**Comment by stefanorosanelli** [comment]
Seems ok, but how can we reproduce the problem?
For example on an istance that does'nt have this fix?

**Comment by fquffio** [comment]
@stefanorosanelli It should be enough to create a fake `ObjectType` (`foo`, for instance) without providing an actual CakePHP Model. Doing so, the framework would be looking for a non-existing table named `foos` and would trigger the error that caused the blank page.

**Comment by didoda** [comment]
My test: I added a model Foo in $uses of DocumentsController; loading the page, I see an Error 500 (Internal server error) page. In error.log:

```
2015-08-21 15:28:30 Error:  500 Internal Error - missingTable: array (
  'url' => 'http://localhost/workspace/bedita/bedita-app/documents',
  'code' => '500',
  'model' => 'Foo',
  'table' => 'foos',
  'title' => 'Missing Database Table',
  'BEAuthUser' =>
  array (
    'id' => '1',
    'userid' => 'cw',
    'realname' => 'ChannelWeb',
    'passwd' => ***,
    'email' => NULL,
    'valid' => '1',
    'last_login' => '2015-08-21 15:28:28',
    'last_login_err' => '2013-08-08 17:33:55',
    'num_login_err' => 0,
    'created' => NULL,
    'modified' => '2015-05-21 11:55:57',
    'user_level' => '0',
    'auth_type' => 'bedita',
    'auth_params' =>
    array (
      'userid' => '',
    ),
    'lang' => NULL,
    'time_zone' => NULL,
    'comments' => NULL,
    'notes' => NULL,
    'notify_changes' => NULL,
    'reports' => NULL,
    'groups' =>
    array (
      0 => 'administrator',
      1 => 'editor',
      2 => 'reader',
    ),
  ),
)
```

Error handled as expected.
