### ISSUE TITLE
When the mail sending fails, the status remains on pending instead of failed

### ISSUE THREAD

**Issue by alejanmat** [bedita/bedita#729]
If the sending of mail fails, the status of mail job remains pending instead of failed without a log message.
The log must be more clear and the status of the mail job must be failed

**Comment by stefanorosanelli** [comment]
This happens in case of bad message data: an exception is thrown and the message remains in "pending" status

**Comment by stefanorosanelli** [comment]
seems fixed @alejanmat can you close it?
