### ISSUE TITLE
Accessible Export Import commands

### ISSUE THREAD

**Issue by qwerg** [bedita/bedita#730]
All the logic in #283 must be placed in UI accessible methods, not only shell.
Also methods are not exposed! How can a user know in shell wich exportFilter are available? bho
#577 / epub3 import export need same logic.

We can: 
- use the import page described in #641, but maintaining the export button in section tab: instead of a modal window the user will go in the import page passing some parameters (current section)
- maintain the actual modal window

**Comment by stefanorosanelli** [comment]
For Export UI see #663

As for Import UI I prefer using current page with section id passed as parameter and drop modal window - @xho ?

Shell commands: we don't have a method to list of import/export filters with its parameters, could be useful - create an issue for that

**Comment by stefanorosanelli** [comment]
created #777 for shell commands
closing - import/export handled in other issues, system will be reviewed in BE4
