### ISSUE TITLE
Tab order in object view are different in each module

### ISSUE THREAD

**Issue by xho** [bedita/bedita#742]
The list of form tabs differs between modules. I.e. the "preview" tab is the last one in documents and the second in events. There should be a uniform approach, so kind of decision should be made on tab priority / importance and which should go first.
I would also prefer to visually group together "tabs of the same kind", i.e.

main tabs (title, prop, position, text)
[space]
relations tabs (multimedia, webmarks…)
[space]
advanced tabs

**Comment by stefanorosanelli** [comment]
Agree, same tabs in different modules should normally follow same order.

We could also group common tabs in single elements, easier to reuse

**Comment by xho** [comment]
Too difficult to solve globally in BE3, we'll plan things better in BE4. Closing.
