### ISSUE TITLE
API: introduce search and type filter in /objects endpoint

### ISSUE THREAD

**Issue by stefanorosanelli** [bedita/bedita#744]
Introduce 2 filters in /objects method:
- **object_type**: list of object types to show
- **query**: perform text search

**Comment by batopa** [comment]
To easily discern filter params from others I suggest to use `filter` parameter as basis for any objects filtering strategy.

For example, the following is a request for perform a full text search of _test_ word limited to _document_ and _event_ objects

`GET /objects?filter[query]=test&filter[object_type]=document,events`
