### ISSUE TITLE
BEdita web wizard setup creates core.php with errors

### ISSUE THREAD

**Issue by xho** [bedita/bedita#747]
Using web based setup, the file core.php created has problems in unclosed or wrong formatted comments near url rewrite options.

For example, after choosing mod_rewrite enabled:

```
 * And uncomment the App.baseUrl below:
 */
// Configure::write('App.baseUrl', env('SCRIPT_NAME')); *
 * The value of the define determines the names of the routes
 * and their associated controller actions:
[........]
 *
 * [Note Routing.admin is deprecated in 1.3.  Use Routing.prefixes instead]
 */
```

The comment is not opened after the Configure line, also there is not a new line.
So this configuration throws errors.

**Comment by didoda** [comment]
I tried to create core.php through web based setup and I succeeded (no errors and core.php is fine).
I wonder whether is a php version related problem (my php version is 5.6.4-4).
In the error case, it's like applymodrewrite writes inside core.php file 3 lines after the right position/line.

mod_rewrite is set in setup.php:applymodrewrite function:

```
private function _applymodrewrite($enable = "enabled") {
            $filename = ROOT . DS . APP_DIR . DS . "config" . DS . "core.php";
            $c = 1;
            $done = false;
            $filedata = array();
            $filearr = file($filename);
            $line_start = 0;
            foreach($filearr as $line_num => $line) {
                if(($line_start == 0) && (stripos($line,"Configure::write('App.baseUrl'") !== false) ) {
                    $line_start = $line_num;
                }
                if($line_start > 0 && !$done) {
                    $line_end = $line_num;
                    $line_start = -1;
                    $done = true;
                    $filedata[]= ($enable == "enabled") ? "// Configure::write('App.baseUrl', env('SCRIPT_NAME'));" : "Configure::write('App.baseUrl', env('SCRIPT_NAME'));";
                    $done = true;
                } else {
                    $filedata[]=$line;
                }
            }
            return (file_put_contents($filename,$filedata) !== FALSE);
        }
```

Except for "$done = true;" repeated 2 times, I don't see anything wrong. I guess that stripos has different behaviour on xho's environment, for some reason.

**Comment by didoda** [comment]
I tried in test.bedita.com... no error. We could skip the problem, assuming mod_rewrite enabled as prerequisite (then getting rid of _applymodrewrite call).

**Comment by stefanorosanelli** [comment]
Yes, better skip _core.php_ manipulation, we may assume mod_rewrite enabled as prerequisite
