### ISSUE TITLE
API: improve ISO-8601 support on date format

### ISSUE THREAD

**Issue by batopa** [bedita/bedita#749]
Using `DateTime::ISO8601` to format date produces results as 2005-08-15T15:52:01+0200 but reading the [PHP documentation](http://php.net/manual/en/class.datetime.php#datetime.constants.iso8601) it says

> This format is not compatible with ISO-8601, but is left this way for backward compatibility reasons. Use DateTime::ATOM or DATE_ATOM for compatibility with ISO-8601 instead.

Moreover in some iOS version the creation of `Date` object using  +0200 format thrown errors.
So our default date format should be 2005-08-15T15:52:01+02:00 obtained using `DateTime::ATOM` format.

Furthermore in write operations we should accept also the standard format of **javascript** `Date().toISOString()` i.e. 2015-09-25T12:25:16.259Z

**Comment by edoardocavazza** [comment]
Working now. Thank you!
