### ISSUE TITLE
[API] protected fields when saving an object

### ISSUE THREAD

**Issue by edoardocavazza** [bedita/bedita#750]
Right now, if you know the proper property name, a POST request can update all object's fields.

By default, some fields should be protected (maybe at core level):
- `created`
- `created_by`
- `modified`
- `modified_by`
- `ip_created`
- others?

Moreover, we should introduce a protection for the fields which are not passed to the client through the GET request: if some fields are private and hide, POST requests should not be able to update that.

**Comment by stefanorosanelli** [comment]
I think it's not just an API issue, but more general - also saving a $data array directly in PHP you should not be able to change those fields 
[but maybe we used this _feature_ in some shell script, we have to check....]

**Comment by edoardocavazza** [comment]
I agree. Maybe we could set a protection level using the authentication:
- administrators can update protected fields
- developers/managers/editors/... can not

**Comment by batopa** [comment]
Anyway for API we should permit to save only fields served from `GET /objects:id` (obviously excluded protected fields).
If my API is configured to just show the object `title` the call `POST /objects` should permits to save only that field. 

Maybe we could use a cache to save the fields returned by response (divided by object type) to know which fields can be passed to `POST /objects` request, but how do we invalidate the cache if conf was changed? By hand? Caching and checking `$config['api']['formatting']` at every `GET /objects` request?

**Comment by stefanorosanelli** [comment]
Cake3 supports _accessible_ fields, problem solved :)
