### ISSUE TITLE
Exception logging: separate log files, default and custom config

### ISSUE THREAD

**Issue by didoda** [bedita/bedita#754]
When a BeditaException is thrown, system logs to 'error.log'.
It's not correct.
When a BeditaException is thrown, system should:
1. log to a specified file (i.e. debug.log, http_responses.log, filesystem.log, database.log, ...) [default file chosen by semantic of exception]
2. not log at all (i.e. http status codes 401, 404, ...)

Developers should have the possibility to force an exception to log to a specified file, different from default.
In some circumstances, logging organisation should be customisable (custom configuration overrides defaults).

**Comment by didoda** [comment]
I imagine file logging separation by exception, like:

```
$logFiles = array(
    'BeditaAjaxException' => NULL,
    'BeditaAllowURLException' => 'http_response',
    'BeditaBadRequestException' => 'http_response',
    'BeditaConflictException' => NULL,
    'BeditaDeleteStreamObjException' => NULL,
    'BeditaFileExistException' => 'filesystem',
    'BeditaForbiddenException' => 'http_response',
    'BeditaFrontAccessException' => 'http_response',
    'BeditaHashException' => NULL,
    'BeditaInfoException' => NULL,
    'BeditaInternalErrorException' => 'error',
    'BeditaIOException' => 'filesystem',
    'BeditaMailException' => 'mail',
    'BeditaMediaProviderException' => NULL,
    'BeditaMethodNotAllowedException' => NULL,
    'BeditaMIMEException' => 'file',
    'BeditaNotFoundException' => 'http_response',
    'BeditaNotImplementedException' => 'http_response',
    'BeditaPublicationException' => NULL,
    'BeditaRuntimeException' => 'error',
    'BeditaSaveStreamObjException' => NULL,
    'BeditaServiceUnavailableException' => 'http_response',
    'BeditaUnauthorizedException' => 'http_response',
    'BeditaUploadPHPException' => 'filesystem',
    'BeditaURLException' => 'http_response'
);
```

Custom config could override it. For instance:

```
$config['exceptions.logFiles'] = array(
    'BeditaAllowURLException' => NULL, // disable logging for this exception
    'BeditaUnauthorizedException' => 'auth'
);
```

**Comment by stefanorosanelli** [comment]
I would keep solution to this as simple as possible
Goal of this issue is: try to follow logging guidelines https://github.com/bedita/bedita/wiki/Logging-conventions
I'd say: all exceptions should be logged, some are always **errors**, some not, some could be **info/debug**
That said I don't know if there's a simple solution - see also #538 and #570

**Comment by didoda** [comment]
Solution is not complicated, but it requires an important refactor (at least in `bedita-app/app_controller.php`, `bedita-app/app_error.php`, `bedita-app/bedita_exception.php`) and releasing it would be dangerous, because exceptions are used everywhere in frontends, it's not possible testing all around. Maybe we could just keep in mind how to better logging system in next BEdita version (4).

**Comment by stefanorosanelli** [comment]
Agree, let's move it to BEdita4 - we'll see then, depending on how exception handling and logging will be implemented

**Comment by fquffio** [comment]
This is already possible in CakePHP 3 by simply configuring logger. Still valid?

**Comment by stefanorosanelli** [comment]
That's right, we probably need some examples on how to do that.
Closing.
