### ISSUE TITLE
Alt field for multimedia items

### ISSUE THREAD

**Issue by rzecchini** [bedita/bedita#756]
Multimedia items should have an "alternative text" field, representing the information to display when a img is missing.

**Comment by stefanorosanelli** [comment]
Agree, normally we use some combination of _title_ and _description_ but a separate field may be more appropriate
@xho, @qwerg any thoughts?

**Comment by xho** [comment]
Agree that are semantically different things: title is for – ehm – title,
while alt stands for “alternative text”, that the browser should use when the
image is not shown, for various reasons, or by screen readers.
Actually often in terms of content they fit together, but not always.

At the same time I have to say I fear the multiplication of unused fields
in content management…

On 28 October 2015 at 11:39, Stefano Rosanelli notifications@github.com
wrote:

> Agree, normally we use some combination of _title_ and _description_ but
> a separate field may be more appropriate
> @xho https://github.com/xho, @qwerg https://github.com/qwerg any
> thoughts?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/bedita/bedita/issues/756#issuecomment-151796269.

## 

#  x][o

**Comment by edoardocavazza** [comment]
I would like to add that "alternative text" could be an useful field in terms of search in the database.

**Comment by xho** [comment]
Consider also that the alt attribute is not available and valid everywhere.
I.e. in <figure> and <svg> (the latter has got a desc element inside, <desc>Stuff</desc>), but also (strangely) it has not been defined for <video> and <audio> tags. And so on: in Multimedia module we manage several different kinds of file types.

So, speaking of user interface and trying to limit the caos in CM, I think that it should only be available where it is meaningful.

**Comment by stefanorosanelli** [comment]
Obsolete, closing
