### ISSUE TITLE
[API] "Error: object type not found" when `frontendAreaId` object does not exists

### ISSUE THREAD

**Issue by edoardocavazza** [bedita/bedita#757]
Every request to an API Frontend gets the response:

``` json
{
    "error": {
        "status": 500,
        "code": null,
        "message": "Error: object type not found",
        "details": "Error: object type not found",
        "more_info": null,
        "url": "..."
    }
}
```

if `$config['frontendAreaId']` points to an area which does not exist.

**Comment by batopa** [comment]
Which error should we trigger?

If `frontendAreaId` is missing it should be a blocking error on server (wrong configuration). I will throw a 500 error with a specific message as "Missing or wrong publication in configuration".

@edoardocavazza @stefanorosanelli do you think it's correct?

**Comment by stefanorosanelli** [comment]
:+1:

**Comment by edoardocavazza** [comment]
:+1:

**Comment by edoardocavazza** [comment]
Great it works! Closing...
