### ISSUE TITLE
Make CKEditor auto correct smart-quotes (double and single)

### ISSUE THREAD

**Issue by rzecchini** [bedita/bedita#758]
CKEditor should behave like most of the other editors and autocorrect dumb quotes to smart ones (see img attached). I suggest a plugin that implement this feature on quotes and other typographic characters: https://github.com/danyaPostfactum/ckeditor-autocorrect-plugin

![smart-quotes](https://cloud.githubusercontent.com/assets/2392233/10692977/6e2fae90-7995-11e5-9a32-748d3ff0d736.gif)

**Comment by xho** [comment]
I don't know, I don't agree with autocorrect quotes by default, as
autocorrect may result annoying in many contexts. I would prefer a
configurable option for the editor, with more eventually (such a place
where tu turn on advanced editor's features).

C_

On 23 October 2015 at 14:52, rzecchini notifications@github.com wrote:

> CKEditor should behave like most of the other editors and autocorrect dumb
> quotes to smart ones (see img attached). I suggest a plugin that implement
> this feature on quotes and other typographic characters:
> https://github.com/danyaPostfactum/ckeditor-autocorrect-plugin
> 
> [image: smart-quotes]
> https://cloud.githubusercontent.com/assets/2392233/10692977/6e2fae90-7995-11e5-9a32-748d3ff0d736.gif
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/bedita/bedita/issues/758.

## 

#  x][o

**Comment by rzecchini** [comment]
Great. What we need is the ability to toggle ON this feature in some
context like news & institutional websites where no writer pay attention to
which type of quote they are entering.
A configurable option seems fine.

2015-10-23 15:07 GMT+02:00 xho notifications@github.com:

> I don't know, I don't agree with autocorrect quotes by default, as
> autocorrect may result annoying in many contexts. I would prefer a
> configurable option for the editor, with more eventually (such a place
> where tu turn on advanced editor's features).
> 
> C_
>

**Comment by batopa** [comment]
Uhm... I'm not sure that "autocorrect" should be enabled by default

**Comment by rzecchini** [comment]
@edoardocavazza it seems that the autocorrect plugin isn't enabled within the description field
<img width="681" alt="schermata 2016-04-08 alle 12 39 01" src="https://cloud.githubusercontent.com/assets/2392233/14381543/5a680882-fd87-11e5-9bee-c6b1338e45cc.png">
(as you see the text inside descriptions keeps wrong quotes)
