### ISSUE TITLE
[API] endpoint for publication id

### ISSUE THREAD

**Issue by edoardocavazza** [bedita/bedita#759]
Provide an endpoint which retrieves the current `$config[frontendAreaId]` value, or, maybe better, the nickname of the publication.

**Comment by batopa** [comment]
@edoardocavazza maybe it could be return the publication as `GET /objects/:id`?

**Comment by edoardocavazza** [comment]
:+1:

**Comment by stefanorosanelli** [comment]
in **BE4** we should have a `/publications` endpoint listing all available publications

**Comment by edoardocavazza** [comment]
If the API frontend can interact with more than a publication, we can close this specific issue. 

Can we suppose that the developer already knows the nicknames of the publications? If so, he/she could use the current `GET /objects/:nick` to retrieve the publication he/she needs.

**Comment by stefanorosanelli** [comment]
in BE4 we will no more have _1 API frontend / 1 publication_ but a native API for all data - we then may use permissions and/or api keys to isolate single publications,

Developer should know only API URL & API KEYS, endpoint to get available roots / publication may be useful

**Comment by batopa** [comment]
> If the API frontend can interact with more than a publication, we can close this specific issue.

Not now. Maybe we could handle the "current" publication as query string parameter.
For example:

``` http
GET /objects/:id
```

to search object _:id_ in default frontend publication (`$congfig['frontendAreaId']`) as it happens now.

``` http
GET /objects/:id?publication=id_pub
```

to search object _:id_ in specific _id_pub_ publication.

Adding a check on that parameter in `ApiBaseController::beforeCheckLogin()` and overriding the default frontend publication `$config['frontendAreaId']` with the new one should solve the issue.

At that point the request

``` http
GET /publications
```

Should be return the list of all the publications available to the user. The default `$config['frontendAreaId']` publication could be flagged with a special key like `default` or similar.

Obviously the developer has to know on which publication he needs to work.

**Comment by stefanorosanelli** [comment]
Native multipublication API will be available in BE4, if we don't need it now, we may skip this step
Instead of implementing a new endpoint what about using something like

``` http
GET /objects/filter[object_type]=area
```

now response is empty, probably because there is no publication inside API publication
we could also implement a new filter for that

**Comment by batopa** [comment]
The response is empty because `GET /objects?filter[object_type]=area` search 'area' object type in default publication's descendants.

Maybe at this point it makes sense that the developer has to know the publication id or nickname.

**Comment by batopa** [comment]
obsolete
