### ISSUE TITLE
[API] enable status update if staging mode

### ISSUE THREAD

**Issue by edoardocavazza** [bedita/bedita#760]
if frontend `$config['staging']` is `true`, the POST update request should be able to update `status` field.

**Comment by stefanorosanelli** [comment]
Now if we create an object via API `status` field is always `on`. Maybe this should be configurable (globally or per object type).

But I think we should always be able to set `status` via POST, also not in `staging` environment, but always.
If we don't set `status` field an API default logic should do it

**Comment by batopa** [comment]
obsolete
