### ISSUE TITLE
[API] add filter by object ids getting a collection of objects

### ISSUE THREAD

**Issue by batopa** [bedita/bedita#765]
We need to add a filter to get a collection of objects by id.
For example

~~GET /objects?filter[id]=1,2,3~~

``` http
GET /objects?id=1,2,3
```

If some object requested is not reachable the API will respond with an error.
The max number of objects ids requested must is less then `ApiBaseController::paginationOptions['maxPageSize']`

**Comment by batopa** [comment]
Since it is not properly a filter it is better to use `id` and not `filter[id]`

**Comment by stefanorosanelli** [comment]
test ok!
