### ISSUE TITLE
[API] implement a query string to get object relations detail

### ISSUE THREAD

**Issue by batopa** [bedita/bedita#768]
We need an option to get relations detail getting objects. The request has to include the relation name and the number of related objects to get `relation_name|relation_number`. 

For example:

~~/objects?expand[relation_details]=attach|3,seealso|2~~

```
/objects?embed[relations]=attach|3,seealso|2
```

**Comment by batopa** [comment]
The relations  are in 'objects' key of relative 'relations'.

``` json
{
    "relations": {
        "attach": {
            "count": 10,
            "url": "https://example.com/objects/1/relations/attach",
            "objects": [...]
        }
    }
}
```

**Comment by stefanorosanelli** [comment]
test ok, moved to **doc** status
