### ISSUE TITLE
[API] /posters response on image error

### ISSUE THREAD

**Issue by stefanorosanelli** [bedita/bedita#770]
At this moment in case of missing image or other thumbnail related errors we get a response like: 

``` js
{
 api: "posters",
 data: {
  id: 372,
  uri: "http://example.com/img/iconMissingImage_130x85.gif"
 },
 method: "get",
 params: [ ],
 url: "http://example.com/api/posters/372"
}
```

Is this correct?
In this example we may have a filesystem error.
Should we send an error response? Or an empty image?

@xho @qwerg @edoardocavazza

**Comment by stefanorosanelli** [comment]
also a non existent id returns empty response (no error)

``` js
{
api: "posters",
data: [ ],
method: "get",
params: [ ],
url: "http://example.com/api/posters/9999999999"
}
```

**Comment by batopa** [comment]
obsolete
