### ISSUE TITLE
publications: new data export

### ISSUE THREAD

**Issue by stefanorosanelli** [bedita/bedita#771]
Implement part of #663, namely:
- drop current **Export** button from _Publication / Tools_
- add new **Export** block in _Publications_ containing element .tpl similar to the new import page #641 (with dynamic options etc...)

**Comment by stefanorosanelli** [comment]
accidentally closed  in 59def4b
reopening

**Comment by stefanorosanelli** [comment]
Seems ok, but:
- we need it also for sections (publications in issue title is the module name)
- file name in **File:** could be title or nickname of section/publication exported

**Comment by stefanorosanelli** [comment]
Ok
Two more things:
- selecting a radio button filter or pushing _Export_ button the **unsaved object** icon appears in Publications box and confirm window is fired upon page change
- default file name extension: to be set automatically in **File:** input text, filename should be [nickname].[default-extension]

**Comment by didoda** [comment]
default extension is a filter option. for instance:
(from `json_export_filter`)

```
public $options = array(
        'extension' => array(
            'label' => 'Extension',
            'dataType' => 'options', // number|date|text|options
            'values' => array(
                'json' => 'json'
            ),
            'defaultValue' => 'json', //
            'mandatory' => false,
            'multipleChoice' => false,
            'visible' => 'n'
        )
    );
```

(from `xml_export_filter`)

```
public $options = array(
        'extension' => array(
            'label' => 'Extension',
            'dataType' => 'options', // number|date|text|options
            'values' => array(
                'xml' => 'xml'
            ),
            'defaultValue' => 'xml', //
            'mandatory' => false,
            'multipleChoice' => false,
            'visible' => 'n'
        )
    );
```

Parameter 'visible' can be used to show filter option in view

**Comment by didoda** [comment]
Let's use a better solution: filter variable `public $defaultExtension` (suggested by @stefanorosanelli).
For example:
(from `json_export_filter`)

```
public $defaultExtension = 'json';
```
