### ISSUE TITLE
shell: deploy script should also be non-interactive

### ISSUE THREAD

**Issue by stefanorosanelli** [bedita/bedita#780]
shelll script 

```
./cake.sh deploy up
```

should also be called in a non-interactive way, for instance:
- `./cake.sh deploy up -core` => update BEdita core
- `./cake.sh deploy up -frontend <frontend-name>` => update selected frontend app
- `./cake.sh deploy up -module <module-name>` => update selected module

**Comment by fquffio** [comment]
Implemented several flags:
- `--core`, to update BEdita core
- `--frontend <frontend>`, `--module <module>`, `--addon <addon>` to update frontends, modules and addons respectively

Alternatively, flags `--type` and `--name` can be provided (e.g. `--type core`, or `--type frontend --name bootstrap`).

In case of an error, the command will exit with code 1, while some details about the error will be printed to stderr:

```
$ ./cake.sh deploy up --frontend foobar 2&>1 /dev/null; echo $?
1
```

As a further security measure, in situations where interactive shell is highly undesirable, this command could be piped to `yes q`:

```
$ yes q | ./cake.sh deploy up --myMistypedFlag foobar
```

**Comment by stefanorosanelli** [comment]
Seems ok
Well done
`--addon` is somehow _deprecated_ since addons are modules now, but it's ok

Also for frontends and module names I would keep the original folder name instead of the CamelCase version - `glossary` and not `Glossary` - unless there's a reason to do so

**Comment by fquffio** [comment]
@stefanorosanelli I added the `--addon` even if deprecated to give some consistency across flags. We might remove it and force the use of `--type addon --name <addon>` instead, in cases where it's actually needed.

About the last part, I'm pretty sure this would work with both `--module glossary` and `--module Glossary`, doesn't it?

**Comment by stefanorosanelli** [comment]
Ok, we can leave `--addon`

And yes, it works with both `--module glossary` and `--module Glossary` but I would show `glossary` in items list - simply beacuse it's `glossary` on filesystem...

**Comment by fquffio** [comment]
@stefanorosanelli Fixed that, don't know why I did that. :smile: Added a `--dry-run` parameter, to output the command that would be executed without having to deal with consequences. Updated help.
