### ISSUE TITLE
shell: script to check and repair relations

### ISSUE THREAD

**Issue by stefanorosanelli** [bedita/bedita#783]
Shell script is needed to check `object_relations` table:
- only current **valid** relations should be present
- relations and its inverse correctness

Typical scenario:
- a relation is used
- this relation is changed or deleted
- relations referring to previous definitions still exist

**Comment by didoda** [comment]
Some tips about shell script usage.

List of available relations.

```
./cake.sh relation ls
```

Check data for a specified relation (if issues are found, fix can be launched [y/n]).

```
./cake.sh relation check -name <relation-name>
```

Check data for all relations available (if issues are found, fix can be launched [y/n]).

```
./cake.sh relation check all
```

Fix data for a specified relation.

```
./cake.sh relation fix -name <relation-name>
```

Info about how to use the script.

```
./cake.sh relation help
```
