### ISSUE TITLE
frontends: optimizations in FrontendController::route - avoid useless db queries

### ISSUE THREAD

**Issue by stefanorosanelli** [bedita/bedita#793]
this line in `FrontendController::route` is always called

``` php
$id = (is_numeric($name))? $name : $this->BEObject->getIdFromNickname($name,$this->status);
```

instead it should be called only for **section** and **content** methods

@batopa @fquffio  ?

**Comment by fquffio** [comment]
Honestly, I think that query is required in many scenarios, given the way we handle routes. I see that that `$id` variable is used in several ways within that method, and I couldn't think of a consistent optimization that does not affect severely readability…

**Comment by stefanorosanelli** [comment]
I don't agree, that query should be used only in content and section
otherwise for every URL that doesn't contain id or nicknames lilke `login`, `logout` and all `$config['reservedWords']` that cannot have equal nicknames by design we look for possible object ids

I would call  

``` php
$this->BEObject->getIdFromNickname($name,$this->status);
```

only if no suitable method is found, few lines under, where we have 

``` php
if ($methodName === null....
```

```
```

**Comment by stefanorosanelli** [comment]
frontend controller route proposal
https://gist.github.com/stefanorosanelli/5e60ddd4607de0f8c7f5

**Comment by batopa** [comment]
obsolete
