### ISSUE TITLE
Implement User and ExternalAuth entities

### ISSUE THREAD

**Issue by fquffio** [bedita/bedita#806]
Basing on the schema structure depicted in [`bedita/bedita4-design`](https://github.com/bedita/bedita4-design), implement basic Table and Entity classes (with tests!) for:
- [x] `Users`
- [x] `ExternalAuths`
- [x] `AuthProviders`
### Questions
- Should we plan additional fields for – let's say – multi-factor authentication (which is not an external auth provider, but rather a second layer of security to the user)? Should we place such additional information in a JSON field?

**Comment by stefanorosanelli** [comment]
About multi-factor auth: this JSON data could be included in the JSON `external_auth.auth_params` field? We may use an explicit key like `MFA` inside that field 
We may also introduce a new/dedicated field for that purpose.

**Comment by fquffio** [comment]
Schema changes proposed:
- `auth_providers.name` could be converted to type `VARCHAR`, and it should be unique
- `auth_providers.url` could be converted to `VARCHAR`, too
- `external_auth.auth_params` and `external_auth.auth_username` could be renamed to `external_auth.params` and `external_auth.username` respectively

### MFA

@stefanorosanelli Uhm… I don't think that the `external_auth` table would fit well. MFA is not a parallel authentication method, but rather an additional step in the authentication process.

As long as I can see, a basic MFA setup (using TOTP generated via a Google Authenticator-compatible app) would consist of:
- a field to store the secret token
- a JSON field to store a set of one-time recovery codes (optional, but _very_ recommended)
- a field to store the last code used (necessary to avoid replay attacks)
- _(optional)_ a JSON field to store enabled U2F FIDO tokens (e.g. YubiKeys)
- _(optional)_ a date field to store information about when MFA was enabled

Of course, instead of adding so many fields to the `users` table, all those columns could be serialized into a single JSON field (even if I wouldn't like this solution) or they could be placed into a separate table structured to handle multiple second-factor authentication methods such as OTPs generated by tokens of several kinds, challenge-response authentication or similar. But honestly I wouldn't see this as a priority, while TOTP generated by Google Authenticator could be an interesting addition to be considered from the very beginning of the development process. :smile:

**Comment by stefanorosanelli** [comment]
Schema changes are ok, proceed

About MFA: I have to read a bit more about the whole TOTP / Google Authenticator process but couldn't those fields, or a single JSON field, be added to `external_auth` table? But I don't see a problem in adding a new table if/when we're going to adopt this mechanism.
