### ISSUE TITLE
ui: add filter on object status in list view

### ISSUE THREAD

**Issue by stefanorosanelli** [bedita/bedita#809]
Add an 'object.status' filter to default filters in object list view in backend 
Should be hidden as default, viewable through config array in .tpl views

**Comment by vallo87** [comment]
changes in the options array

{$options = [
                ...
        'categories' =>false, true or array('label' => 'mylabel'),
        'status' => false, true or array('on' => 'myOnLabel', 'draft' => 'myDraftLabel', 'off' => 'myOffLabel')
                ...
    ]
}

**Comment by stefanorosanelli** [comment]
It works, there's a minor UI issue: default (no checkbox selected) has same behavior as all checkbox selected

solution proposed by @xho:
- as default all statuses are checked (also with "reset filter" action)
- if there's only one item checked it can't be unchecked (it's impossibile to uncheck all statuses)
