### ISSUE TITLE
Missing a way to invalidate FrontendController::objectCache array

### ISSUE THREAD

**Issue by batopa** [bedita/bedita#810]
We need a method to invalidate keys of `FrontendController::objectCache` array to force the reload of data.

**Comment by batopa** [comment]
Added `FrontendController::clearObjectCache()`

``` php
// example from PagesController
$this->clearObjectCache(); // clear all

$this->clearObjectCache(12); // clear objectCache for object with id 12

$this->clearObjectCache(array(12, 43)); // clear objectCache for object with id 12 and 43
```

**Comment by stefanorosanelli** [comment]
Seems ok, the only problem i see is naming: `clearObjectCache` may suggest that we are cleaning the object cache using `Cache::delete()` or `BeObjectCache::delete()` - instead we are only dealing with the internal array -- `clearObjectCacheArray()` ??

**Comment by batopa** [comment]
Agree, I'll rename it to `clearObjectCacheArray`
