### ISSUE TITLE
Automagic invalidation of FrontendController::objectCache array

### ISSUE THREAD

**Issue by batopa** [bedita/bedita#812]
After #810 we have a way to invalidate `FrontendController::objectCache` array using `FrontendController::clearObjectCacheArray()` method.

We can improve the invalidation using `BeCallbackManager` as event manager and trigger an event for invalidate the array in `CacheableBehavior::afterSave()` and `CacheableBehavior::afterDelete()`

**Comment by fquffio** [comment]
PR merged. I'm closing this issue.
