### ISSUE TITLE
Db: sql with multiple queries not returning errors

### ISSUE THREAD

**Issue by stefanorosanelli** [bedita/bedita#813]
Using `DbUtils::executeTransaction($sql)` when $sql contains multiple queries,  in case of SQL errors:
- no errors are returned (so no error message)
- no rollback is performed

**Comment by fquffio** [comment]
Now SQL errors should correctly raise an exception, that is then caught and results in `error` being correctly populated with the error message.

We should keep in mind, anyway, that some statements in some databases (notably, DDL in MySQL – read [here](http://dev.mysql.com/doc/refman/5.7/en/implicit-commit.html) and [here](https://wiki.postgresql.org/wiki/Transactional_DDL_in_PostgreSQL:_A_Competitive_Analysis)) cause an implicit transaction commit, thus a rollback is not always possible.
