### ISSUE TITLE
Use versioned schema for test fixtures

### ISSUE THREAD

**Issue by fquffio** [bedita/bedita#820]
Unit tests' fixtures should (temporarily?) use JSON schema versioned thanks to #802 to generate DDL, in order to have always up-to-date schema when running tests, thus pointing out incompatible changes in schema structure.

**Comment by fquffio** [comment]
@stefanorosanelli @batopa @didoda This seems to be working right now. Test fixtures should extend `BEdita\Auth\TestSuite\Fixture\TestFixture` instead of usual `Cake\TestSuite\Fixture\TestFixture` to take advantage of this functionality.

I would prefer to leave the `$fields` attribute correctly populated (and possibly updated) in fixtures in order to make it easier to migrate back to the usual test pattern as soon as we'll have a more stable schema structure, but at the present moment it is ignored for tables that are present in the `BEdita/Core/config/be4-schema.json` file.

**Comment by batopa** [comment]
@fquffio why don't always use json schema? I think that maintaining `$fields` in every `Fixture` could become tedious and more subject to mistakes.

**Comment by batopa** [comment]
Something like

``` php
// in BEdita\Auth\TestSuite\Fixture\TestFixture

public function init()
{
    if ($this->table === null) {
        $this->table = $this->_tableFromClass();
    }

    if (Configure::check("schema.{$this->table}.columns")) {
        // #820 Temporarily use `ROOT/plugins/BEdita/Core/config/be4-schema.json` to obtain schema.
        $this->fields = Configure::read("schema.{$this->table}.columns");
        $this->fields += [
            '_constraints' => Configure::read("schema.{$this->table}.constraints") ?: [],
            '_indexes' => Configure::read("schema.{$this->table}.indexes") ?: [],
            '_options' => Configure::read("schema.{$this->table}.options") ?: [
                'engine' => 'InnoDB',
                'collation' => 'utf8_general_ci',
            ],
        ];
    }

    parent::init();
}
```

should prevent us to define `$fields` in every Fixture.

what do you think?

**Comment by fquffio** [comment]
@batopa It already does (see 82cd064). What I'm not sure is whether this is considered to be a "good pattern".

**Comment by batopa** [comment]
@fquffio it is slightly different to avoid errors if `$fields` is not defined in `Fixture`. Calling first `parent::init()` thrown  an Exception because can't create the schema.

**Comment by fquffio** [comment]
@batopa Oh, I see. Sorry, I didn't notice the difference. Yes, it would definitely do the job, but my doubt still remains. 😉

**Comment by batopa** [comment]
Obvioulsy it can be written in a better way :smile: 
For example if `Fixture::$fields` is not empty use it else use schema json

**Comment by stefanorosanelli** [comment]
I think it's a good solution to have all metadata in a unique JSON also for unit-tests
So :+1: for @batopa patch

**Comment by batopa** [comment]
1e9e0b3 introduces a callback to handle data before build schema.
Defining a method signed `beforeBuildSchema(\Cake\Event\Event $event)` in a class that extends `BEdita\Auth\TestSuite\Fixture\TestFixture` you can change some data before table schema was built.

For example you could modify `$fields` loaded via schema json.
