### ISSUE TITLE
Current date&time are used as part of the object cache key

### ISSUE THREAD

**Issue by fquffio** [bedita/bedita#831]
In `FrontendController::loadSectionObjects()` and `FrontendController::loadRelatedObjects()`, object cache uses current date&time as part of the cache key, in order to handle publication dates. This causes a continuous cache read miss, thus the cache is recreated on almost every call.

We should work around this and handle filtering by publication date in some different fashion.

**Comment by fquffio** [comment]
The only solution I can think of is to obtain the date when cache will become invalid on cache creation.

Such date would be obtained somehow like this:

``` sql
SELECT LEAST(
    (SELECT MIN(start_date) FROM contents WHERE start_date > NOW() AND ...),
    (SELECT MIN(end_date) FROM contents WHERE end_date > NOW() AND ...)
);
```

This way, on cache read, we could check if cache is still to be considered valid, otherwise continue as if the cache read attempt was actually a miss.

@stefanorosanelli @batopa Any other suggestion and/or brilliant idea? 😄

**Comment by batopa** [comment]
:+1:  @fquffio the idea seems good

**Comment by stefanorosanelli** [comment]
agree, good idea, find future dates where cached data may change
proceed

**Comment by stefanorosanelli** [comment]
Ok
Good job :+1:
