### ISSUE TITLE
Implement basic API Content Negotiation rules

### ISSUE THREAD

**Issue by stefanorosanelli** [bedita/bedita#836]
First set of rules, from **Accept:** request header
- on `text/html` or `application/xhtml+xml` respond with a content type error (406 Not acceptable - https://tools.ietf.org/html/rfc2616.html#section-10.4.7) in _production mode_, and with `text/html` in _debug mode_  showing JSON data in HTML with DebugKit display
- on `application/xml` => content type error (406), in a future version an XML reponse 
- `application/ld+json` => content type error (406), in a future version with JSON-LD 
- `application/json` => current JSON API response with `application/json` content type
- `application/vnd.api+json` => current JSON API response with `application/vnd.api+json` content type
- any other value => content type error (406)

As a consequence, selecting the right response format implies loading of a `FormatterComponent` to format data correspondingly (JSON API formatter, JSON-LD formatter, BE3 Formatter,...)

**Comment by stefanorosanelli** [comment]
@batopa @fquffio are rules ok?

**Comment by stefanorosanelli** [comment]
Basic rules implemented on **Accept:** request header:
-  `application/json` => response has `application/json` content type
-  `application/vnd.api+json` => response has `application/vnd.api+json` content type
-  on `text/html` or `application/xhtml+xml`, `application/xhtml`, `text/xhtml` => if `debug` configuration is _true_ or `Accept.html` configuration set to true an HTML reponse with JSON data is presented otherwise a content type error **406 Not Acceptable**  
-  any other value => content type error **406 Not Acceptable**

**Comment by stefanorosanelli** [comment]
Possible HTML enhancements:
- use `Template/Common/html_json.ctp` to render JSON - current rendering is in `Layout/default_api.ctp`
- better JSON rendering with syntax highlighting, anchors, tree ui

**Comment by stefanorosanelli** [comment]
Now `Template/Common/html_json.ctp` is used to render JSON

Handled **415 Unsopported Media Type** JSON API error  http://jsonapi.org/format/#content-negotiation-servers

Still to do: better JSON rendering with syntax highlighting, anchors, tree ui (new issue?)

**Comment by batopa** [comment]
Merged via PR https://github.com/bedita/bedita/pull/846
