### ISSUE TITLE
Object model design in BE4

### ISSUE THREAD

**Issue by stefanorosanelli** [bedita/bedita#838]
Implement table inheritance in BEdita4 to map objects table associations in models
Find best strategy using CakePHP tools

**Comment by batopa** [comment]
Simple CTI for find is done. To inherit a table from Table Model

``` php
public function initialize(array $config)
{
    $this->addBehavior('BEdita/Core.ClassTableInheritance', [
        'table' => [
            'name' => 'TableName',
            'className' => 'Optional\Table\ClassName'
        ]
    ]);
}
```

For now work `find()` and `contain()`. The results will be collapsed on main Entity.

**Comment by fquffio** [comment]
PR was merged. I'm closing this issue.
