### ISSUE TITLE
Basic pagination in API response

### ISSUE THREAD

**Issue by stefanorosanelli** [bedita/bedita#839]
Implement paginated response for `/users` endpoint - logic to be reused in other endpoints (where applicable)
JSON API pagination spec here http://jsonapi.org/format/#fetching-pagination

**Comment by fquffio** [comment]
Just a few questions about the spec:
- when serving the first page in the set, `links.prev` should be `null`, right?
- in the same fashion, when serving the last page in the set, `links.next` should be `null`, correct?
- assuming all the results can be displayed in a single page, I guess that both `links.prev` and `links.next` should be `null`, but how about `links.first` and `links.last`? Should `links.last` be `null` as well, or (what I would lean towards) should both links have the same URL to the first page?

**Comment by stefanorosanelli** [comment]
About the spec:
- unavailable **keys** must be `null` or omitted (from the spec) - so it's up to us to decide - is there a solution preferable for a client? @batopa ?
- same logic should be applied to `links.next` and `links.prev`, in case of a single page response I would put same URL on both `links.first` and `links.last`: _last_ page actually is not missing
- there are some additional information we may want to add in a response: total number of items, page size, current page - since they are not links, should they stay in `meta` block?

**Comment by fquffio** [comment]
@stefanorosanelli Completely agree on 2nd and 3rd point. For what concerns the "`null` or omitted" question, I'll wait for an enlightened answer by @batopa and @edoardocavazza. 😉  In the meanwhile, I guess we could consider this a minor change to be made whenever we'll decide which path to follow, couldn't we?

Pagination links and metadata are automatically added whenever the CakePHP's `PaginationComponent` is used. Should we decide to implement our own pagination component or to extend the default one, we might need to update pagination handling in `BEdita/API.JsonApiComponent` in order to restore a seamless integration.

Example response (`GET /users`):

``` json
{
  "data": [
    {
      "id": "1",
      "type": "users",
      "attributes": {
        "username": "blake.jenkins",
        "blocked": false,
        "last_login": null,
        "last_login_err": null,
        "num_login_err": 0,
        "created": "2016-05-09T08:33:01+0000",
        "modified": "2016-05-09T08:33:01+0000"
      }
    },
    {
      "id": "2",
      "type": "users",
      "attributes": {
        "username": "erdman.samir",
        "blocked": false,
        "last_login": null,
        "last_login_err": null,
        "num_login_err": 0,
        "created": "2016-05-09T08:33:01+0000",
        "modified": "2016-05-09T08:33:01+0000"
      }
    }
  ],
  "links": {
    "self": "http://10.0.83.4/users",
    "first": "http://10.0.83.4/users",
    "last": "http://10.0.83.4/users",
    "prev": null,
    "next": null
  },
  "meta": {
    "page": 1,
    "count": 2,
    "perPage": 20,
    "pageCount": 1
  }
}
```

**Comment by stefanorosanelli** [comment]
:+1: 
For `"meta"` block I suggest we use:

``` json
"meta": {
    "pagination": {
        "page": 1,
        "page_items": 2,
        "count": 2,
        "page_size": 20,
        "page_count": 1
   }
}
```

**Comment by batopa** [comment]
I would prefer to always have keys to maintain consistent pagination data.
I would set to `null` if missing value

**Comment by batopa** [comment]
merged in PR https://github.com/bedita/bedita/pull/846

**Comment by stefanorosanelli** [comment]
- using a browser to view data (using `html` Accept Header) seems that query parameter `page` like `page=2` is ignored but it works fine using a `json` Accept Header
- should `links.self` give complete current URL? query parameter `page` is missing
