### ISSUE TITLE
API basic error response

### ISSUE THREAD

**Issue by stefanorosanelli** [bedita/bedita#840]
Implement a JSON response with error details on bad requests/generic errors/exceptions

JSON API error response spec http://jsonapi.org/format/#errors

See also http://book.cakephp.org/3.0/en/development/errors.html

**Comment by fquffio** [comment]
Example error response (`GET /users/0`):

``` json
{
  "error": {
    "status": "404",
    "title": "Not Found"
  },
  "links": {
    "self": "http://10.0.83.4/users/0"
  }
}
```

If debug mode is on, the `error` object contains an additional `meta` key, which is an object itself. Such `meta` object has a `trace` key containing the stack trace that threw the exception.

**Comment by batopa** [comment]
Merged wirh PR https://github.com/bedita/bedita/pull/846
