### ISSUE TITLE
'Create new section' ignores where I am inside the publication

### ISSUE THREAD

**Issue by rzecchini** [bedita/bedita#845]
When I make a new section the default position should be within the section where I am calling the action from. Moreover – as recorded in the video below – it fails at finding the section when typed inside the search form. The only way to get it is to click the little arrow next to the pubblication name.
![new_section_bedita](https://cloud.githubusercontent.com/assets/2392233/14956365/a4983d18-107f-11e6-8f57-848d623fa0e0.gif)

**Comment by stefanorosanelli** [comment]
Agree, behavior could be the same as **create new section here** in **Sections** block, but then maybe we should remove that button.

**Comment by rzecchini** [comment]
Never notice that button until now 😳
I think the main problem is to have multiple targets doing the same thing or related targets that sit visually distant from each other. When someone browses through his sections he doesn't even notice **create new section here** because it is hidden:
<img width="534" alt="schermata 2016-05-04 alle 10 02 41" src="https://cloud.githubusercontent.com/assets/2392233/15010174/0dc010ce-11eb-11e6-8c91-3807a0414db1.png">
I had to open and scroll all of my sections before figuring out where it was:
<img width="310" alt="schermata 2016-05-04 alle 10 03 01" src="https://cloud.githubusercontent.com/assets/2392233/15010225/5171af76-11eb-11e6-82a6-36bc9bd25441.png">
I would definitely remove the **create new section here** button and add its functionality to the main **new section** button.

**Comment by stefanorosanelli** [comment]
Hidden BEdita gems! :)

**Comment by qwerg** [comment]
Don't drop the gem. Add new functionality to new section creation, but keep
this option too.

Il mercoledì 4 maggio 2016, Stefano Rosanelli notifications@github.com ha
scritto:

> Hidden BEdita gems! :)
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/bedita/bedita/issues/845#issuecomment-216892970

## 

---

Andrea Alberti

**Comment by batopa** [comment]
obsolete
