### ISSUE TITLE
[API] cache Permission queries

### ISSUE THREAD

**Issue by stefanorosanelli** [bedita/bedita#853]
In some methods used intensively in API we could introduce a cache:
- `Permission::isObjectsAndParentsAccessible` - called by `ApiValidator::isObjectReachable` 
- `Permission::relatedObjectsNotAccessibile` - called by `ApiFormatter::formatRelationsCount`
- `ApiBaseController::responseChildren()`

**Comment by batopa** [comment]
Merged in PR #854
