### ISSUE TITLE
Handle "select" clause in class table inheritance

### ISSUE THREAD

**Issue by batopa** [bedita/bedita#872]
When a table inherits another table should be possible to select fields of inherited table without specifying the association.

For example:

``` php
// profiles table inherits objects table
$query = TableRegistry::get('Profiles')
    ->find()
    ->select(['title', 'uname', 'surname']);
```

Should correspond to:

``` php
$query = TableRegistry::get('Profiles')
    ->find()
    ->select(['Objects.title', 'Objects.uname', 'surname']);
```

**Comment by fquffio** [comment]
PR merged just two months and a week after I was assigned to it. Sorry for delay!
