### ISSUE TITLE
Saving data in class table inheritance

### ISSUE THREAD

**Issue by batopa** [bedita/bedita#873]
Saving data on tables that have class table inheritance should be transparent.

Saving entities should map inherited fields on the right association.

So:

``` php
$profiles = TableRegistry::get('Profiles');
$profile = $profiles->newEntity([
    'title' => 'My title',
    'surname' => 'Surname'
]);
$profiles->save($profile);
```

Should save `title` in `objects` table and `surname` in `profiles` table.

**Comment by fquffio** [comment]
PR merged.
