### ISSUE TITLE
[API] save section need to be handled 

### ISSUE THREAD

**Issue by vallo87** [bedita/bedita#883]
- API endpoint children needs to check if the object is a section, if so, it must throw an error and do nothing
- when creating a section object Tree Update must be avoided in Section->saveObject

**Comment by vallo87** [comment]
done: when creating a section object Tree Update must be avoided in Section->saveObject

**Comment by stefanorosanelli** [comment]
Seems ok, what's missing (and potentially harmful):
- if a section is created `data['parents']` could be empty - instead it should consist of a single _id_ ponting to an area or section
