### ISSUE TITLE
basic /objects endpoint

### ISSUE THREAD

**Issue by stefanorosanelli** [bedita/bedita#890]
only paginated list (/objects) and single object (/objects/1) GET methods

**Comment by stefanorosanelli** [comment]
Current limitations:
- data are limited to `objects` table, other table data are not displayed
- as `type` in response currently `object_types.name` field is used, if we want to keep a plural form in response we may do it after #859

**Comment by batopa** [comment]
Merged with https://github.com/bedita/bedita/pull/893
Current limitations will solved in next implementations
