### ISSUE TITLE
Empty anchors cause CKEditor strange behavior

### ISSUE THREAD

**Issue by edoardocavazza** [bedita/bedita#898]
When an empty anchor tag `<a>` is inserted in the body without text content (`<a href="..."></a>`), CKEditor tries to fix it but it smashes up the content.

Before to fix it, I am wondering if we should handle empty anchors with input validation or just "workarounding" the view.

@qwerg @xho @stefanorosanelli @batopa @didoda @fquffio

**Comment by didoda** [comment]
CKEditor or BEdita should sanitize html, removing or fixing "invalid" DOM; I guess that empty anchor should be allowed, IMO it doesn't break any DOM rule... trying to figure it out from https://www.w3.org/TR/html5/text-level-semantics.html#the-a-element

A couple of tickets for CKEditor, about removing empty anchors:
- https://dev.ckeditor.com/ticket/10325
- https://dev.ckeditor.com/ticket/2253

CKEditor developers consider empty anchor as an issue, not allowed...

**Comment by batopa** [comment]
obsolete
