### ISSUE TITLE
introduce objects.revision field [versioning & sync]

### ISSUE THREAD

**Issue by stefanorosanelli** [bedita/bedita#909]
In order to implement versioning and sync (in near future) we could add a revision number field to objects table, to be incremented automatically at each save operation that changes some of the properties

An **AUTO_INCREMENT** field maybe?
A Behavior to handle it for every object?

**Comment by fquffio** [comment]
`AUTO_INCREMENT` wouldn't work, I think. I'd go with a `RevisionBehavior`.

**Comment by stefanorosanelli** [comment]
superseded by #1624 - closing
