### ISSUE TITLE
Use database migrations

### ISSUE THREAD

**Issue by fquffio** [bedita/bedita#913]
In order to ensure database is always up to date, we should use database migrations, that make it possible to apply progressive changes in data structure without loss of data.

Despite BEdita 4 is still in an early pre-release phase, we could adopt this method early to become familiar with it before using it in a production-ready product.

**Comment by fquffio** [comment]
#931 introduces several changes to table structure, that would be rather complex to migrate from present structure. As soon as that issue will be solved, we should proceed with migrations.

**Comment by stefanorosanelli** [comment]
In this phase still other **big** changes could (and probably will) be introduced, if that's problematic with `migrations` we could postpone its introduction when we consider db structure more _stable_
