### ISSUE TITLE
API KEY strategy and usage 

### ISSUE THREAD

**Issue by stefanorosanelli** [bedita/bedita#915]
- define API KEY accepted use cases in BEdita4 (add to doc)
- implement simple use cases for API KEYS and/or create related issues

**Comment by stefanorosanelli** [comment]
API KEYS are often used as a means to authenticate users in API services where the user is typically unique and identifies with the customer of the API
In those use cases API KEYS are used in `Authentication:` HTTP headers and often are composed by  public and secret parts just like username and passwords.

In BEdita4 API KEYS are not used to authenticate users, since every project has many users that are handled directly in BE4.

API KEYS in BE4 are used to:
- enhance API access security - also for anonymous API interrogations - i.e. API calls without authentications
- enable tracking statistics / analytics

API KEYS should be normally kept secret - but if that's not completely possible or safe, e.g. use in Javascript web applications, it's a good practice to identify a single allowed origin for calls using this API KEY

To summarize:
- it's possible to allow calls without API KEYS (useful in dev or test environments or for apps not available to the public) through a configuration parameter (which default value?)
- for a BE4 project we may define more API KEYS - to enable tracking of different apps consuming same project's API
- for each API KEY we may define an origin domain (like www.example.com) - only calls from that domain will be accepted for those API KEYS
- api keys will be used through an HTTP Header **X-Api-Key**
- there will be a tool to automatically generate new API KEYS and block / remove them
- an example configuration layout could be something like:

``` json
  "ApiKeys" : {
    "sdgwr89081023jfdklewrasdasdwdfswdr" : {
      "label" : "web app",
      "origin" : "example.com",
      "valid" : true
    },
    "5894yunbjwp54u5ufn34234h234hlege1" : {
      "label": "android app",
      "origin" : "*",
      "valid" : true
    }
  }
```

@batopa @fquffio what do you think?

**Comment by fquffio** [comment]
Closing, as PR #932 has been merged.
