### ISSUE TITLE
[API] Introducing files upload

### ISSUE THREAD

**Issue by batopa** [bedita/bedita#918]
Uploading files via REST API is missing. Any files uploaded should be linked to a multimedia (video, image, audio, ...) or a custom object type in a configurable way.
## Upload flow
1. A client makes a file upload request
   
   ``` http
   POST /files/:object_type/file_name.jpg
   Host: example.com
   Authorization: Bearer <access_token>
   Accept: application/json
   Content-Type: image/jpeg
   Content-Length: 284
   
   <raw image content>
   ```
   
   where `object_type` is the type of BEdita object linked to that file (for example `image`). In this way we can perform specific checks per object type before accept files. For example we may check some size/extension related to a specific type. 
   Furthmore every object type could have a particular way to treat the file using local filesystem, Amazon S3, ...
2. The server responds with some error if something goes wrong or with the relative path of file uploaded if it succeeded, for example
   
   ``` json
   {
      "api": "files",
      "data": {
          "file": "ab/cd/filename-on-filesystem.jpg"
      },
      "method": "post",
      "params": [],
      "url": "https://example.com/api/files/image/file_name.jpg"
   }
   ```
3. the client proceeds creating the object type with file associated to it
   
   ``` http
   POST /objects
   Host: example.com
   Authorization: Bearer <access_token>
   Accept: application/json
   Content-Type: application/json
   
   {
     "data": {
         "object_type": "image",
         "title": "Image title",
         "uploaded_file: "ab/cd/filename-on-filesystem.jpg"
     }
   }
   ```
4. If `uploaded_file` is not already linked to other object and the file is supported from the specified `object_type` the server will respond with a `201 Created` with the object data as it happens now (http://bedita.readthedocs.io/en/v3.7.0/endpoints/objects.html#create-an-object).

**Comment by stefanorosanelli** [comment]
Seems fine
As a security enhancement, to avoid orphan uploaded files we could use also a sort of hash_job between steps 2 and 3, for instance:
1. in step 2, server reponds also with a hash an creates corresponding hash_job "multimedia object creation is pending"
2. in step 3 we may use this hash to ensure a multimedia file association is pending and we may close the hash job after object creation
3. with a cron shell script we may look for multimedia files not associated after upload and remove them, looking for timed out hash jobs of same type

This could be done after this issue or in BE4 only

**Comment by batopa** [comment]
@stefanorosanelli I agree, in that case the client could set a custom header to specify the hash operation instead of pass `uploaded_file`. The `uploaded_file` could be stay in `hash_jobs.params`
For example:

``` http
 POST /objects
 Host: example.com
 Authorization: Bearer <access_token>
 Accept: application/json
 Content-Type: application/json
 X-BEdita-Upload-Hash: 5a192d3f5716e9709df81974f5ee2aba
 X-BEdita-Upload-Command: associate

 {
    "data": {
        "object_type": "image",
        "title": "Image title"
    }
 }
```

**Comment by batopa** [comment]
Or simply as query string

``` http
 POST /objects?upload_hash=5a192d3f5716e9709df81974f5ee2aba
 Host: example.com
 Authorization: Bearer <access_token>
 Accept: application/json
 Content-Type: application/json

 {
    "data": {
        "object_type": "image",
        "title": "Image title"
    }
 }
```

**Comment by stefanorosanelli** [comment]
:+1: 
I prefer second version, use of query string maybe more intuitive for a developer

**Comment by batopa** [comment]
Due to the way query string check is implemented it is difficult to customize valid query string per endpoint for requests different to GET. We could improve it but could be a bit messy because we need to maintain backward compatibility.

I'll stay simple so I'll pass `upload_token` in the data payload

``` http
 POST /objects
 Host: example.com
 Authorization: Bearer <access_token>
 Accept: application/json
 Content-Type: application/json

 {
    "data": {
        "object_type": "image",
        "title": "Image title",
        "upload_token": "5a192d3f5716e9709df81974f5ee2aba"
    }
 }
```

**Comment by batopa** [comment]
Documentation added:
- http://bedita.readthedocs.io/en/latest/uploading_files.html
-  http://bedita.readthedocs.io/en/latest/endpoints/files.html
