### ISSUE TITLE
Permissions on endpoints and object types

### ISSUE THREAD

**Issue by stefanorosanelli** [bedita/bedita#920]
In order to design permissions on backend and more generally API permissions we have to introduce a system, not related to permissions on single objects (like folders or contents), to provide privileges on single operations like:
- create / update / remove users
- view roles (read-only mode)
- create / update certain object types

**Comment by stefanorosanelli** [comment]
In BE4 every app identifies itself with api-key and/or other header (TBD) 
Default application: backend

On every API call we have a permission check analyzing: endpoint, HTTP method, client app, user roles.
On perms check failure we get a 403 forbidden OR 401 unauthorized response.
On perms check success we get default endpoint response

---

Here a brief list of use cases for every endpoint with a possible implementation on a hypothetic `endpoint_permissions` table.

**Role**: `all` means every role (we could use a special role with id 0), `null` means role independent, also non logged users.
**Application**: `null` means default for every app, also backend
**Permissions**: 
- _R_  read -> GET method 
- _RW_ read & write -> GET, POST, PATCH, DELETE methods
- _BLOCK_  no access

**/auth** 
- every app decides which roles may login - (backend) defaults: _admin, manager, editor_  
- in this particular case check is made after endpoint processing, not before
- an app may require to block /auth

| endpoint | role | application | permission |
| --- | --- | --- | --- |
| auth | manager | null | RW |
| auth | editor | null | RW |
| auth | null | app1 | BLOCK |
| auth | all | app2 | RW |

app1 blocks auth, app2 enables auth for all roles
_R_ permission has no meaning in /auth since only a _POST_ method is available

---

**/home** 
- always available - normally only `/auth` available if user not logged
- an app may decide to block

**/me** 
- always available- gives a 401 if user unlogged
- blockable

| endpoint | role | application | permission |
| --- | --- | --- | --- |
| home | null | null | R |
| home | all | app2 | R |
| me | all | app3 | BLOCK |

no write operations on these endpoints, RW has no effect

---

**/users**
**/roles**
**/object_types**
**/relations**
- (backend) defaults: available only to manager (and admin)
- generally available only to selected roles

| endpoint | role | application | permission |
| --- | --- | --- | --- |
| roles | manager | null | RW |
| roles | editor | null | R |
| roles | null | app1 | BLOCK |
| roles | frontend | app2 | R |
| roles | all | app3 | R |

**/admin**
- only admin role and backend application
- unchangeable
- blockable for an app

| endpoint | role | application | permission |
| --- | --- | --- | --- |
| admin | null | app2 | BLOCK |

only possibile setting is BLOCK, other permissions have no effect

---

**/objects**
- (backend) defaults: logged users RW

| endpoint | role | application | permission |
| --- | --- | --- | --- |
| objects | null | null | R |
| objects | all | null | RW |
| objects | null | app1 | BLOCK |
| objects | frontend | app2 | R |

---

object types endpoints - also permissions on object types are set

**/events**
**/documents**

| endpoint | role | application | permission |
| --- | --- | --- | --- |
| events | editor | null | RW |
| docs | editor | null | R |
| events | null | app3 | BLOCK |

@fquffio @batopa ?

---

What defaults if no record present for an endpoint? 

| role | application | permission |
| --- | --- | --- |
| null | null | RW |

or

| role | application | permission |
| --- | --- | --- |
| null | null | R |
| all | null | RW |

**Comment by stefanorosanelli** [comment]
A special `role` is needed - like `all`, `everybody` - that is automatically assigned to every user, with which we can handle `every user` case.

Opening a PR for schema table, implementation will be in another issue.

**Comment by batopa** [comment]
Merged with PR #973
