### ISSUE TITLE
In view user group, paginate objects with permissions set for group

### ISSUE THREAD

**Issue by qwerg** [bedita/bedita#922]
If too many objects are set, it's not possibile to open the usergroup detail view.
Need to paginate this find:

```
// find objects with permissions set for group // TODO paginate
            $beObject = ClassRegistry::init('BEObject');
            $res = $beObject->find('all', array(
                'fields' => array('BEObject.id, BEObject.title, BEObject.nickname, BEObject.object_type_id, BEObject.status, Permission.id, Permission.flag'),
                'contain' => array(),
                'joins' => array(
                    array(
                        'table' => 'permissions',
                        'alias' => 'Permission',
                        'type' => 'inner',
                        'conditions'=> array(
                            'BEObject.id = Permission.object_id',
                            'Permission.ugid' => $g['Group']['id'],
                            'Permission.switch' => 'group'
                        )
                    )
                )
            ));
```

**Comment by fquffio** [comment]
When saving a group, all its permissions on objects are updated, and data are taken from that form. Thus, raw pagination would result in corrupting permissions for a large number of objects.

Long story short: if we paginate that query, I'm afraid we are forced to refactor the save logic for groups, and it might not be an easy task. 😒 

@batopa @stefanorosanelli @didoda Any suggestions? Any better idea?

**Comment by batopa** [comment]
I don't see any solution except changing the way the save is handled.

Maybe we should introduce a specific view for manage objects' permissions for a group.
For example in groups list `/users/groups` we could have a button `objects protected` or similar that land in a view in which to handle only objects' permissions.
In that way I guess we could paginate and change the way permissions are saved more easily.

**Comment by batopa** [comment]
obsolete
