### ISSUE TITLE
Endpoint to get users related to a role does not comply with JSON API

### ISSUE THREAD

**Issue by fquffio** [bedita/bedita#923]
At the present status, the endpoint to get the list of users related to a role is `GET /roles/:role_id/users`. According to [JSON API spec](http://jsonapi.org/format/#fetching-relationships) this URL is wrong.

The URL should be turned into: `/roles/:role_id/relationships/users`

**Comment by batopa** [comment]
The URL to get the list of related resources were right. `/relationships` is used to get the association data between two resources not the list of related resources.

``` http
GET /roles/:role_id/relationships/users
```

should return as main data the `users.id` joined to roles `:role_id` and eventually other data about the association.
