### ISSUE TITLE
Implement endpoint to get list of roles related to a user

### ISSUE THREAD

**Issue by batopa** [bedita/bedita#924]
The endpoint

``` http
GET /users/:id/roles
```

is to implement.

**Comment by stefanorosanelli** [comment]
Issue almost completed, still few questions/problems:
- links in response of `/users/1/roles` are not as expected, we have

``` json
"links": {
"self": "http://example.com/roles?user_id=1",
"first": "http://example.com/roles?user_id=1",
}
```

instead of

``` json
"links": {
"self": "http://example.com/users/1/roles",
"first": "http://example.com/users/1/roles",
}
```

@fquffio this has something to do with `Router::reverse` usage, but couldn't find out what...
- should we have `relationships` item for every element in a response of `/users/:id/relationships/roles`? this applies to `/roles/:id/relationships/users` as well - I think it's redundant
- to avoid display of `external_auth` relationships I used a bad trick - see 1cfa599 - is there a better way to do it? Hope so :smiley:

**Comment by fquffio** [comment]
- I see that first problem was just solved by @batopa 
- I'd probably leave both links. I know it might seem redundant, but they do pretty different things… 😕  
- I'd add `external_auth` to User's hidden properties, and handle it as such:

``` patch
diff --git a/plugins/BEdita/API/src/Utility/JsonApi.php b/plugins/BEdita/API/src/Utility/JsonApi.php
index b84d349..2946574 100644
--- a/plugins/BEdita/API/src/Utility/JsonApi.php
+++ b/plugins/BEdita/API/src/Utility/JsonApi.php
@@ -119,6 +119,7 @@ class JsonApi
         $relationships = [];
         $associations = TableRegistry::get($entity->source())->associations();
         $relatedParam = sprintf('%s_id', Inflector::singularize($endpoint));
+        $hidden = $entity->hiddenProperties();

         $btmJunctionAliases = array_map(
             function (BelongsToMany $val) {
@@ -130,7 +131,7 @@ class JsonApi
         foreach ($associations as $association) {
             list(, $type) = namespaceSplit(get_class($association));
             $name = $association->property();
-            if (!($association instanceof Association) || $type === 'ExtensionOf' || $name == 'external_auth' ||
+            if (!($association instanceof Association) || $type === 'ExtensionOf' || in_array($name, $hidden) ||
                 ($type === 'HasMany' && in_array($association->target()->alias(), $btmJunctionAliases))) {
                 continue;
             }
diff --git a/plugins/BEdita/Core/src/Model/Entity/User.php b/plugins/BEdita/Core/src/Model/Entity/User.php
index cad47e3..d4523c6 100644
--- a/plugins/BEdita/Core/src/Model/Entity/User.php
+++ b/plugins/BEdita/Core/src/Model/Entity/User.php
@@ -57,6 +57,7 @@ class User extends Profile
      */
     protected $_hidden = [
         'password_hash',
+        'external_auth',
     ];

     /**
```

**Comment by stefanorosanelli** [comment]
To summarize:
- links problem seems fixed 
- @fquffio patch to hide `external_auth` applied
- we will discuss `relationships` items in `/relationships` urls later, in other issues in case

**Comment by fquffio** [comment]
@stefanorosanelli Just another word on the duplicate links question: reading the first example in [this section](http://jsonapi.org/format/#document-compound-documents) of JSON API spec (and actually almost any other example in that document) both links are included.

Also, in [this paragraph](http://jsonapi.org/format/#document-resource-object-relationships) those links are described as URLs with completely different purposes: each one may exist independently from the other.

**Comment by stefanorosanelli** [comment]
Yes, but for every [`resource object`](http://jsonapi.org/format/#document-resource-objects) representation only `id` and `type` fields are mandatory.
While `relationships` (and `links`, `meta`, `attributes`) are completely optional.

It's up to us to decide what to include, JSON API does not impose such inclusions.
