### ISSUE TITLE
DELETE /users/:id and /roles/:id responses does not comply JSON API 

### ISSUE THREAD

**Issue by batopa** [bedita/bedita#925]
Deleting an user or a role the response is a 200 HTTP status code with empty content while JSON API specifies that it must be a 204 HTTP status code with no content http://jsonapi.org/format/#crud-deleting-responses-204 or a 200 with just top-level meta data as content http://jsonapi.org/format/#crud-deleting-responses-200.

I like more 204 with no content, @fquffio @stefanorosanelli are you agree?

**Comment by fquffio** [comment]
I do agree. It has been a problem with #911.

**Comment by stefanorosanelli** [comment]
Content-type with 204 no content response makes no sense, however Web server may add a default content-type if missing.
Now we keep request content-type, already checked and accepted, in response too
