### ISSUE TITLE
[API] Too many objects error in single object request

### ISSUE THREAD

**Issue by stefanorosanelli** [bedita/bedita#938]
a simple GET request on and object with `embed` option like:

``` http
GET /objects/123?embed[relations]=attach|6
```

returns a 400 error response with message: _Too many objects requested_
this error makes sense in an object list but not on a single object

**Comment by batopa** [comment]
I can't reproduce it. Maybe in the meantime it has been solved.

**Comment by batopa** [comment]
Solved in https://github.com/bedita/bedita/issues/779
