### ISSUE TITLE
[CTI] cascade validation and type-cast properties

### ISSUE THREAD

**Issue by batopa** [bedita/bedita#941]
At the moment dealing with hydrating entities the only data validated and type-casted are those of main entity, but we need to validate and type-cast also the inherited entities.

For example doing

``` php
$profile = TableRegistry::get('Profiles')->newEntity($data);
```

`BEdita\Core\Model\Entity\Profile` properties are validated and type-casted but not the inherited properties from `BEdita\Core\Model\Entity\Object`. 

We could use reusable validators
https://book.cakephp.org/3.0/en/core-libraries/validation.html#creating-reusable-validators

**Comment by fquffio** [comment]
After #1155 and #1269 this issue became obsolete.
