### ISSUE TITLE
Shell setup script

### ISSUE THREAD

**Issue by stefanorosanelli** [bedita/bedita#942]
Create a simple shell script for initial setup:
- check database connection
- if no valid db connection
  - ask user to review `app.php` file and insert connection data
  - or ask for host / username / password / driver and update `app.php`
- if database is empty create schema and insert starting data, otherwise ask user to skip action
- check permissions on filesystem
- ask for username and password to define first BEdita4 admin user

**Comment by stefanorosanelli** [comment]
First basic implementation is ready. 
Lot of things could be improved.
- console output styles are basic, we can do better than this :smile: 
- `app.php` is not automatically updated, we simply tell user to check config file
- permissions on filesystem are shown for `logs/` and `tmp/` folders, but no action is taken
- initial password is visible and password is typed only once
- user with id = 1 is modified, no new user is created

**Comment by fquffio** [comment]
If we take advantage of Composer's IO interface, we should have access to a method for asking passwords and hiding the typed answer: https://getcomposer.org/apidoc/master/Composer/IO/IOInterface.html#method_askAndHideAnswer

**Comment by batopa** [comment]
But is ComposerIO interface available without using composer event (post-update, post-install, ...)? I mean for use it normally in CakePHP shell scripts?

If no, Composer uses https://github.com/Seldaek/cli-prompt so we could trying to integrate it for using in CakePHP shell.

**Comment by fquffio** [comment]
PR has been merged. @stefanorosanelli shall we close this issue?

**Comment by stefanorosanelli** [comment]
Ok, issue moved to _Docs_ pipeline, will close afterwards
