### ISSUE TITLE
Differentiate logic DELETE from SQL row delete on objects

### ISSUE THREAD

**Issue by stefanorosanelli** [bedita/bedita#945]
Default DELETE action method on objects MUST change its status to _DELETED_ and not remove records.
We have to introduce an actual record delete (empty trashcan action).

Proposals

``` http
DELETE /objects/:id?forceRemove=1
```

or 

``` http
DELETE /trashcan/:id
```

@fquffio @batopa @didoda 
Only an admin should perform empty thrash actions?
Maybe with different endpoint we can handle permissions better?

**Comment by didoda** [comment]
Trashcan is a UI metaphore.
We can consider object removal as 2 step operation:
1. mark object as 'deleted'
2. delete it

Objects marked as 'deleted' should be automatically removed, some time after the day they have been marked as 'deleted'.
DELETE endpoint should do the "mark object as 'deleted'" task only, IMO.
Force delete should be an admin task or automatic (with some configurable policy).

**Comment by stefanorosanelli** [comment]
Agree: but objects marked as `deleted` should be removed by an explicit user/administrator action, like _empty trash_, don't think that automatic delete is generally a good idea.

But the question is: in terms of REST endpoints and methods how do we handle physical/permanent DELETE or _empty trash_ actions?

**Comment by didoda** [comment]
I prefer "DELETE /trashcan/:id" for 2 reasons:
1. it's shorter than DELETE /objects/:id?forceRemove=1
2. it separates logical and physical DELETE in different endpoints (permission handling should be easier this way)

**Comment by stefanorosanelli** [comment]
After a brief review with @batopa and @fquffio:
- from `/objects` objects with status **deleted** are never reachable
- from `/trashcan` endpoint only **deleted**  objects are visible

Actions available in `/trashcan` are: 
- **index** and **view** - using **GET** - like `/objects` 
- **delete** - using **DELETE** - removes permanently an object or a list
- **restore** - remove from trashcan - using **PATCH** (???) that can only modify `objects.status` to `on`, `draft` or `off` or, even better to its previous status (after versioning is implemented)

From that another question arises: what status should be visible from `/objects`?
From **manager** app we will see on, draft and off - but from a client app? default should be on, but we should be able to see `draft` objects in **staging** apps

@batopa proposes: available statuses are `application` properties - for every client application we can decide if only `on` or `on` and `draft` are available.

**Comment by stefanorosanelli** [comment]
Since we agree on a new endpoint `/trash` we better create two separate issues:
- soft delete 
- `/trash` endpoint
