### ISSUE TITLE
[CTI] delete fails because of referential integrity

### ISSUE THREAD

**Issue by batopa** [bedita/bedita#948]
Deleting an object fails because `ExtensionOf` association deletes first the ancestor (objects table) that  delete all children table by referential integrity. The ORM then tries to delete a row on children that not exists anymore and throws an error.

Example:

``` php
$profiles = TableRegistry::get('Profiles');
$profile = $profiles->get(1);
$profiles->delete($profile);
```

we need to implement another strategy.

**Comment by fquffio** [comment]
PR has been merged, so this issue can be closed.
