### ISSUE TITLE
BEdita API extra meta informations

### ISSUE THREAD

**Issue by edoardocavazza** [bedita/bedita#949]
I think we should introduce some meta informations in every API call, such as Core and Api versions.

Should we use custom headers?

```
X-BEdita-Version: 4.0.0
X-BEdita-API: 1
```

**Comment by fquffio** [comment]
API version is implied by content negotiation, according to [JSON API specifications](http://jsonapi.org/format/#content-negotiation), thus only `X-BEdita-Version` is needed.

**Comment by stefanorosanelli** [comment]
@fquffio @edoardocavazza @batopa 

I think a `X-BEdita-API` or similar version is needed if we introduce backwards incompatible changes in API - content negotiation in JSON API is used AFAIK to define JSON API version not BEdita API format

Suppose we make radical changes to an endpoint response, we would probably use same JSON API version.
Still: API changes may be visible/used to non JSON API future implementations.

And of course `X-BEdita-API` differs from `X-BEdita-Version`
