### ISSUE TITLE
Expose object type as virtual property "type" in entities

### ISSUE THREAD

**Issue by fquffio** [bedita/bedita#955]
To improve consistency and reusability in `JsonApi` utility class, I think it would be a good idea to add a virtual property `type` in object entities, that basically returns the object type name, or "object" as a fallback.

This virtual property could also be writable, and it would provide a simple interface to set the object type on creation.

@batopa @didoda @stefanorosanelli ?

**Comment by stefanorosanelli** [comment]
:+1: if this will be used by the `type` returned by JSON API response it's ok

don't know about `object` as fallback since it's not an actual type

also `Role` entity could have it, and other items that are not objects (like `ObjectType` ?)

**Comment by fquffio** [comment]
@stefanorosanelli Yeah, that was the main purpose of this proposal.

You're right: probably having "object" as a fallback leads to more confusion than having no fallback.

For entities that do not represent a BEdita object (e.g. `Role`, `ObjectType`, …) we could either implement a custom getter-only property, or inflect the type from the table. This way, setting the default type in controller would be only needed when dealing with arrays, but hence most of the time we have hydrated entities, it would require even less configuration.

Basically, I'd change the way the type is retrieved in `JsonApi` utility class to something like:

``` php
if ($item instanceof EntityInterface) {
    if ($item->get('type')) {
        $type = $item->get('type');  // Whether this is an "actual" or virtual property, it's not our business.
    } else {
        $type = $theDefaultTypeSetInController ?: Inflector::underscore(Inflector::pluralize($entity->source()->table()));  // Inflect type from table name as a last resort.
    }
} else {  // $item is array
    $type = !empty($item['type']) ? $item['type'] : $theDefaultTypeSetInController;  // Nothing changes here.
}
```
