### ISSUE TITLE
Newsletter - template, specific css definition

### ISSUE THREAD

**Issue by batopa** [bedita/bedita#96]
Riaguardo il css da utilizzare per un certo template newsletter

 1. Aggiungere un campo nel database per inserire il nome del css (default: base)
 1. Aggiungere campo nel form del template e salvataggio in db.
 1. Utilizzo del css inserito nel db nella composizione di un messaggio associato ad un certo template

**Comment by stefanorosanelli** [comment]
Can we drop this issue? @batopa @xho @qwerg

**Comment by qwerg** [comment]
Newsletter should use graphics/templates inherited from a frontend.
If there's no frontends, the newsletter should use a standard BEdita template and graphics.
But at present, frontends are not visibile or managed in BEdita (it's probably a BE4 feature).
We can close this issue, and postpone to a more general newsletter refactor (or drop :-)) in BE4

**Comment by stefanorosanelli** [comment]
agree with @qwerg closing
