### ISSUE TITLE
Use BeEmbedMedia for custom object types extending Streams

### ISSUE THREAD

**Issue by fquffio** [bedita/bedita#960]
If a custom object type extends `BeditaStreamModel` or `BeditaSimpleStreamModel` it is impossible to use `BeEmbedMediaHelper` to generate thumbnails and such.

We should add a configuration parameter to tell BeEmbedMediaHelper to treat a custom object type as if it was one of the core ones. For instance, one could have the `Avatars` object type, and want Avatars to behave like Images.

We could either add a global configuration (i.e. always handle Avatars as Images) or a per-invocation parameter `{$beEmbedMedia->object($myObj, ['forceType' => 'Image', …])}`… or both.

@bedita/core What's the best option?

**Comment by batopa** [comment]
Or we could define in the Model class how it behaves

``` php

class Avatar extends BeditaStreamModel {

    public function embedAs() {
         return 'Image';
    };

}
```

than in `BeEmbedMediaHelper` we could change `getType()` method with something like

``` php
private function getType($obj) {
    $model = Configure::read('objectTypes.' . $obj['object_type_id'] . '.model');
    if (empty($model)) {
         return '';
    }

    $objectModel = ClassRegistry::init($model)
    if (!method_exists('embedAs', $objectModel) {
        return $model;
    }

    return $objectModel->embedAs();
}
```

**Comment by fquffio** [comment]
Great idea! Probably I would also add `$obj` to `embedAs` method parameters, just in case the behavior depends on the object being embedded. Thus `$objectModel->embedAs($obj)`.
