### ISSUE TITLE
[API] Make concept of "object reachable" configurable

### ISSUE THREAD

**Issue by batopa** [bedita/bedita#963]
Currently an object is reachable via API if it's on publication's tree or is related to an object on publication's tree.

We need a way to decide what means "reachable" for a specific frontend API. 
For example in some situation I could want to permit to get or save objects without the need to check those conditions.

**Comment by didoda** [comment]
We could force skip `ApiValidator->checkObjectReachable($id)`, using a call in controller; i.e.:
```
$this->ApiValidator->enableObjectReachbleCheck(false);
call_user_func_array(array($this, 'getObjects'), ...)
```
