### ISSUE TITLE
Authorization for endpoint permissions

### ISSUE THREAD

**Issue by stefanorosanelli** [bedita/bedita#968]
Implement authorization for endpoint permission using rules and schema from #920 
- handle `all` or `everybody` special role 
- define initial data set for `endpoints` - see #969
- use CakePHP Authorization Handler - http://book.cakephp.org/3.0/en/controllers/components/authentication.html#authorization
- should we handle applications - client apps recognized via api-keys ? or create another issue for that?

**Comment by fquffio** [comment]
After this has been implemented, we should be able to remove `$this->Auth->allow()` in `AppController::initialize()`. Then we could also bind `LoggedUser::setUser()` to the `Auth.afterIdentify` event.
