### ISSUE TITLE
Automatic populate object_type_id field in object creation

### ISSUE THREAD

**Issue by stefanorosanelli** [bedita/bedita#971]
In JSON POST data calls avoid to set object_type_id field

Now to create an object you have to use it

``` json
{
    "data": {
        "type": "users",
        "attributes": {
            "object_type_id": 1,
            ......
            "username": "gustavo",
            "password_hash": "gustavo"
        }
    }
}
```

**Comment by fquffio** [comment]
I think this is somehow related to #955.

**Comment by stefanorosanelli** [comment]
That's right,  `type_id` and `type` are both needed - we could probably merge this with #955  
You may proceed if you prefer so

**Comment by stefanorosanelli** [comment]
Seems solved with #955 - moved to `Test`

@fquffio can we close it?

**Comment by fquffio** [comment]
As I wrote in [this comment](https://github.com/bedita/bedita/pull/1026#issuecomment-258476446), it depends on what do we mean with "automatically set". 😄

I guess that current functionality can be considered sufficient. @batopa ?

**Comment by batopa** [comment]
I think it's ok for now. Closing
