### ISSUE TITLE
Set `created_by` and `modified_by` properties

### ISSUE THREAD

**Issue by fquffio** [bedita/bedita#975]
When creating or patching an object, `created_by` and `modified_by` should be updated accordingly based on the currently logged in user. So far, they have been arbitrarily set to `1`.

**Comment by stefanorosanelli** [comment]
Through a singleton class like `CurrentUser` where we store/set current user data like `id` and other attributes it would be possible to use that info in the same way from anywhere, also from shell commands or unit test.
@bedita/core ?

**Comment by fquffio** [comment]
PR has been merged. This issue can now be safely closed. 🙃
