### ISSUE TITLE
[API] Make configurable file size, max size and max number of files for /files endpoint

### ISSUE THREAD

**Issue by batopa** [bedita/bedita#976]
We should permit to configure some parameters to use when uploading a file through `/files` endpoint.
- `maxFileSize` i.e. the max dimension that a single file can have
- `maxSizeAvailable` i.e. the max size availaible for every user (all files)
- `maxFilesAllowed` i.e. the max number of file that every user can upload

``` php
$config['api']['upload'] = array(
    'maxFileSize' => 8388608, // 8 MB
    'maxSizeAvailable' => 83886080, // 80 MB
    'maxFilesAllowed' => 100
);
```

@bedita/core should we have some default values if some configuration missing?

Furthermore we have already implemented a mime type check using `$config['validate_resource']['mime']` of BEdita core config.
We could introduce an alias `mimeTypes` of it in `$config['api']['upload']` and fallback to `$config['validate_resource']['mime']` if `$config['api']['upload']['mimeTypes]` is not defined.
In this way we'll have all upload configuration grouped.

**Comment by stefanorosanelli** [comment]
Yes, probably some `high` default max values are a good idea

**Comment by batopa** [comment]
And... should be better to explicit conf per object types?
For example:

``` php
$config['api']['upload'] = array(
    'maxFileSize' => array('image' => 8388608, 'video' => 22222222)
    'maxSizeAvailable' => array('image' => 83886080, 'video' => 99999999999)
    'maxFilesAllowed' => array('image' =>100, 'video' => 30)
);
```

where the total is the sum of all object types conf. If some value for object type missing use default.

This introduce more control and more complexity.
