### ISSUE TITLE
GET /auth endpoint - logged user data

### ISSUE THREAD

**Issue by stefanorosanelli** [bedita/bedita#982]
read only endpoint to get user logged own data
same response as `/users/:id` with id of logged user

proposals to use a better name than `/me` are welcome :smiley:

**Comment by fquffio** [comment]
Maybe this endpoint could simply perform a redirect to the user's detail page. For instance, let's say the currently logged in user has ID=1, a `GET /me` request could simply redirect to `/users/1` to avoid duplicating logic and tests.

@batopa @edoardocavazza ?

**Comment by stefanorosanelli** [comment]
That's ok, as far as permissions on `/me` and `/users` endpoints are treated separately (same user may not call `/users/1` directly)

**Comment by stefanorosanelli** [comment]
Should also a PATCH method available for one user to change its data?

What about DELETE? (Unsubscribe and logout)

**Comment by stefanorosanelli** [comment]
instead of `/me` endpoint we now use `GET /auth`
