### ISSUE TITLE
Tree position is not correctly indexed by custom indexer models

### ISSUE THREAD

**Issue by fquffio** [bedita/bedita#989]
When saving an object, its tree position is not correctly indexed by custom indexer models.

Custom indexer models act in place of `SearchText` model, which is bound to `afterSave` event in each BEdita object model. Tree position, though, is saved later, thus when an object is indexed, the custom indexer model can only know its last position on the tree. This requires a double save in order for objects to be shown in their correct position.

**Comment by batopa** [comment]
obsolete
